CREATE TABLE `wf_schedule_query_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `portfolio_id` BIGINT UNSIGNED NOT NULL COMMENT '来源作品集ID',
  `portfolio_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'PERSONAL个人 TEAM团队',
  `portfolio_title_snapshot` VARCHAR(100) NOT NULL COMMENT '来源作品集标题快照',
  `visit_record_id` BIGINT UNSIGNED NOT NULL COMMENT '访问汇总记录ID',
  `visitor_id` BIGINT UNSIGNED NULL COMMENT '全局访客ID',
  `visitor_key` CHAR(64) NOT NULL COMMENT '匿名访客摘要',
  `owner_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'USER用户 TEAM团队',
  `owner_id` BIGINT UNSIGNED NOT NULL COMMENT '记录归属用户或团队ID',
  `source_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UNKNOWN' COMMENT '访问来源类型',
  `display_mode` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MODAL_CALENDAR' COMMENT '查档组件展示方式',
  `queried_date` DATE NOT NULL COMMENT '查询日期',
  `slot_definition_id` BIGINT UNSIGNED NOT NULL COMMENT '档位定义ID',
  `slot_name_snapshot` VARCHAR(50) NOT NULL COMMENT '档位名称快照',
  `start_time_snapshot` TIME NULL COMMENT '开始时间快照',
  `end_time_snapshot` TIME NULL COMMENT '结束时间快照',
  `color_snapshot` VARCHAR(16) NULL COMMENT '展示颜色快照',
  `result_status` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '查询结果状态',
  `result_status_text` VARCHAR(32) NOT NULL COMMENT '查询结果状态文案',
  `available` TINYINT UNSIGNED NOT NULL COMMENT '是否可约：1是 0否',
  `result_message` VARCHAR(100) NOT NULL COMMENT '查询结果提示',
  `queried_at` DATETIME(3) NOT NULL COMMENT '查询成功时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，已删除时为主键ID',
  `version` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_schedule_query_owner_portfolio_time` (`owner_type`, `owner_id`, `portfolio_type`, `queried_at`, `id`),
  KEY `idx_schedule_query_visit_time` (`visit_record_id`, `queried_at`),
  KEY `idx_schedule_query_portfolio_time` (`portfolio_id`, `queried_at`),
  CONSTRAINT `chk_schedule_query_portfolio_type` CHECK (`portfolio_type` IN ('PERSONAL', 'TEAM')),
  CONSTRAINT `chk_schedule_query_owner_type` CHECK (`owner_type` IN ('USER', 'TEAM')),
  CONSTRAINT `chk_schedule_query_available` CHECK (`available` IN (0, 1)),
  CONSTRAINT `chk_schedule_query_time` CHECK (`start_time_snapshot` <= `end_time_snapshot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  ROW_FORMAT=DYNAMIC COMMENT='访客查询档期记录';
