-- ============================================================
-- WeFolio V7 — 初始化一期积分规则
-- 说明: 一期不接入微信充值接口，仅配置维护、访问和后台人工加分以外的消耗规则。
-- ============================================================

INSERT INTO `wf_point_rule` (
  `rule_code`,
  `rule_version`,
  `rule_name`,
  `transaction_type`,
  `scene_code`,
  `calc_mode`,
  `unit_count`,
  `points_value`,
  `config_json`,
  `effective_from`,
  `effective_to`,
  `status`,
  `version`,
  `created_at`,
  `updated_at`,
  `deleted`
) VALUES
  (
    'UPLOAD_IMAGE',
    1,
    '上传图片作品',
    'CONSUMPTION',
    'UPLOAD_IMAGE',
    'FIXED_PER_ACTION',
    1,
    1,
    JSON_OBJECT('source', 'PRD_7_12'),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'UPLOAD_VIDEO',
    1,
    '上传视频作品',
    'CONSUMPTION',
    'UPLOAD_VIDEO',
    'FIXED_PER_ACTION',
    1,
    5,
    JSON_OBJECT('source', 'PRD_7_12'),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'CREATE_TEAM',
    1,
    '新建团队',
    'CONSUMPTION',
    'CREATE_TEAM',
    'FIXED_PER_ACTION',
    1,
    1000,
    JSON_OBJECT('source', 'PRD_7_12'),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'MAINTAIN_STANDARD_PORTFOLIO',
    1,
    '维护标准作品集',
    'CONSUMPTION',
    'MAINTAIN_STANDARD_PORTFOLIO',
    'FIXED_PER_ACTION',
    1,
    1,
    JSON_OBJECT('source', 'PRD_7_12'),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'MAINTAIN_ADVANCED_PORTFOLIO',
    1,
    '维护高级作品集',
    'CONSUMPTION',
    'MAINTAIN_ADVANCED_PORTFOLIO',
    'FIXED_PER_ACTION',
    1,
    10,
    JSON_OBJECT('source', 'PRD_7_12'),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'VISIT_PERSONAL_PORTFOLIO',
    1,
    '访问个人作品集',
    'CONSUMPTION',
    'VISIT_PERSONAL_PORTFOLIO',
    'FIXED_PER_ACTION',
    1,
    1,
    JSON_OBJECT('source', 'PRD_7_12', 'dedupeWindowHours', 2),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'VIEW_PORTFOLIO_IMAGES',
    1,
    '查看作品集图片',
    'CONSUMPTION',
    'VIEW_PORTFOLIO_IMAGES',
    'ACCUMULATED_THRESHOLD',
    10,
    1,
    JSON_OBJECT('source', 'PRD_7_12', 'dedupeWindowHours', 2),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  ),
  (
    'VIEW_PORTFOLIO_VIDEO',
    1,
    '查看作品集视频',
    'CONSUMPTION',
    'VIEW_PORTFOLIO_VIDEO',
    'FIXED_PER_ACTION',
    1,
    1,
    JSON_OBJECT('source', 'PRD_7_12', 'dedupeWindowHours', 2),
    '2026-01-01 00:00:00.000',
    NULL,
    'ACTIVE',
    0,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3),
    0
  );
