const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function readProjectFile(filePath) {
  return fs.readFileSync(path.join(__dirname, '..', filePath), 'utf8')
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

test('mine balance band navigates to points page without recharge bubbling', () => {
  const appJson = JSON.parse(readProjectFile('app.json'))
  const indexJs = readProjectFile('pages/index/index.js')
  const indexWxml = readProjectFile('pages/index/index.wxml')

  assert.ok(appJson.pages.includes('pages/points/points'))
  assert.ok(appJson.pages.includes('pages/points-rules/points-rules'))
  assert.match(indexJs, /const POINTS_PAGE_URL = '\/pages\/points\/points'/)
  assert.match(indexJs, /handlePointsTap\(\)[\s\S]*url:\s*POINTS_PAGE_URL/)
  assert.match(indexWxml, /class="balance-band"[\s\S]*bindtap="handlePointsTap"/)
  assert.match(indexWxml, /class="light-button"[\s\S]*catchtap="handleRechargeTap"[\s\S]*>充值</)
})

test('points page matches design structure and backend endpoints', () => {
  const pointsJsPath = path.join(__dirname, '../pages/points/points.js')
  const pointsJsonPath = path.join(__dirname, '../pages/points/points.json')
  const pointsWxmlPath = path.join(__dirname, '../pages/points/points.wxml')
  const pointsWxssPath = path.join(__dirname, '../pages/points/points.wxss')

  assert.equal(fs.existsSync(pointsJsPath), true)
  assert.equal(fs.existsSync(pointsJsonPath), true)
  assert.equal(fs.existsSync(pointsWxmlPath), true)
  assert.equal(fs.existsSync(pointsWxssPath), true)

  const pointsJs = fs.readFileSync(pointsJsPath, 'utf8')
  const pointsWxml = fs.readFileSync(pointsWxmlPath, 'utf8')
  const pointsWxss = fs.readFileSync(pointsWxssPath, 'utf8')
  const metricGridRule = readRule(pointsWxss, '.points-metric-grid')
  const metricRule = readRule(pointsWxss, '.points-metric')
  const metricDividerRule = readRule(pointsWxss, '.points-metric + .points-metric')
  const contentRule = readRule(pointsWxss, '.points-content')
  const balanceRule = readRule(pointsWxss, '.points-balance-band')
  const ledgerRowRule = readRule(pointsWxss, '.ledger-row')
  const ledgerHeadingRule = readRule(pointsWxss, '.ledger-heading')
  const ledgerActionRule = readRule(pointsWxss, '.ledger-action')
  const ruleLinkRule = readRule(pointsWxss, '.rule-link')
  const ledgerDescViewportRule = readRule(pointsWxss, '.ledger-desc-viewport')
  const ledgerDescTextRule = readRule(pointsWxss, '.ledger-desc-text')
  const ledgerDescAutoScrollRule = readRule(pointsWxss, '.ledger-desc-text.is-auto-scrolling')

  assert.match(pointsJs, /const POINT_OVERVIEW_URL = '\/api\/mine\/points'/)
  assert.match(pointsJs, /const POINT_TRANSACTIONS_URL = '\/api\/mine\/points\/transactions'/)
  assert.match(pointsJs, /const POINT_RULES_PAGE_URL = '\/pages\/points-rules\/points-rules'/)
  assert.match(pointsJs, /normalizePointOverview/)
  assert.match(pointsJs, /normalizePointTransactions/)
  assert.match(pointsJs, /handleRuleTap/)
  assert.match(pointsJs, /handleLoadMore/)
  assert.match(pointsWxml, /navigation-bar title="我的积分" back="\{\{true\}\}"/)
  assert.match(pointsWxml, /bindscrolltolower="handleLoadMore"/)
  assert.match(pointsWxml, /当前可用积分/)
  assert.match(pointsWxml, /catchtap="handleRechargeTap"[\s\S]*>去充值</)
  assert.match(pointsWxml, /积分流水/)
  assert.match(pointsWxml, /class="panel-heading ledger-heading"[\s\S]*class="ledger-action"[\s\S]*<view class="rule-link"[\s\S]*aria-role="button"/)
  assert.doesNotMatch(pointsWxml, /<button class="rule-link"/)
  assert.match(pointsWxml, /bindtap="handleRuleTap"[\s\S]*查看积分规则/)
  assert.match(pointsWxml, /wx:for="\{\{pointData\.metrics\}\}"/)
  assert.match(pointsWxml, /wx:for="\{\{transactionData\.records\}\}"/)
  assert.match(pointsWxml, /<view class="ledger-desc-viewport">/)
  assert.match(pointsWxml, /class="ledger-desc-text \{\{item\.marqueeEnabled \? 'is-auto-scrolling' : ''\}\}"/)
  assert.match(pointsWxml, /--ledger-marquee-distance:\s*-\{\{item\.marqueeDistance\}\}px/)
  assert.match(pointsWxml, /--ledger-marquee-duration:\s*\{\{item\.marqueeDuration\}\}s/)
  assert.doesNotMatch(pointsWxml, /<scroll-view class="ledger-desc-scroll"/)
  assert.match(metricGridRule, /display:\s*flex/)
  assert.match(metricGridRule, /gap:\s*0/)
  assert.match(metricGridRule, /border:\s*1rpx solid #e9ecef/)
  assert.match(metricGridRule, /border-radius:\s*48rpx/)
  assert.match(metricRule, /border:\s*0/)
  assert.match(metricDividerRule, /border-left:\s*1rpx solid #f1f3f5/)
  assert.match(contentRule, /padding:\s*20rpx 32rpx/)
  assert.match(balanceRule, /border:\s*1rpx solid #e9ecef/)
  assert.match(balanceRule, /border-radius:\s*48rpx/)
  assert.match(balanceRule, /background:\s*#ffffff/)
  assert.doesNotMatch(metricGridRule, /display:\s*grid/)
  assert.match(ledgerRowRule, /display:\s*flex/)
  assert.match(ledgerHeadingRule, /width:\s*100%/)
  assert.match(ledgerHeadingRule, /align-items:\s*flex-start/)
  assert.match(ledgerActionRule, /flex:\s*1 1 0/)
  assert.match(ledgerActionRule, /align-items:\s*flex-start/)
  assert.match(ledgerActionRule, /justify-content:\s*flex-end/)
  assert.match(ruleLinkRule, /width:\s*196rpx/)
  assert.match(ruleLinkRule, /flex:\s*0 0 196rpx/)
  assert.match(ruleLinkRule, /margin:\s*0/)
  assert.match(ruleLinkRule, /text-align:\s*center/)
  assert.match(ledgerDescViewportRule, /width:\s*100%/)
  assert.match(ledgerDescViewportRule, /overflow:\s*hidden/)
  assert.doesNotMatch(ledgerDescViewportRule, /text-overflow:\s*ellipsis/)
  assert.match(ledgerDescTextRule, /display:\s*inline-block/)
  assert.match(ledgerDescTextRule, /min-width:\s*100%/)
  assert.match(ledgerDescTextRule, /white-space:\s*nowrap/)
  assert.doesNotMatch(ledgerDescTextRule, /text-overflow:\s*ellipsis/)
  assert.match(ledgerDescAutoScrollRule, /animation-name:\s*ledger-desc-auto-scroll/)
  assert.match(ledgerDescAutoScrollRule, /animation-duration:\s*var\(--ledger-marquee-duration\)/)
  assert.match(ledgerDescAutoScrollRule, /animation-iteration-count:\s*infinite/)
  assert.match(ledgerDescAutoScrollRule, /animation-direction:\s*alternate/)
  assert.match(pointsWxss, /@keyframes\s+ledger-desc-auto-scroll\s*\{[\s\S]*0%,\s*15%\s*\{[\s\S]*translateX\(0\)[\s\S]*85%,\s*100%\s*\{[\s\S]*translateX\(var\(--ledger-marquee-distance\)\)/)
})

test('points rules page dynamically renders grouped backend rules', () => {
  const rulesJsPath = path.join(__dirname, '../pages/points-rules/points-rules.js')
  const rulesJsonPath = path.join(__dirname, '../pages/points-rules/points-rules.json')
  const rulesWxmlPath = path.join(__dirname, '../pages/points-rules/points-rules.wxml')
  const rulesWxssPath = path.join(__dirname, '../pages/points-rules/points-rules.wxss')

  assert.equal(fs.existsSync(rulesJsPath), true)
  assert.equal(fs.existsSync(rulesJsonPath), true)
  assert.equal(fs.existsSync(rulesWxmlPath), true)
  assert.equal(fs.existsSync(rulesWxssPath), true)

  const rulesJs = fs.readFileSync(rulesJsPath, 'utf8')
  const rulesWxml = fs.readFileSync(rulesWxmlPath, 'utf8')
  const rulesWxss = fs.readFileSync(rulesWxssPath, 'utf8')
  const costGroupRule = readRule(rulesWxss, '.cost-group')
  const costLineRule = readRule(rulesWxss, '.cost-line')
  const giftMarkRule = readRule(rulesWxss, '.cost-mark.gift')
  const giftDescRule = readRule(rulesWxss, '.gift-desc')
  const giftChipRule = readRule(rulesWxss, '.cost-chip.gift')

  assert.match(rulesJs, /const POINT_OVERVIEW_URL = '\/api\/mine\/points'/)
  assert.match(rulesJs, /normalizePointOverview/)
  assert.match(rulesWxml, /navigation-bar title="积分规则" back="\{\{true\}\}"/)
  assert.match(rulesWxml, /section-title">积分具体规则</)
  assert.doesNotMatch(rulesWxml, /acquisition-panel|acquisition-board|section-title">积分获取</)
  assert.match(rulesWxml, /wx:if="\{\{pointData\.ruleGroups\.length \|\| pointData\.acquisitionRules\.length\}\}" class="cost-board"/)
  assert.match(rulesWxml, /wx:for="\{\{pointData\.ruleGroups\}\}"[\s\S]*class="cost-group gift-group"/)
  assert.match(rulesWxml, /class="cost-mark gift">赠送</)
  assert.match(rulesWxml, /wx:for="\{\{pointData\.acquisitionRules\}\}"/)
  assert.match(rulesWxml, /rule\.title/)
  assert.match(rulesWxml, /rule\.desc/)
  assert.match(rulesWxml, /rule\.pointsText/)
  assert.match(rulesWxml, /wx:for="\{\{pointData\.ruleGroups\}\}"/)
  assert.match(rulesWxml, /wx:for="\{\{item\.rules\}\}"/)
  assert.match(rulesWxml, /item\.groupText/)
  assert.match(rulesWxml, /rule\.costText/)
  assert.doesNotMatch(rulesWxml, /积分消耗具体规则/)
  assert.doesNotMatch(rulesWxml, /section-title">积分消耗</)
  assert.doesNotMatch(rulesWxml, /当前启用规则由后台配置下发/)
  assert.doesNotMatch(rulesWxml, /完整规则/)
  assert.match(rulesWxml, /扣费归属/)
  assert.match(rulesWxml, /团队无积分账户/)
  assert.match(costGroupRule, /display:\s*flex/)
  assert.match(costLineRule, /display:\s*flex/)
  assert.match(giftMarkRule, /color:\s*#5c9e6e/)
  assert.match(giftMarkRule, /background:\s*#ffffff/)
  assert.match(giftDescRule, /white-space:\s*normal/)
  assert.match(giftChipRule, /color:\s*#5c9e6e/)
  assert.match(giftChipRule, /background:\s*#ffffff/)
})
