const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8'))

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

function assertPageRegistered(pagePath) {
  assert.ok(appJson.pages.includes(pagePath), `${pagePath} should be registered`)
}

function assertUsesNavigation(pagePath) {
  const json = JSON.parse(read(`${pagePath}.json`))
  assert.equal(json.usingComponents['navigation-bar'], '/components/navigation-bar/navigation-bar')
}

test('app registers portfolio pages', () => {
  [
    'pages/portfolios/portfolios',
    'pages/portfolio-standard-edit/portfolio-standard-edit',
    'pages/portfolio-component-library/portfolio-component-library',
    'pages/portfolio-standard-preview/portfolio-standard-preview',
    'pages/visitor-portfolio/visitor-portfolio',
    'pages/visitor-schedule/visitor-schedule',
    'pages/portfolio-unavailable/portfolio-unavailable'
  ].forEach(assertPageRegistered)
})

test('portfolio pages use custom navigation bar', () => {
  [
    'pages/portfolios/portfolios',
    'pages/portfolio-standard-edit/portfolio-standard-edit',
    'pages/portfolio-component-library/portfolio-component-library',
    'pages/portfolio-standard-preview/portfolio-standard-preview',
    'pages/visitor-portfolio/visitor-portfolio',
    'pages/visitor-schedule/visitor-schedule',
    'pages/portfolio-unavailable/portfolio-unavailable'
  ].forEach(assertUsesNavigation)
})

test('bottom portfolio tabs navigate to portfolio list page', () => {
  [
    'pages/index/index.js',
    'pages/schedule/schedule.js',
    'pages/works/works.js'
  ].forEach((pagePath) => {
    const pageJs = read(pagePath)

    assert.match(pageJs, /PORTFOLIOS_PAGE_URL\s*=\s*'\/pages\/portfolios\/portfolios'/)
    assert.match(pageJs, /label === '作品集'[\s\S]*wx\.redirectTo\(\{[\s\S]*url:\s*PORTFOLIOS_PAGE_URL/)
    assert.doesNotMatch(pageJs, /title:\s*`\$\{label\}页面接入中`[\s\S]*label === '作品集'/)
  })
})

test('maintainer portfolio pages expose expected controls', () => {
  const listWxml = read('pages/portfolios/portfolios.wxml')
  const listWxss = read('pages/portfolios/portfolios.wxss')
  const listJs = read('pages/portfolios/portfolios.js')
  const portfolioActionButtonRule = readRule(listWxss, '.portfolio-action-button')
  const portfolioActionButtonPublishRule = readRule(listWxss, '.portfolio-action-button.publish')
  const editWxml = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxml')
  const libraryWxml = read('pages/portfolio-component-library/portfolio-component-library.wxml')
  const previewWxml = read('pages/portfolio-standard-preview/portfolio-standard-preview.wxml')
  const unavailableWxml = read('pages/portfolio-unavailable/portfolio-unavailable.wxml')

  assert.match(listWxml, /个人/)
  assert.match(listWxml, /团队/)
  assert.match(listWxml, /class="portfolio-list-panel/)
  assert.match(listWxml, /个人作品集/)
  assert.match(listWxml, /class="summary-pill published/)
  assert.match(listWxml, /class="summary-pill draft/)
  assert.match(listWxml, /class="portfolio-item-card/)
  assert.match(listWxml, /class="portfolio-cover/)
  assert.match(listWxml, /class="portfolio-side/)
  assert.match(listWxml, /class="portfolio-action-row/)
  assert.match(listWxml, /wx:if="\{\{item\.showPublishedPreview\}\}"[\s\S]*data-action="PREVIEW_PUBLISHED"[\s\S]*预览/)
  assert.match(listWxml, /wx:if="\{\{item\.showDraftPreview\}\}"[\s\S]*data-action="PREVIEW_DRAFT"[\s\S]*catchtap="handleDraftPreviewTap"[\s\S]*预览/)
  assert.match(listWxml, /class="portfolio-action-button/)
  assert.match(listWxml, /wx:if="\{\{item\.actionType === 'SHARE'\}\}"[\s\S]*class="portfolio-action-button share"[\s\S]*open-type="share"[\s\S]*data-id="\{\{item\.portfolioId\}\}"[\s\S]*分享/)
  assert.doesNotMatch(listWxml, /class="portfolio-icon-button share"/)
  assert.doesNotMatch(listWxml, /class="portfolio-share-hit"/)
  assert.doesNotMatch(listWxml, /class="portfolio-share-icon"/)
  assert.match(listWxml, /class="portfolio-arrow/)
  assert.match(listWxml, /class="portfolio-swipe-row \{\{revealedPortfolioId === item\.portfolioId \? 'revealed' : ''\}\}"/)
  assert.match(listWxml, /bindtouchstart="handlePortfolioTouchStart"[\s\S]*bindtouchmove="handlePortfolioTouchMove"[\s\S]*bindtouchend="handlePortfolioTouchEnd"[\s\S]*bindtouchcancel="handlePortfolioTouchCancel"/)
  assert.match(listWxml, /class="portfolio-delete-pane"[\s\S]*class="portfolio-delete-button"[\s\S]*catchtap="handleDeletePortfolioTap"[\s\S]*删除/)
  assert.match(listWxml, /class="create-actions/)
  assert.match(listWxml, /新建标准个人作品集/)
  assert.match(listWxml, /新建高级个人作品集/)
  assert.match(listWxml, /class="tabbar"/)
  assert.match(listWxml, /item\.active/)
  assert.match(listWxss, /\.portfolios-page\s*\{[\s\S]*height:\s*100vh;[\s\S]*display:\s*flex;[\s\S]*overflow:\s*hidden;/)
  assert.match(listWxss, /\.portfolio-content\s*\{[\s\S]*padding:\s*28rpx 28rpx calc\(172rpx \+ env\(safe-area-inset-bottom\)\);/)
  assert.match(listWxss, /\.portfolio-list-panel\s*\{[\s\S]*border-radius:\s*16rpx;[\s\S]*box-shadow:/)
  assert.match(listWxss, /\.portfolio-swipe-row\.revealed \.portfolio-item-card\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(listWxss, /\.portfolio-delete-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(listWxss, /\.portfolio-delete-button\s*\{[\s\S]*width:\s*128rpx;[\s\S]*height:\s*100%;[\s\S]*border-radius:\s*0;/)
  assert.match(listWxss, /\.portfolio-item-card\s*\{[\s\S]*min-height:\s*180rpx;[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(listWxss, /\.portfolio-cover\s*\{[\s\S]*width:\s*140rpx;[\s\S]*height:\s*112rpx;/)
  assert.match(portfolioActionButtonRule, /height:\s*56rpx/)
  assert.match(portfolioActionButtonRule, /border-radius:\s*14rpx/)
  assert.match(portfolioActionButtonRule, /color:\s*#425061/)
  assert.match(portfolioActionButtonRule, /border:\s*1rpx\s+solid\s+#d6dee7/)
  assert.match(portfolioActionButtonRule, /background:\s*#f3f6f9/)
  assert.doesNotMatch(portfolioActionButtonRule, /box-shadow:/)
  assert.match(portfolioActionButtonPublishRule, /color:\s*#211a0f/)
  assert.match(portfolioActionButtonPublishRule, /border-color:\s*#c79035/)
  assert.match(portfolioActionButtonPublishRule, /background:\s*#d9a84a/)
  assert.match(listWxss, /\.portfolio-action-button\.share\s*\{[\s\S]*color:\s*#425061;[\s\S]*border-color:\s*#d6dee7;[\s\S]*background:\s*#f3f6f9;/)
  assert.match(listWxss, /\.portfolio-action-button\.share:active\s*\{[\s\S]*background:\s*#e9eff5;/)
  assert.doesNotMatch(listWxss, /\.portfolio-icon-button\s*\{/)
  assert.doesNotMatch(listWxss, /\.portfolio-share-icon\s*\{/)
  assert.doesNotMatch(listWxss, /\.portfolio-share-hit\s*\{/)
  assert.match(listWxss, /\.create-actions\s*\{[\s\S]*display:\s*flex;[\s\S]*gap:\s*16rpx;[\s\S]*margin:\s*24rpx 0 0;/)
  assert.doesNotMatch(listWxss, /\.create-actions\s*\{[\s\S]*grid-template-columns:/)
  assert.match(listWxss, /\.tabbar\s*\{[\s\S]*position:\s*fixed;[\s\S]*bottom:\s*0;/)
  assert.match(listJs, /const \{ normalizeId \} = require\('\.\.\/\.\.\/utils\/id'\)/)
  assert.match(listJs, /revealedPortfolioId:\s*null/)
  assert.match(listJs, /handlePortfolioTouchStart/)
  assert.match(listJs, /handleDeletePortfolioTap/)
  assert.match(listJs, /handleDraftPreviewTap/)
  assert.match(editWxml, /分享信息/)
  assert.match(editWxml, /分享封面/)
  assert.match(editWxml, /class="cover-preview"[\s\S]*bindtap="handleChooseShareCover"/)
  assert.match(editWxml, /class="cover-preview"[\s\S]*aria-label="选择分享封面"/)
  assert.doesNotMatch(editWxml, /class="cover-preview"[\s\S]*更换分享封面/)
  assert.doesNotMatch(editWxml, /class="cover-actions"/)
  assert.doesNotMatch(editWxml, /class="cover-action-button"/)
  assert.doesNotMatch(editWxml, /bindtap="handleRemoveShareCover"/)
  assert.match(editWxml, /组件编排/)
  assert.match(editWxml, /class="component-list"/)
  assert.match(editWxml, /保存草稿/)
  assert.match(editWxml, /预览草稿/)
  assert.match(editWxml, /请保存后预览/)
  assert.match(editWxml, /<button[^>]*bindtap="handlePreview"[^>]*>[\s\S]*预览草稿[\s\S]*请保存后预览[\s\S]*<\/button>/)
  assert.doesNotMatch(editWxml, />发布<\/button>/)
  assert.doesNotMatch(editWxml, /bindtap="handlePublish"/)
  assert.match(editWxml, /二维码联系/)
  assert.doesNotMatch(editWxml, /class="component-hints"/)
  assert.doesNotMatch(editWxml, /class="hint-chip"/)
  assert.match(libraryWxml, /轮播图/)
  assert.match(libraryWxml, /双列作品列表/)
  assert.match(libraryWxml, /二维码联系/)
  assert.match(libraryWxml, /预留联系信息/)
  assert.match(previewWxml, /预览/)
  assert.match(previewWxml, /禁用真实提交/)
  assert.doesNotMatch(previewWxml, /返回编辑/)
  assert.doesNotMatch(previewWxml, /bindtap="handleBackToEditor"/)
  assert.doesNotMatch(previewWxml, /maintenance-mask/)
  ;[
    'CAROUSEL',
    'PROFILE',
    'WORK_GRID',
    'WORK_LIST',
    'SCHEDULE_QUERY',
    'QR_CONTACT',
    'CONTACT_FORM',
    'TEXT_SECTION'
  ].forEach((componentType) => {
    assert.match(previewWxml, new RegExp(`item\\.componentType === '${componentType}'`))
  })
  assert.match(unavailableWxml, /暂未开放/)
})

test('visitor portfolio pages expose maintenance, QR, contact and schedule surfaces', () => {
  const visitorWxml = read('pages/visitor-portfolio/visitor-portfolio.wxml')
  const scheduleWxml = read('pages/visitor-schedule/visitor-schedule.wxml')

  assert.match(visitorWxml, /UNDER MAINTENANCE/)
  assert.match(visitorWxml, /二维码联系/)
  assert.match(visitorWxml, /预留联系信息/)
  assert.match(visitorWxml, /提交/)
  ;[
    'CAROUSEL',
    'PROFILE',
    'WORK_GRID',
    'WORK_LIST',
    'SCHEDULE_QUERY',
    'QR_CONTACT',
    'CONTACT_FORM',
    'TEXT_SECTION'
  ].forEach((componentType) => {
    assert.match(visitorWxml, new RegExp(`item\\.componentType === '${componentType}'`))
  })
  assert.match(visitorWxml, /bindtap="handlePreviewQr"/)
  assert.match(scheduleWxml, /档期查询/)
  assert.match(scheduleWxml, /查询/)
  assert.doesNotMatch(scheduleWxml, /联系人电话/)
  assert.doesNotMatch(scheduleWxml, /内部备注/)
})

test('portfolio create action buttons align to the list panel width', () => {
  const listWxss = read('pages/portfolios/portfolios.wxss')

  assert.match(listWxss, /\.create-actions\s*\{[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(listWxss, /\.create-action\s*\{[\s\S]*flex:\s*1 1 0;[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;[\s\S]*margin:\s*0;[\s\S]*box-sizing:\s*border-box;/)
})

test('portfolio list cards keep action buttons from squeezing title copy', () => {
  const listWxss = read('pages/portfolios/portfolios.wxss')

  assert.match(listWxss, /\.portfolio-copy\s*\{[\s\S]*min-width:\s*0;[\s\S]*flex:\s*1 1 0;/)
  assert.match(listWxss, /\.portfolio-side\s*\{[\s\S]*flex:\s*0 0 auto;[\s\S]*min-width:\s*0;[\s\S]*gap:\s*12rpx;/)
  assert.match(listWxss, /\.portfolio-action-row\s*\{[\s\S]*flex:\s*0 0 auto;[\s\S]*max-width:\s*226rpx;[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*gap:\s*10rpx;/)
  assert.match(listWxss, /\.portfolio-action-button\s*\{[\s\S]*width:\s*108rpx;[\s\S]*min-width:\s*108rpx;[\s\S]*max-width:\s*108rpx;[\s\S]*flex:\s*none;[\s\S]*box-sizing:\s*border-box;/)
  assert.doesNotMatch(listWxss, /\.portfolio-card-actions\s*\{/)
})

test('portfolio list cards show cover title update time and status as item information', () => {
  const listWxml = read('pages/portfolios/portfolios.wxml')
  const listWxss = read('pages/portfolios/portfolios.wxss')
  const listJs = read('pages/portfolios/portfolios.js')

  assert.match(listWxml, /class="portfolio-cover"/)
  assert.match(listWxml, /item\.coverUrl/)
  assert.match(listWxml, /class="portfolio-title"[\s\S]*item\.title/)
  assert.match(listWxml, /class="portfolio-meta"[\s\S]*item\.updatedText/)
  assert.match(listWxml, /class="portfolio-badges"[\s\S]*class="status-badge \{\{item\.statusTone\}\}"[\s\S]*item\.statusText/)
  assert.match(listWxml, /class="status-badge \{\{item\.statusTone\}\}"/)
  assert.match(listWxml, /item\.statusText/)
  assert.doesNotMatch(listWxml, /item\.templateText/)
  assert.doesNotMatch(listWxml, /item\.revisionText/)
  assert.doesNotMatch(listWxml, /item\.metricText/)
  assert.doesNotMatch(listWxml, /class="metric-badge/)
  assert.match(listWxss, /\.portfolio-badges\s*\{[\s\S]*margin-top:\s*14rpx;[\s\S]*gap:\s*12rpx;[\s\S]*flex-wrap:\s*wrap;/)
  assert.match(listWxss, /\.status-badge\s*\{[\s\S]*height:\s*44rpx;[\s\S]*padding:\s*0 18rpx;[\s\S]*font-size:\s*22rpx;[\s\S]*font-weight:\s*800;/)
  assert.match(listWxss, /\.status-badge\.published\s*\{[\s\S]*background:\s*#edf5fb;/)
  assert.match(listWxss, /\.status-badge\.draft\s*\{[\s\S]*background:\s*#fff4d7;/)
  assert.match(listWxss, /\.status-badge\.muted\s*\{[\s\S]*background:\s*#f2f5f8;/)
  assert.doesNotMatch(listJs, /templateText:/)
  assert.doesNotMatch(listJs, /revisionText:/)
  assert.doesNotMatch(listJs, /metricText:/)
  assert.doesNotMatch(listJs, /resolveTemplateText/)
  assert.doesNotMatch(listJs, /resolveMetricText/)
  assert.doesNotMatch(listJs, /草稿\s*\$\{[^}]*Revision/)
  assert.doesNotMatch(listJs, /正式\s*\$\{[^}]*Revision/)
  assert.match(listJs, /onShareAppMessage/)
  assert.match(listJs, /pages\/visitor-portfolio\/visitor-portfolio\?shareCode=/)
  assert.match(listJs, /imageUrl:\s*portfolio\.coverUrl/)
})

test('portfolio list delete action stays hidden at rest and centers its label when revealed', () => {
  const listWxss = read('pages/portfolios/portfolios.wxss')

  assert.match(listWxss, /\.portfolio-delete-pane\s*\{[\s\S]*transform:\s*translateX\(100%\);[\s\S]*opacity:\s*0;[\s\S]*pointer-events:\s*none;/)
  assert.match(listWxss, /\.portfolio-swipe-row\.revealed \.portfolio-delete-pane\s*\{[\s\S]*transform:\s*translateX\(0\);[\s\S]*opacity:\s*1;[\s\S]*pointer-events:\s*auto;/)
  assert.match(listWxss, /\.portfolio-delete-button\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*center;/)
})

test('portfolio editor component delete action stays hidden at rest and while dragging', () => {
  const editWxss = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxss')

  assert.match(editWxss, /\.component-remove-pane\s*\{[\s\S]*transform:\s*translateX\(100%\);[\s\S]*opacity:\s*0;[\s\S]*pointer-events:\s*none;/)
  assert.match(editWxss, /\.component-swipe-row\.revealed \.component-remove-pane\s*\{[\s\S]*transform:\s*translateX\(0\);[\s\S]*opacity:\s*1;[\s\S]*pointer-events:\s*auto;/)
  assert.match(editWxss, /\.component-swipe-row\.dragging \.component-remove-pane\s*\{[\s\S]*transform:\s*translateX\(100%\);[\s\S]*opacity:\s*0;[\s\S]*pointer-events:\s*none;/)
})

test('standard personal portfolio editor follows shared maintainer layout', () => {
  const editWxml = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxml')
  const editWxss = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxss')
  const editJs = read('pages/portfolio-standard-edit/portfolio-standard-edit.js')

  assert.match(editWxml, /class="edit-content"/)
  assert.match(editWxml, /class="panel share-panel"/)
  assert.match(editWxml, /class="panel component-panel"/)
  assert.match(editWxml, /class="section-desc"/)
  assert.match(editWxml, /class="field-heading"/)
  assert.match(editWxml, /class="field-heading"[\s\S]*作品集标题[\s\S]*\{\{shareFieldCounters\.title\}\}/)
  assert.doesNotMatch(editWxml, /分享简介/)
  assert.doesNotMatch(editWxml, /shareFieldCounters\.intro/)
  assert.match(editWxml, /data-path="share\.title"[\s\S]*maxlength="50"/)
  assert.match(editWxml, /class="component-work-search"/)
  assert.match(editWxml, /placeholder="搜索作品名称"/)
  assert.match(editWxml, /bindinput="handleComponentWorkKeywordInput"/)
  assert.match(editWxml, /bindconfirm="handleComponentWorkSearchConfirm"/)
  assert.match(editWxml, /class="component-work-search-clear"[\s\S]*catchtap="handleClearComponentWorkSearch"/)
  assert.match(editWxml, /wx:for="\{\{componentWorkFilterTags\}\}"/)
  assert.match(editWxml, /catchtap="handleComponentWorkTagTap"/)
  assert.match(editWxml, /bindscrolltolower="handleComponentWorkScrollToLower"/)
  assert.match(editWxml, /componentWorkLoadingMore/)
  assert.match(editJs, /componentWorkKeyword/)
  assert.match(editJs, /componentWorkFilterTags/)
  assert.match(editJs, /handleComponentWorkScrollToLower/)
  assert.match(editWxss, /\.component-work-search\s*\{/)
  assert.match(editWxss, /\.component-work-filter-scroll\s*\{/)
  assert.match(editWxss, /\.component-work-filter-pill\.active\s*\{/)
  assert.match(editWxss, /\.component-work-footer\s*\{/)
  assert.doesNotMatch(editWxml, /data-path="share\.intro"/)
  assert.doesNotMatch(editWxml, /class="input textarea"/)
  assert.match(editWxml, /class="component-list"/)
  assert.match(editWxml, /class="component-swipe-row \{\{revealedComponentKey === item\.componentKey \? 'revealed' : ''\}\} \{\{draggingIndex === index \? 'dragging' : ''\}\}"/)
  assert.match(editWxml, /class="component-order"/)
  assert.doesNotMatch(editWxml, /class="component-meta"/)
  assert.doesNotMatch(editWxml, /\{\{item\.componentType\}\} · \{\{item\.componentKey\}\}/)
  assert.match(editWxml, /class="component-drag-handle"/)
  assert.match(editWxml, /class="component-row-arrow \{\{item\.componentType === 'CAROUSEL' \|\| item\.componentType === 'PROFILE' \|\| item\.componentType === 'QR_CONTACT' \|\| item\.componentType === 'WORK_GRID' \|\| item\.componentType === 'WORK_LIST' \? '' : 'placeholder'\}\}"/)
  assert.doesNotMatch(editWxml, /wx:if="\{\{item\.componentType === 'CAROUSEL'\}\}" class="component-row-arrow"/)
  assert.match(editWxml, /class="profile-sheet-mask component-work-picker-mask \{\{profileSheetVisible \? 'visible' : ''\}\}"/)
  assert.match(editWxml, /catchtap="handleConfirmProfileSheet"/)
  assert.match(editWxml, /bindchange="handleProfileVisibleFieldChange"/)
  assert.match(editWxml, />从基础资料刷新</)
  assert.doesNotMatch(editWxml, /例如/)
  assert.doesNotMatch(editWxml, /头像地址/)
  assert.doesNotMatch(editWxml, /data-field="avatarUrl"/)
  assert.doesNotMatch(editWxml, /头像图片 URL/)
  assert.doesNotMatch(editWxml, /微信二维码地址/)
  assert.doesNotMatch(editWxml, /data-field="wechatQrUrl"/)
  assert.doesNotMatch(editWxml, /二维码图片 URL/)
  assert.doesNotMatch(editWxml, /profileFieldCounters\.wechatQrUrl/)
  assert.doesNotMatch(editWxml, /handleRemoveProfileAvatar/)
  assert.doesNotMatch(editWxml, /profile-avatar-remove/)
  assert.doesNotMatch(editWxml, />移除</)
  assert.doesNotMatch(editWxml, /class="profile-form-section-title">资料副本/)
  assert.match(editWxml, /class="profile-sheet-fields-panel"/)
  assert.match(editWxml, /class="profile-avatar-editor"/)
  assert.match(editWxml, /catchtap="handleChooseProfileAvatar"/)
  assert.match(editWxml, /class="profile-qr-editor"/)
  assert.match(editWxml, /src="{{profileForm\.wechatQrUrl}}"/)
  assert.match(editWxml, /catchtap="handleChooseProfileWechatQr"/)
  assert.match(editWxml, /class="profile-field-limit"/)
  assert.match(editWxml, /maxlength="50"/)
  assert.match(editWxml, /maxlength="500"/)
  assert.match(editWxml, /class="component-remove-pane"/)
  assert.match(editWxml, /class="component-remove-button"/)
  assert.match(editWxml, /class="action-button secondary-button(?: [^"]*)?"/)
  assert.match(editWxml, /class="action-button primary-button"/)
  assert.match(editWxml, /style="\{\{draggingIndex === index \? componentDragStyle : ''\}\}"/)
  assert.match(editWxml, /data-type="\{\{item\.componentType\}\}"/)
  assert.match(editWxml, /catchtap="handleComponentTap"/)
  assert.match(editWxml, /class="component-picker-mask \{\{componentSheetVisible \? 'visible' : ''\}\}"/)
  assert.match(editWxml, /class="component-picker-panel"/)
  assert.match(editWxml, /class="component-picker-grabber"/)
  assert.match(editWxml, /class="component-work-picker-mask \{\{componentWorkSheetVisible \? 'visible' : ''\}\}"/)
  assert.match(editWxml, /wx:for="{{componentWorkOptions}}"/)
  assert.match(editWxml, /catchtap="handleToggleComponentWork"/)
  assert.match(editWxml, /catchtap="handleConfirmComponentWorks"/)
  assert.match(editWxml, /class="display-group-order \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*catchtap="handleToggleDisplayGroupTag"/)
  assert.match(editWxml, /wx:for="\{\{displayGroupWorkOptions\}\}"/)
  assert.match(editWxml, /class="display-group-work-order \{\{item\.selected \? 'selected' : ''\}\}"/)
  assert.match(editWxml, /catchtap="handleToggleDisplayGroupWork"/)
  assert.doesNotMatch(editWxml, /display-group-add-button/)
  assert.doesNotMatch(editWxml, /displayGroupFormVisible/)
  assert.doesNotMatch(editWxml, /handleDisplayGroupNameInput/)
  assert.doesNotMatch(editWxml, /handleConfirmDisplayGroupForm/)
  assert.doesNotMatch(editWxml, /handleDisplayGroupLongPress/)
  assert.doesNotMatch(editWxml, /handleDeleteDisplayGroup/)
  assert.doesNotMatch(editWxml, /handleCopyWorkTagsToDisplayGroups/)
  assert.doesNotMatch(editWxml, /handleImportWorksByTag/)
  assert.doesNotMatch(editWxml, /handleOpenDisplayGroupWorkPicker/)
  assert.doesNotMatch(editWxml, /class="display-group-row-actions"/)
  assert.doesNotMatch(editWxml, /class="display-group-row-button/)
  assert.match(editWxml, /wx:for="{{componentOptions}}"/)
  assert.match(editWxml, /data-type="{{item\.componentType}}"/)
  assert.match(editWxml, /catchtap="handleSelectComponent"/)
  assert.match(editWxml, /catchtap="handleCloseComponentSheet"/)
  assert.match(editWxml, /bindlongpress="handleComponentDragStart"/)
  assert.match(editWxml, /bindtouchstart="handleComponentTouchStart"/)
  assert.match(editWxml, /bindtouchmove="handleComponentTouchMove"/)
  assert.match(editWxml, /bindtouchend="handleComponentTouchEnd"/)
  assert.match(editWxml, /bindtouchcancel="handleComponentTouchCancel"/)
  assert.doesNotMatch(editWxml, />上移</)
  assert.doesNotMatch(editWxml, />下移</)
  assert.match(editJs, /componentSheetVisible/)
  assert.match(editJs, /revealedComponentKey/)
  assert.match(editJs, /componentDragStyle/)
  assert.match(editJs, /componentWorkSheetVisible/)
  assert.match(editJs, /profileSheetVisible/)
  assert.match(editJs, /updateComponentProfileConfig/)
  assert.match(editJs, /isEditableComponentType/)
  assert.match(editJs, /uploadPortfolioImageAsset/)
  assert.match(editJs, /PORTFOLIO_ASSET_TYPES/)
  assert.match(editJs, /handleChooseProfileAvatar/)
  assert.match(editJs, /handleChooseProfileWechatQr/)
  assert.match(editJs, /handleChooseShareCover/)
  assert.doesNotMatch(editJs, /handleRemoveShareCover/)
  assert.doesNotMatch(editJs, /handleRemoveProfileAvatar/)
  assert.match(editJs, /addComponent/)
  assert.match(editJs, /handleSelectComponent/)
  assert.match(editJs, /handleComponentTap/)
  assert.match(editJs, /updateComponentWorkIds/)
  assert.doesNotMatch(editJs, /handleOpenComponentLibrary\(\)\s*\{[\s\S]*wx\.navigateTo/)

  assert.match(editWxss, /\.portfolio-edit-page\s*\{[\s\S]*height:\s*100vh;[\s\S]*display:\s*flex;[\s\S]*overflow:\s*hidden;/)
  assert.match(editWxss, /\.edit-scroll\s*\{[\s\S]*flex:\s*1;[\s\S]*min-height:\s*0;/)
  assert.match(editWxss, /\.edit-content\s*\{[\s\S]*padding:\s*28rpx 28rpx calc\(156rpx \+ env\(safe-area-inset-bottom\)\);[\s\S]*box-sizing:\s*border-box;/)
  assert.match(editWxss, /\.panel\s*\{[\s\S]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.96\);[\s\S]*border-radius:\s*16rpx;[\s\S]*box-shadow:/)
  assert.match(editWxss, /\.field-limit\s*\{[\s\S]*color:\s*#8b96a3;[\s\S]*font-size:\s*22rpx;/)
  assert.match(editWxss, /\.input\s*\{[\s\S]*width:\s*100%;[\s\S]*min-height:\s*84rpx;[\s\S]*border-radius:\s*16rpx;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(editWxss, /\.cover-row\s*\{[\s\S]*display:\s*flex;[\s\S]*gap:/)
  assert.match(editWxss, /\.cover-preview\s*\{[\s\S]*width:\s*360rpx;[\s\S]*height:\s*288rpx;/)
  assert.doesNotMatch(editWxss, /\.cover-actions\s*\{/)
  assert.doesNotMatch(editWxss, /\.cover-action-button\s*\{/)
  assert.doesNotMatch(editWxss, /\.cover-action-button\.remove\s*\{/)
  assert.doesNotMatch(editWxss, /\.profile-avatar-remove\s*\{/)
  assert.match(editWxss, /\.component-swipe-row\s*\{[\s\S]*position:\s*relative;[\s\S]*overflow:\s*hidden;/)
  assert.match(editWxss, /\.component-row\s*\{[\s\S]*position:\s*relative;[\s\S]*display:\s*flex;[\s\S]*transition:\s*transform 180ms ease/)
  assert.match(editWxss, /\.component-swipe-row\.revealed \.component-row\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(editWxss, /\.component-remove-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(editWxss, /\.component-row\.dragging\s*\{[\s\S]*border-color:/)
  assert.match(editWxss, /\.component-drag-handle\s*\{[\s\S]*repeating-linear-gradient/)
  assert.match(editWxss, /\.component-row-arrow\s*\{[\s\S]*width:\s*28rpx;[\s\S]*flex:\s*none;/)
  assert.match(editWxss, /\.component-row-arrow\.placeholder\s*\{[\s\S]*visibility:\s*hidden;/)
  assert.match(editWxss, /\.component-picker-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;[\s\S]*background:\s*rgba\(17,\s*24,\s*39,\s*0\.35\);/)
  assert.match(editWxss, /\.component-picker-mask\.visible\s*\{[\s\S]*opacity:\s*1;[\s\S]*pointer-events:\s*auto;/)
  assert.match(editWxss, /\.component-picker-panel\s*\{[\s\S]*max-height:\s*72vh;[\s\S]*border-radius:\s*24rpx 24rpx 18rpx 18rpx;[\s\S]*transform:\s*translateY\(36rpx\);/)
  assert.match(editWxss, /\.component-picker-mask\.visible \.component-picker-panel\s*\{[\s\S]*transform:\s*translateY\(0\);/)
  assert.match(editWxss, /\.component-picker-grabber\s*\{[\s\S]*width:\s*72rpx;[\s\S]*height:\s*8rpx;/)
  assert.match(editWxss, /\.component-option\s*\{[\s\S]*width:\s*100%;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(editWxss, /\.component-work-picker-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assert.match(editWxss, /\.component-work-option\.selected\s*\{[\s\S]*border-color:/)
  assert.match(editWxss, /\.display-group-order\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(editWxss, /\.display-group-order\.selected\s*\{[\s\S]*background:\s*#17202a;/)
  assert.match(editWxss, /\.display-group-work-order\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(editWxss, /\.display-group-work-order\.selected\s*\{[\s\S]*background:\s*#17202a;/)
  assert.doesNotMatch(editWxss, /\.display-group-add-button\s*\{/)
  assert.doesNotMatch(editWxss, /\.display-group-form\s*\{/)
  assert.doesNotMatch(editWxss, /\.display-group-pill\.manage\s*\{/)
  assert.doesNotMatch(editWxss, /\.display-group-delete\s*\{/)
  assert.doesNotMatch(editWxss, /\.work-tag-import-button\s*\{/)
  assert.doesNotMatch(editWxss, /\.display-group-row-actions\s*\{/)
  assert.doesNotMatch(editWxss, /\.display-group-row-button\s*\{/)
  assert.match(editWxss, /\.bottom-actions\s*\{[\s\S]*position:\s*fixed;[\s\S]*display:\s*flex;[\s\S]*gap:\s*12rpx;/)
  assert.match(editWxss, /\.action-button\s*\{[\s\S]*flex:\s*1 1 0;[\s\S]*min-width:\s*0;[\s\S]*height:\s*88rpx;[\s\S]*border-radius:\s*16rpx;/)
})

test('standard portfolio display tag sheet shows ordered tag and work selections', () => {
  const editWxml = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxml')
  const editWxss = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxss')
  const tagScrollRule = readRule(editWxss, '.display-group-scroll')
  const activePillRule = readRule(editWxss, '.display-group-pill.active')
  const workScrollIndex = editWxml.indexOf('class="display-group-work-scroll"')
  const workListRule = readRule(editWxss, '.display-group-work-list')
  const workItemRule = readRule(editWxss, '.display-group-work-item')
  const workThumbRule = readRule(editWxss, '.display-group-work-thumb')
  const workCopyRule = readRule(editWxss, '.display-group-work-item-copy')
  const workScrollRule = readRule(editWxss, '.display-group-work-scroll')
  const tagOrderRule = readRule(editWxss, '.display-group-order')
  const workOrderRule = readRule(editWxss, '.display-group-work-order')

  assert.match(tagScrollRule, /padding-top:\s*12rpx/)
  assert.doesNotMatch(activePillRule, /translateY/)
  assert.match(editWxml, /wx:for="\{\{displayGroupOptions\}\}"[\s\S]*class="display-group-pill/)
  assert.match(editWxml, /class="display-group-count">\{\{item\.countText\}\}<\/view>/)
  assert.match(editWxml, /data-group-key="\{\{item\.groupKey\}\}"[\s\S]*catchtap="handleSelectDisplayGroup"/)
  assert.match(editWxml, /class="display-group-order \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*data-tag-id="\{\{item\.id\}\}"[\s\S]*catchtap="handleToggleDisplayGroupTag"/)
  assert.match(editWxml, /\{\{item\.selectionOrder \? item\.selectionOrder : ''\}\}/)
  assert.notEqual(workScrollIndex, -1)
  assert.match(editWxml, /<scroll-view[^>]*class="display-group-work-scroll"[^>]*scroll-y[^>]*type="list"/)
  assert.match(editWxml, /class="display-group-work-list"[\s\S]*wx:for="\{\{displayGroupWorkOptions\}\}"/)
  assert.match(editWxml, /class="display-group-work-item \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*catchtap="handleToggleDisplayGroupWork"/)
  assert.match(editWxml, /class="display-group-work-thumb"[\s\S]*src="\{\{item\.thumbUrl\}\}"/)
  assert.match(editWxml, /class="display-group-work-item-title">/)
  assert.match(editWxml, /class="display-group-work-order \{\{item\.selected \? 'selected' : ''\}\}"/)
  assert.match(editWxml, /class="component-work-actions"[\s\S]*class="component-work-cancel"[\s\S]*handleCancelDisplayGroupSheet[\s\S]*>取消<[\s\S]*class="component-work-confirm"[\s\S]*handleConfirmDisplayGroupSheet[\s\S]*>完成</)
  assert.doesNotMatch(editWxml, />关闭</)
  assert.doesNotMatch(editWxml, /displayGroupWorkPreviewOptions/)
  assert.doesNotMatch(editWxml, /work-tag-import-section/)
  assert.match(workScrollRule, /max-height:\s*360rpx/)
  assert.match(workListRule, /flex-direction:\s*column/)
  assert.match(workItemRule, /display:\s*flex/)
  assert.match(workItemRule, /flex-direction:\s*row/)
  assert.match(workItemRule, /min-height:\s*96rpx/)
  assert.match(workThumbRule, /flex:\s*none/)
  assert.match(workCopyRule, /display:\s*flex/)
  assert.match(workCopyRule, /flex:\s*1 1 0/)
  assert.match(workCopyRule, /flex-direction:\s*column/)
  assert.match(tagOrderRule, /border-radius:\s*50%/)
  assert.match(workOrderRule, /border-radius:\s*50%/)
})

test('standard personal portfolio editor keeps add button compact and delete hidden behind swipe', () => {
  const editWxss = read('pages/portfolio-standard-edit/portfolio-standard-edit.wxss')

  assert.match(editWxss, /\.link-button\s*\{[\s\S]*width:\s*136rpx;[\s\S]*min-width:\s*136rpx;[\s\S]*max-width:\s*136rpx;[\s\S]*flex:\s*0 0 136rpx;[\s\S]*padding:\s*0;/)
  assert.match(editWxss, /\.component-remove-button\s*\{[\s\S]*width:\s*108rpx;[\s\S]*min-width:\s*108rpx;[\s\S]*height:\s*64rpx;/)
  assert.doesNotMatch(editWxss, /\.component-actions\s*\{/)
})
