const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function readProjectFile(filePath) {
  return fs.readFileSync(path.join(__dirname, '..', filePath), 'utf8')
}

function readJson(filePath) {
  return JSON.parse(readProjectFile(filePath))
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

test('app registers schedule pages and mine tab navigates to schedule page', () => {
  const appJson = readJson('app.json')
  const indexJs = readProjectFile('pages/index/index.js')

  assert.ok(appJson.pages.includes('pages/schedule/schedule'))
  assert.ok(appJson.pages.includes('pages/schedule-entry/schedule-entry'))
  assert.match(indexJs, /const SCHEDULE_PAGE_URL = '\/pages\/schedule\/schedule'/)
  assert.match(indexJs, /label === '档期'[\s\S]*wx\.redirectTo\(\{[\s\S]*url:\s*SCHEDULE_PAGE_URL/)
  assert.doesNotMatch(indexJs, /title:\s*`\$\{label\}页面接入中`[\s\S]*label === '档期'/)
})

test('schedule page contains definition and maintenance views wired to backend APIs', () => {
  const pageJson = readJson('pages/schedule/schedule.json')
  const pageJs = readProjectFile('pages/schedule/schedule.js')
  const pageWxml = readProjectFile('pages/schedule/schedule.wxml')
  const pageWxss = readProjectFile('pages/schedule/schedule.wxss')
  const segmentedRule = readRule(pageWxss, '.schedule-segmented')
  const calendarToolbarRule = readRule(pageWxss, '.calendar-toolbar')
  const monthControlRule = readRule(pageWxss, '.month-control')
  const monthTitleRule = readRule(pageWxss, '.month-title')
  const monthMainRule = readRule(pageWxss, '.month-main')
  const monthSubRule = readRule(pageWxss, '.month-sub')
  const scheduleAddButtonRule = readRule(pageWxss, '.schedule-add-button')
  const definitionAddButtonRule = readRule(pageWxss, '.definition-add-button')
  const slotControlRowRule = readRule(pageWxss, '.slot-control-row')
  const statusFormRowRule = readRule(pageWxss, '.status-form-row')
  const fieldHeadingRule = readRule(pageWxss, '.field-heading')
  const fieldLimitRule = readRule(pageWxss, '.field-limit')
  const statusChoiceRule = readRule(pageWxss, '.slot-status-choice')
  const statusChoiceActiveRule = readRule(pageWxss, '.slot-status-choice.active')
  const statusChoiceTealRule = readRule(pageWxss, '.slot-status-choice.teal')
  const statusChoiceMutedRule = readRule(pageWxss, '.slot-status-choice.muted')
  const slotColorGridRule = readRule(pageWxss, '.slot-color-grid')
  const slotColorChoiceRule = readRule(pageWxss, '.slot-color-choice')
  const segmentedMarkup = pageWxml.match(/<view class="schedule-segmented">([\s\S]*?)<\/view>/)[1]
  const definitionListMarkup = pageWxml.match(/<view class="panel definition-list-panel">([\s\S]*?)<\/view>\s*<\/block>\s*<block wx:else>/)[1]
  const scheduleColorCardMarkup = pageWxml.match(/<view class="panel schedule-color-card">([\s\S]*?)<view class="calendar-group">/)[1]

  assert.equal(pageJson.usingComponents['navigation-bar'], '/components/navigation-bar/navigation-bar')
  assert.match(pageWxml, /navigation-bar title="档期" back="\{\{false\}\}"/)
  assert.match(pageWxml, /data-mode="definitions"[\s\S]*档位定义/)
  assert.match(pageWxml, /data-mode="maintenance"[\s\S]*档期维护/)
  assert.doesNotMatch(pageWxml, />排序</)
  assert.doesNotMatch(pageWxml, /sortOrder/)
  assert.match(pageWxml, /class="form-grid slot-control-row"[\s\S]*data-field="startTime"[\s\S]*data-field="endTime"[\s\S]*class="form-row status-form-row"[\s\S]*>启用状态</)
  assert.match(pageWxml, /class="field-heading"[\s\S]*档位名称[\s\S]*\{\{slotFieldCounters\.name\}\}/)
  assert.match(pageWxml, /class="slot-status-choice \{\{item\.tone\}\} \{\{slotForm\.status === item\.value \? 'active' : ''\}\}"/)
  assert.doesNotMatch(pageWxml, /class="choice \{\{slotForm\.status === item\.value \? 'active' : ''\}\}"/)
  assert.doesNotMatch(pageWxml, /<view class="field-label standalone">启用状态<\/view>/)
  assert.match(pageWxml, /class="slot-color-grid"/)
  assert.match(pageWxml, /class="slot-color-choice \{\{slotForm\.color === item\.color \? 'active' : ''\}\}"/)
  assert.match(pageWxml, /style="\{\{item\.choiceStyle\}\}"/)
  assert.match(pageWxml, /style="\{\{item\.swatchStyle\}\}"/)
  assert.match(pageWxml, /class="slot-color-name">\{\{item\.name\}\}<\/text>/)
  assert.doesNotMatch(pageWxml, /class="cost-note"/)
  assert.doesNotMatch(pageWxml, /保存后，未来/)
  assert.doesNotMatch(pageWxss, /\.cost-note\b/)
  assert.ok(
    segmentedMarkup.indexOf('data-mode="maintenance"') < segmentedMarkup.indexOf('data-mode="definitions"'),
    '档期维护应排在档位定义前面'
  )
  assert.match(pageWxml, /class="definition-sheet-overlay \{\{slotFormVisible \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(definitionListMarkup, /class="outline-button"[^>]*>新增定义<\/button>/)
  assert.match(pageWxml, /class="primary-button definition-add-button" bindtap="handleSlotAdd">新增定义<\/button>/)
  assert.doesNotMatch(scheduleColorCardMarkup, />管理<\/button>/)
  assert.doesNotMatch(pageWxml, />维护当天<\/button>/)
  assert.doesNotMatch(pageWxml, /点击维护当天/)
  assert.match(pageWxml, /class="primary-button schedule-add-button" bindtap="handleMaintainDate">新增档期<\/button>/)
  assert.match(pageWxml, /wx:for="\{\{overview\.month\.days\}\}"/)
  assert.match(pageJs, /normalizeScheduleOverview/)
  assert.match(pageJs, /buildSlotDefinitionPayload/)
  assert.match(pageJs, /buildSlotDefinitionFieldCounters/)
  assert.match(pageJs, /slotFieldCounters:\s*buildSlotDefinitionFieldCounters/)
  assert.match(pageJs, /slotStatusOptions:\s*\[[\s\S]*tone:\s*'teal'[\s\S]*tone:\s*'muted'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/slot-definitions'/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/slot-definitions\/\$\{this\.data\.editingSlotId\}`/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/slot-definitions\/\$\{slotId\}\/status`/)
  assert.doesNotMatch(pageJs, /method:\s*'DELETE'/)
  assert.match(segmentedRule, /display:\s*flex/)
  assert.doesNotMatch(segmentedRule, /display:\s*grid/)
  assert.match(calendarToolbarRule, /flex-wrap:\s*nowrap/)
  assert.match(monthControlRule, /flex:\s*0\s+0\s+72rpx/)
  assert.match(monthControlRule, /max-width:\s*72rpx/)
  assert.match(monthControlRule, /box-sizing:\s*border-box/)
  assert.match(monthTitleRule, /display:\s*flex/)
  assert.match(monthTitleRule, /flex-direction:\s*column/)
  assert.match(monthTitleRule, /align-items:\s*center/)
  assert.match(monthMainRule, /white-space:\s*nowrap/)
  assert.match(monthSubRule, /white-space:\s*nowrap/)
  assert.match(scheduleAddButtonRule, /width:\s*100%/)
  assert.match(scheduleAddButtonRule, /min-width:\s*100%/)
  assert.match(scheduleAddButtonRule, /max-width:\s*100%/)
  assert.match(scheduleAddButtonRule, /flex:\s*none/)
  assert.match(definitionAddButtonRule, /width:\s*100%/)
  assert.match(definitionAddButtonRule, /min-width:\s*100%/)
  assert.match(definitionAddButtonRule, /max-width:\s*100%/)
  assert.match(definitionAddButtonRule, /flex:\s*none/)
  assert.match(slotControlRowRule, /align-items:\s*flex-start/)
  assert.match(statusFormRowRule, /flex:\s*2\s+1\s+0/)
  assert.match(fieldHeadingRule, /display:\s*flex/)
  assert.match(fieldHeadingRule, /justify-content:\s*space-between/)
  assert.match(fieldLimitRule, /font-size:\s*22rpx/)
  assert.match(fieldLimitRule, /color:\s*#8b96a3/)
  assert.match(statusChoiceRule, /border:\s*2rpx solid/)
  assert.match(statusChoiceRule, /background:\s*#f5f8fb/)
  assert.match(statusChoiceActiveRule, /box-shadow:\s*inset 0 0 0 2rpx currentColor/)
  assert.doesNotMatch(statusChoiceActiveRule, /background:\s*#17202a/)
  assert.doesNotMatch(statusChoiceActiveRule, /color:\s*#ffffff/)
  assert.match(statusChoiceTealRule, /color:\s*#0f766e/)
  assert.match(statusChoiceMutedRule, /color:\s*#66727f/)
  assert.match(slotColorGridRule, /flex-wrap:\s*wrap/)
  assert.match(slotColorChoiceRule, /width:\s*calc\(\(100%\s*-\s*36rpx\)\s*\/\s*4\)/)
})

test('schedule entry page saves and deletes schedule items with POST endpoints', () => {
  const pageJson = readJson('pages/schedule-entry/schedule-entry.json')
  const pageJs = readProjectFile('pages/schedule-entry/schedule-entry.js')
  const pageWxml = readProjectFile('pages/schedule-entry/schedule-entry.wxml')
  const pageWxss = readProjectFile('pages/schedule-entry/schedule-entry.wxss')
  const slotGridRule = readRule(pageWxss, '.slot-grid')

  assert.equal(pageJson.usingComponents['navigation-bar'], '/components/navigation-bar/navigation-bar')
  assert.match(pageWxml, /navigation-bar title="维护档期" back="\{\{true\}\}"/)
  assert.match(pageWxml, /选择档位定义/)
  assert.match(pageWxml, /档位状态/)
  assert.match(pageWxml, /联系人姓名/)
  assert.match(pageWxml, /联系电话/)
  assert.match(pageWxml, /档期备注/)
  assert.match(pageWxml, /bindtap="handleSave"/)
  assert.match(pageWxml, /bindtap="handleDelete"/)
  assert.match(pageJs, /buildScheduleItemPayload/)
  assert.match(pageJs, /validateScheduleItemForm/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/items\/save'/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/items\/\$\{scheduleId\}\/delete`/)
  assert.match(pageJs, /method:\s*'POST'/)
  assert.doesNotMatch(pageJs, /method:\s*'DELETE'/)
  assert.match(slotGridRule, /display:\s*flex/)
  assert.doesNotMatch(slotGridRule, /display:\s*grid/)
})
