const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const { getRegisteredPageRoutes } = require('./helpers/app-pages')

function readProjectFile(filePath) {
  return fs.readFileSync(path.join(__dirname, '..', filePath), 'utf8')
}

function readJson(filePath) {
  return JSON.parse(readProjectFile(filePath))
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

test('app registers active schedule page and mine tab navigates to it', () => {
  const appJson = readJson('app.json')
  const registeredPageRoutes = getRegisteredPageRoutes(appJson)
  const indexJs = readProjectFile('pages/index/index.js')

  assert.ok(registeredPageRoutes.includes('pages/schedule/schedule'))
  assert.equal(registeredPageRoutes.includes('pages/schedule-entry/schedule-entry'), false)
  assert.match(indexJs, /const SCHEDULE_PAGE_URL = '\/pages\/schedule\/schedule'/)
  assert.match(indexJs, /label === '档期'[\s\S]*wx\.redirectTo\(\{[\s\S]*url:\s*SCHEDULE_PAGE_URL/)
  assert.doesNotMatch(indexJs, /title:\s*`\$\{label\}页面接入中`[\s\S]*label === '档期'/)
})

test('schedule page contains definition and maintenance views wired to backend APIs', () => {
  const pageJson = readJson('pages/schedule/schedule.json')
  const pageJs = readProjectFile('pages/schedule/schedule.js')
  const pageWxml = readProjectFile('pages/schedule/schedule.wxml')
  const pageWxss = readProjectFile('pages/schedule/schedule.wxss')
  const segmentedRule = readRule(pageWxss, '.schedule-segmented')
  const calendarToolbarRule = readRule(pageWxss, '.calendar-toolbar')
  const monthControlRule = readRule(pageWxss, '.month-control')
  const monthControlWideRule = readRule(pageWxss, '.month-control.wide')
  const monthPickerRule = readRule(pageWxss, '.month-picker')
  const monthTitleRule = readRule(pageWxss, '.month-title')
  const monthMainRule = readRule(pageWxss, '.month-main')
  const calendarRule = readRule(pageWxss, '.calendar')
  const weekdayRule = readRule(pageWxss, '.weekday')
  const calendarDayRule = readRule(pageWxss, '.calendar-day')
  const selectedCalendarDayRule = readRule(pageWxss, '.calendar-day.selected')
  const selectedDateStackRule = readRule(pageWxss, '.calendar-day.selected .date-stack')
  const dateStackRule = readRule(pageWxss, '.date-stack')
  const dayNumberRule = readRule(pageWxss, '.day-number')
  const dayMetaRule = readRule(pageWxss, '.day-meta')
  const dayColorsRule = readRule(pageWxss, '.day-colors')
  const dayColorRule = readRule(pageWxss, '.day-color')
  const dayHeadingRule = readRule(pageWxss, '.day-heading')
  const dayDateCopyRule = readRule(pageWxss, '.day-date-copy')
  const dayTitleRule = readRule(pageWxss, '.day-title')
  const dayLunarTitleRule = readRule(pageWxss, '.day-lunar-title')
  const daySummaryRule = readRule(pageWxss, '.day-summary')
  const scheduleAddButtonRule = readRule(pageWxss, '.schedule-add-button')
  const definitionAddButtonRule = readRule(pageWxss, '.definition-add-button')
  const slotSwipeRowRule = readRule(pageWxss, '.slot-swipe-row')
  const slotSwipeRevealedRule = readRule(pageWxss, '.slot-swipe-row.revealed .slot-line')
  const slotDeletePaneRule = readRule(pageWxss, '.slot-delete-pane')
  const scheduleSwipeRowRule = readRule(pageWxss, '.schedule-swipe-row')
  const scheduleSwipeRevealedRule = readRule(pageWxss, '.schedule-swipe-row.revealed .schedule-line')
  const scheduleDeletePaneRule = readRule(pageWxss, '.schedule-delete-pane')
  const slotActionsRule = readRule(pageWxss, '.slot-actions')
  const miniActionRule = readRule(pageWxss, '.mini-action')
  const slotToggleActionRule = readRule(pageWxss, '.slot-toggle-action')
  const miniActionDangerRule = readRule(pageWxss, '.mini-action.danger')
  const sheetOverlayRule = readRule(pageWxss, '.schedule-sheet-overlay')
  const sheetRule = readRule(pageWxss, '.schedule-sheet')
  const scheduleSlotGridRule = readRule(pageWxss, '.schedule-slot-grid')
  const scheduleSlotCardRule = readRule(pageWxss, '.schedule-slot-card')
  const scheduleStatusRowRule = readRule(pageWxss, '.schedule-status-row')
  const scheduleStatusRule = readRule(pageWxss, '.schedule-status')
  const scheduleStatusDotRule = readRule(pageWxss, '.schedule-status::before')
  const scheduleStatusTealRule = readRule(pageWxss, '.schedule-status.teal')
  const scheduleStatusAmberRule = readRule(pageWxss, '.schedule-status.amber')
  const scheduleStatusRoseRule = readRule(pageWxss, '.schedule-status.rose')
  const scheduleStatusMutedRule = readRule(pageWxss, '.schedule-status.muted')
  const slotControlRowRule = readRule(pageWxss, '.slot-control-row')
  const slotControlPickerRule = readRule(pageWxss, '.slot-control-row > picker')
  const statusFormRowRule = readRule(pageWxss, '.status-form-row')
  const slotStatusRule = readRule(pageWxss, '.slot-status')
  const slotStatusActiveRule = readRule(pageWxss, '.slot-status.active')
  const slotStatusMutedRule = readRule(pageWxss, '.slot-status.muted')
  const fieldHeadingRule = readRule(pageWxss, '.field-heading')
  const fieldLimitRule = readRule(pageWxss, '.field-limit')
  const statusChoiceRule = readRule(pageWxss, '.slot-status-choice')
  const statusChoiceActiveRule = readRule(pageWxss, '.slot-status-choice.active')
  const statusChoiceTealRule = readRule(pageWxss, '.slot-status-choice.teal')
  const statusChoiceMutedRule = readRule(pageWxss, '.slot-status-choice.muted')
  const fieldInputRule = readRule(pageWxss, '.field-input')
  const primaryButtonRule = readRule(pageWxss, '.primary-button')
  const slotColorGridRule = readRule(pageWxss, '.slot-color-grid')
  const slotColorChoiceRule = readRule(pageWxss, '.slot-color-choice')
  const slotColorChoiceActiveRule = readRule(pageWxss, '.slot-color-choice.active')
  const slotColorChoiceDisabledRule = readRule(pageWxss, '.slot-color-choice.disabled')
  const segmentedMarkup = pageWxml.match(/<view class="schedule-segmented">([\s\S]*?)<\/view>\s*<block wx:if=/)[1]
  const definitionListMarkup = pageWxml.match(/<view class="panel definition-list-panel">([\s\S]*?)<\/view>\s*<\/block>\s*<block wx:else>/)[1]
  const scheduleColorCardMarkup = pageWxml.match(/<view class="panel schedule-color-card">([\s\S]*?)<view class="calendar-group">/)[1]
  const dayPanelHeaderMarkup = pageWxml.match(/<view class="day-panel">\s*([\s\S]*?)\s*<view wx:if="\{\{overview\.selectedDate\.empty\}\}"/)[1]

  assert.equal(pageJson.usingComponents['navigation-bar'], '/components/navigation-bar/navigation-bar')
  assert.match(pageWxml, /navigation-bar title="档期" back="\{\{false\}\}"/)
  assert.doesNotMatch(pageWxml, /<block wx:if="\{\{loading\}\}">/)
  assert.match(pageWxml, /slotDefinitionsLoading/)
  assert.match(pageWxml, /calendarLoading/)
  assert.match(pageWxml, /dayLoading/)
  assert.match(pageWxml, /data-mode="definitions"[\s\S]*档位定义/)
  assert.match(pageWxml, /data-mode="maintenance"[\s\S]*档期维护/)
  assert.doesNotMatch(pageWxml, />排序</)
  assert.doesNotMatch(pageWxml, /sortOrder/)
  assert.match(pageWxml, /class="form-grid slot-control-row"[\s\S]*data-field="startTime"[\s\S]*data-field="endTime"[\s\S]*class="form-row status-form-row"[\s\S]*>启用状态</)
  assert.match(pageWxml, /class="field-heading"[\s\S]*档位名称[\s\S]*\{\{slotFieldCounters\.name\}\}/)
  assert.match(pageWxml, /class="slot-status-choice \{\{item\.tone\}\} \{\{slotForm\.status === item\.value \? 'active' : ''\}\}"/)
  assert.doesNotMatch(pageWxml, /class="choice \{\{slotForm\.status === item\.value \? 'active' : ''\}\}"/)
  assert.doesNotMatch(pageWxml, /<view class="field-label standalone">启用状态<\/view>/)
  assert.match(pageWxml, /class="slot-color-grid"/)
  assert.match(pageWxml, /class="slot-color-choice \{\{item\.disabled \? 'disabled' : ''\}\} \{\{slotForm\.color === item\.color \? 'active' : ''\}\}"/)
  assert.doesNotMatch(pageWxml, /style="\{\{item\.choiceStyle\}\}"/)
  assert.match(pageWxml, /style="\{\{item\.swatchStyle\}\}"/)
  assert.match(pageWxml, /class="slot-color-name">\{\{item\.name\}\}<\/text>/)
  assert.doesNotMatch(pageWxml, /class="cost-note"/)
  assert.doesNotMatch(pageWxml, /保存后，未来/)
  assert.doesNotMatch(pageWxss, /\.cost-note\b/)
  assert.ok(
    segmentedMarkup.indexOf('data-mode="maintenance"') < segmentedMarkup.indexOf('data-mode="definitions"'),
    '档期维护应排在档位定义前面'
  )
  assert.match(pageWxml, /class="definition-sheet-overlay \{\{slotFormVisible \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(definitionListMarkup, /class="outline-button"[^>]*>新增定义<\/button>/)
  assert.match(pageWxml, /class="slot-swipe-row \{\{revealedSlotId === item\.id && !item\.enabled \? 'revealed' : ''\}\}"/)
  assert.match(pageWxml, /bindtouchstart="handleSlotTouchStart"[\s\S]*bindtouchmove="handleSlotTouchMove"[\s\S]*bindtouchend="handleSlotTouchEnd"/)
  assert.match(pageWxml, /class="slot-delete-pane"[\s\S]*wx:if="\{\{!item\.enabled\}\}"[\s\S]*catchtap="handleDeleteSlotDefinition"[\s\S]*>删除<\/button>/)
  assert.match(pageWxml, /class="slot-actions"[\s\S]*handleToggleSlotStatus/)
  assert.match(pageWxml, /class="mini-action \{\{item\.enabled \? 'warn' : ''\}\} slot-toggle-action"/)
  assert.match(pageWxml, /loading="\{\{togglingSlotId === item\.id\}\}"/)
  assert.match(pageWxml, /disabled="\{\{togglingSlotId !== null\}\}"/)
  assert.doesNotMatch(pageWxml, /<view class="slot-actions">[\s\S]*?handleDeleteSlotDefinition/)
  assert.match(pageWxml, /class="primary-button definition-add-button" bindtap="handleSlotAdd">新增定义<\/button>/)
  assert.doesNotMatch(scheduleColorCardMarkup, />管理<\/button>/)
  assert.doesNotMatch(pageWxml, />维护当天<\/button>/)
  assert.doesNotMatch(pageWxml, /点击维护当天/)
  assert.doesNotMatch(pageWxml, /当前查看月份/)
  assert.match(pageWxml, /<picker class="month-picker" mode="date" fields="month" value="\{\{selectedMonth\}\}" bindchange="handleMonthPickerChange">/)
  assert.match(pageWxml, /class="month-control wide"[\s\S]*切换年月/)
  assert.match(pageWxml, /class="date-stack"[\s\S]*class="day-number">\{\{item\.dayNumber\}\}<\/view>/)
  assert.match(pageWxml, /class="day-meta" wx:if="\{\{item\.metaText\}\}">\{\{item\.metaText\}\}<\/view>/)
  assert.match(pageJs, /handleMonthPickerChange\(event\)[\s\S]*const selectedDate = formatMonthFirstDate\(selectedMonth\)[\s\S]*selectedDate,/)
  assert.match(pageWxml, /class="primary-button schedule-add-button" bindtap="handleMaintainDate">新增档期<\/button>/)
  assert.match(dayPanelHeaderMarkup, /class="day-heading"[\s\S]*class="day-date-copy"[\s\S]*class="day-title">\{\{overview\.selectedDate\.titleText\}\}<\/view>[\s\S]*class="day-lunar-title">\{\{overview\.selectedDate\.lunarTitleText\}\}<\/view>[\s\S]*class="day-summary">\{\{overview\.selectedDate\.summaryText\}\}<\/view>/)
  assert.doesNotMatch(dayPanelHeaderMarkup, /class="panel-meta">\{\{overview\.selectedDate\.summaryText\}\}<\/view>/)
  assert.match(pageWxml, /class="schedule-swipe-row \{\{revealedScheduleId === item\.id \? 'revealed' : ''\}\}"/)
  assert.match(pageWxml, /bindtouchstart="handleScheduleTouchStart"[\s\S]*bindtouchmove="handleScheduleTouchMove"[\s\S]*bindtouchend="handleScheduleTouchEnd"/)
  assert.match(pageWxml, /class="schedule-delete-pane"[\s\S]*catchtap="handleDeleteScheduleItem"[\s\S]*>删除<\/button>/)
  assert.match(pageWxml, /class="schedule-sheet-overlay \{\{scheduleFormVisible \? 'visible' : ''\}\}"/)
  assert.match(pageWxml, /class="schedule-sheet"[\s\S]*\{\{scheduleSheetTitle\}\}/)
  assert.match(pageWxml, /选择档位定义[\s\S]*class="schedule-slot-grid"/)
  assert.match(pageWxml, /档期状态[\s\S]*class="schedule-status-row"/)
  assert.doesNotMatch(pageWxml, />档位状态</)
  assert.match(pageWxml, /data-field="contactName"[\s\S]*data-field="contactPhone"[\s\S]*data-field="note"/)
  assert.match(pageWxml, /loading="\{\{saving\}\}" bindtap="handleSaveSchedule">保存档期<\/button>/)
  assert.doesNotMatch(pageWxml, /class="schedule-sheet"[\s\S]*handleDeleteScheduleItem/)
  assert.match(pageWxml, /wx:for="\{\{overview\.month\.days\}\}"/)
  assert.match(pageJs, /normalizeScheduleOverview/)
  assert.match(pageJs, /buildSlotDefinitionPayload/)
  assert.match(pageJs, /buildSlotDefinitionFieldCounters/)
  assert.match(pageJs, /SCHEDULE_STATUS_OPTIONS/)
  assert.match(pageJs, /buildScheduleItemPayload/)
  assert.match(pageJs, /buildScheduleFieldCounters/)
  assert.match(pageJs, /validateScheduleItemPayload/)
  assert.match(pageJs, /validateSlotDefinitionPayload/)
  assert.doesNotMatch(pageJs, /validateScheduleItemForm\(this\.data\.scheduleForm\)/)
  assert.doesNotMatch(pageJs, /validateSlotDefinitionForm\(this\.data\.slotForm\)/)
  assert.match(pageJs, /const \{ normalizeId \} = require\('\.\.\/\.\.\/utils\/id'\)/)
  assert.match(pageJs, /slotFieldCounters:\s*buildSlotDefinitionFieldCounters/)
  assert.match(pageJs, /scheduleFieldCounters:\s*buildScheduleFieldCounters/)
  assert.match(pageJs, /togglingSlotId:\s*null/)
  assert.match(pageJs, /handleSlotEdit\(event\)[\s\S]*if\s*\(slot\.enabled\)[\s\S]*title:\s*'停用后才可编辑'[\s\S]*return[\s\S]*slotFormVisible:\s*true/)
  assert.match(pageJs, /handleSlotAdd\(\)[\s\S]*buildSlotColorOptions\(this\.data\.overview\.slotDefinitions\)/)
  assert.match(pageJs, /title:\s*'档位颜色已全部使用'/)
  assert.match(pageJs, /handleSlotEdit\(event\)[\s\S]*buildSlotColorOptions\(this\.data\.overview\.slotDefinitions,\s*slot\.id\)/)
  assert.match(pageJs, /handleSlotColorTap\(event\)[\s\S]*dataset\.disabled[\s\S]*return/)
  assert.match(pageWxml, /item\.disabled \? 'disabled' : ''/)
  assert.match(pageWxml, /data-disabled="\{\{item\.disabled\}\}"/)
  assert.match(pageWxml, /aria-disabled="\{\{item\.disabled\}\}"/)
  assert.match(pageJs, /title:\s*'无法删除'/)
  assert.match(pageJs, /handleMaintainDate\(\)[\s\S]*scheduleFormVisible:\s*true/)
  assert.match(pageJs, /handleScheduleTap\(event\)[\s\S]*scheduleFormVisible:\s*true/)
  assert.doesNotMatch(pageJs, /\/pages\/schedule-entry\/schedule-entry/)
  assert.match(pageJs, /slotStatusOptions:\s*\[[\s\S]*tone:\s*'teal'[\s\S]*tone:\s*'muted'/)
  assert.match(pageJs, /statusOptions:\s*SCHEDULE_STATUS_OPTIONS/)
  assert.doesNotMatch(pageJs, /url:\s*'\/api\/mine\/schedule'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/slot-definitions'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/month'/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/day'/)
  assert.match(pageJs, /handleDayTap\(event\)[\s\S]*this\.loadDaySchedules\(false\)/)
  assert.doesNotMatch(pageJs, /handleDayTap\(event\)[\s\S]*this\.loadSchedule/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/slot-definitions'/)
  assert.match(pageJs, /const editingSlotId = this\.data\.editingSlotId[\s\S]*`\/api\/mine\/schedule\/slot-definitions\/save\/\$\{editingSlotId\}`/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/slot-definitions\/status\/\$\{slotId\}`/)
  assert.match(pageJs, /url:\s*'\/api\/mine\/schedule\/items\/save'/)
  assert.match(pageJs, /handleDeleteSlotDefinition/)
  assert.match(pageJs, /handleDeleteScheduleItem/)
  assert.match(pageJs, /content:\s*`确认删除 \$\{schedule\.scheduleDate \|\| this\.data\.selectedDate\} 的“\$\{schedule\.slotName\}”？`/)
  assert.doesNotMatch(pageJs, /删除后访客端不会再看到这条档期记录/)
  assert.match(pageJs, /revealedSlotId:\s*null/)
  assert.match(pageJs, /revealedScheduleId:\s*null/)
  assert.match(pageJs, /handleSlotTouchStart/)
  assert.match(pageJs, /handleScheduleTouchStart/)
  assert.match(pageJs, /handleTouchEnd\(event,\s*touchStateKey,\s*revealedKey,\s*idKey\)/)
  assert.match(pageJs, /handleSlotTouchEnd\(event\)[\s\S]*this\.handleTouchEnd\(event,\s*'slotTouchStart',\s*'revealedSlotId',\s*'slotId'\)/)
  assert.match(pageJs, /handleScheduleTouchEnd\(event\)[\s\S]*this\.handleTouchEnd\(event,\s*'scheduleTouchStart',\s*'revealedScheduleId',\s*'scheduleId'\)/)
  assert.match(pageJs, /handleSaveSchedule\(\)[\s\S]*const payload = buildScheduleItemPayload\(this\.data\.scheduleForm\)[\s\S]*validateScheduleItemPayload\(payload\)[\s\S]*data:\s*payload/)
  assert.match(pageJs, /handleSaveSlot\(\)[\s\S]*const payload = buildSlotDefinitionPayload\(this\.data\.slotForm\)[\s\S]*validateSlotDefinitionPayload\(payload\)[\s\S]*data:\s*payload/)
  assert.match(pageJs, /handleSaveSlot\(\)[\s\S]*catch \(error\)[\s\S]*if \(error && error\.authRequired\) \{[\s\S]*this\.setData\(\{ saving: false \}\)[\s\S]*handleMaintainerAuthRequired\(error\.message\)/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/slot-definitions\/delete\/\$\{slotId\}`/)
  assert.match(pageJs, /`\/api\/mine\/schedule\/items\/delete\/\$\{scheduleId\}`/)
  assert.match(pageJs, /method:\s*'POST'/)
  assert.doesNotMatch(pageJs, /method:\s*'DELETE'/)
  assert.match(segmentedRule, /display:\s*flex/)
  assert.doesNotMatch(segmentedRule, /display:\s*grid/)
  assert.match(calendarToolbarRule, /flex-wrap:\s*nowrap/)
  assert.match(calendarToolbarRule, /display:\s*flex/)
  assert.doesNotMatch(calendarToolbarRule, /display:\s*grid/)
  assert.doesNotMatch(calendarToolbarRule, /grid-template-columns/)
  assert.match(monthControlRule, /flex:\s*0\s+0\s+64rpx/)
  assert.match(monthControlRule, /max-width:\s*64rpx/)
  assert.match(monthControlRule, /border-radius:\s*50%/)
  assert.match(monthControlRule, /box-sizing:\s*border-box/)
  assert.match(monthControlWideRule, /width:\s*132rpx/)
  assert.match(monthControlWideRule, /border-radius:\s*999rpx/)
  assert.match(monthPickerRule, /flex:\s*none/)
  assert.match(monthPickerRule, /margin-right:\s*12rpx/)
  assert.match(monthTitleRule, /display:\s*flex/)
  assert.match(monthTitleRule, /align-items:\s*center/)
  assert.match(monthMainRule, /white-space:\s*nowrap/)
  assert.match(calendarRule, /gap:\s*8rpx\s+0/)
  assert.match(calendarRule, /justify-content:\s*space-between/)
  assert.match(calendarRule, /padding:\s*0\s+28rpx\s+28rpx/)
  assert.doesNotMatch(calendarRule, /gap:\s*8rpx\s+6rpx/)
  assert.match(weekdayRule, /min-height:\s*40rpx/)
  assert.match(weekdayRule, /margin-bottom:\s*12rpx/)
  assert.match(weekdayRule, /color:\s*#adb5bd/)
  assert.match(weekdayRule, /font-size:\s*22rpx/)
  assert.match(weekdayRule, /font-weight:\s*600/)
  assert.match(weekdayRule, /flex:\s*0\s+0\s+calc\(\(100%\s*-\s*36rpx\)\s*\/\s*7\)/)
  assert.match(calendarDayRule, /width:\s*calc\(\(100%\s*-\s*36rpx\)\s*\/\s*7\)/)
  assert.match(calendarDayRule, /flex:\s*0\s+0\s+calc\(\(100%\s*-\s*36rpx\)\s*\/\s*7\)/)
  assert.match(calendarDayRule, /min-height:\s*88rpx/)
  assert.match(calendarDayRule, /padding:\s*8rpx\s+4rpx/)
  assert.match(calendarDayRule, /border:\s*0/)
  assert.match(calendarDayRule, /border-radius:\s*28rpx/)
  assert.match(calendarDayRule, /background:\s*#ffffff/)
  assert.match(calendarDayRule, /overflow:\s*visible/)
  assert.match(selectedCalendarDayRule, /background:\s*#ffffff/)
  assert.doesNotMatch(selectedCalendarDayRule, /border-color:/)
  assert.match(dateStackRule, /width:\s*54rpx/)
  assert.match(dateStackRule, /height:\s*54rpx/)
  assert.match(dateStackRule, /flex:\s*none/)
  assert.match(dateStackRule, /gap:\s*2rpx/)
  assert.doesNotMatch(selectedDateStackRule, /\bwidth\s*:/)
  assert.doesNotMatch(selectedDateStackRule, /\bheight\s*:/)
  assert.match(selectedDateStackRule, /border-radius:\s*50%/)
  assert.match(selectedDateStackRule, /background:\s*#212529/)
  assert.match(selectedDateStackRule, /box-shadow:\s*0\s+0\s+0\s+9rpx\s+#212529/)
  assert.match(dayNumberRule, /font-size:\s*30rpx/)
  assert.match(dayNumberRule, /font-weight:\s*600/)
  assert.match(dayMetaRule, /color:\s*#adb5bd/)
  assert.match(dayMetaRule, /font-size:\s*20rpx/)
  assert.match(dayMetaRule, /font-weight:\s*500/)
  assert.match(dayMetaRule, /text-overflow:\s*ellipsis/)
  assert.match(dayColorsRule, /min-height:\s*10rpx/)
  assert.match(dayColorsRule, /margin-top:\s*6rpx/)
  assert.match(dayColorRule, /width:\s*10rpx/)
  assert.match(dayColorRule, /height:\s*10rpx/)
  assert.match(dayHeadingRule, /display:\s*flex/)
  assert.match(dayHeadingRule, /justify-content:\s*space-between/)
  assert.match(dayHeadingRule, /align-items:\s*center/)
  assert.match(dayHeadingRule, /padding:\s*12rpx\s+0\s+18rpx/)
  assert.match(dayDateCopyRule, /display:\s*flex/)
  assert.match(dayDateCopyRule, /align-items:\s*baseline/)
  assert.match(dayDateCopyRule, /gap:\s*18rpx/)
  assert.match(dayTitleRule, /font-size:\s*36rpx/)
  assert.match(dayLunarTitleRule, /font-size:\s*26rpx/)
  assert.match(dayLunarTitleRule, /white-space:\s*nowrap/)
  assert.match(daySummaryRule, /white-space:\s*nowrap/)
  assert.match(daySummaryRule, /text-align:\s*right/)
  assert.match(scheduleAddButtonRule, /width:\s*100%/)
  assert.match(scheduleAddButtonRule, /min-width:\s*100%/)
  assert.match(scheduleAddButtonRule, /max-width:\s*100%/)
  assert.match(scheduleAddButtonRule, /flex:\s*none/)
  assert.match(definitionAddButtonRule, /width:\s*100%/)
  assert.match(definitionAddButtonRule, /min-width:\s*100%/)
  assert.match(definitionAddButtonRule, /max-width:\s*100%/)
  assert.match(definitionAddButtonRule, /flex:\s*none/)
  assert.match(slotSwipeRowRule, /position:\s*relative/)
  assert.match(slotSwipeRowRule, /overflow:\s*hidden/)
  assert.match(slotSwipeRevealedRule, /transform:\s*translateX\(-140rpx\)/)
  assert.match(slotDeletePaneRule, /position:\s*absolute/)
  assert.match(slotDeletePaneRule, /right:\s*0/)
  assert.match(slotDeletePaneRule, /width:\s*128rpx/)
  assert.match(scheduleSwipeRowRule, /position:\s*relative/)
  assert.match(scheduleSwipeRowRule, /overflow:\s*hidden/)
  assert.match(scheduleSwipeRevealedRule, /transform:\s*translateX\(-140rpx\)/)
  assert.match(scheduleDeletePaneRule, /position:\s*absolute/)
  assert.match(scheduleDeletePaneRule, /right:\s*0/)
  assert.match(scheduleDeletePaneRule, /width:\s*128rpx/)
  assert.match(slotActionsRule, /display:\s*flex/)
  assert.match(slotActionsRule, /justify-content:\s*flex-end/)
  assert.match(slotActionsRule, /gap:\s*12rpx/)
  assert.match(miniActionRule, /width:\s*128rpx/)
  assert.match(miniActionRule, /min-width:\s*128rpx/)
  assert.match(miniActionRule, /max-width:\s*128rpx/)
  assert.match(miniActionRule, /box-sizing:\s*border-box/)
  assert.match(slotToggleActionRule, /width:\s*112rpx/)
  assert.match(slotToggleActionRule, /min-width:\s*112rpx/)
  assert.match(slotToggleActionRule, /max-width:\s*112rpx/)
  assert.match(slotToggleActionRule, /height:\s*56rpx/)
  assert.match(slotToggleActionRule, /color:\s*#212529/)
  assert.match(slotToggleActionRule, /font-size:\s*22rpx/)
  assert.match(slotToggleActionRule, /font-weight:\s*600/)
  assert.match(slotToggleActionRule, /border:\s*0/)
  assert.match(slotToggleActionRule, /border-radius:\s*999rpx/)
  assert.match(slotToggleActionRule, /background:\s*#f5f6f7/)
  assert.match(miniActionDangerRule, /color:\s*#a9354f/)
  assert.match(slotControlRowRule, /align-items:\s*flex-start/)
  assert.match(slotControlPickerRule, /flex:\s*1\s+1\s+0/)
  assert.match(slotControlPickerRule, /min-width:\s*0/)
  assert.match(statusFormRowRule, /flex:\s*2\s+1\s+0/)
  assert.match(slotStatusRule, /padding:\s*12rpx\s+24rpx/)
  assert.match(slotStatusRule, /border:\s*2rpx solid transparent/)
  assert.match(slotStatusActiveRule, /color:\s*#529463/)
  assert.match(slotStatusActiveRule, /border-color:\s*#cde2d4/)
  assert.match(slotStatusActiveRule, /background:\s*#ffffff/)
  assert.match(slotStatusMutedRule, /color:\s*#868e96/)
  assert.match(slotStatusMutedRule, /border-color:\s*#d9dee2/)
  assert.match(slotStatusMutedRule, /background:\s*#ffffff/)
  assert.match(fieldHeadingRule, /display:\s*flex/)
  assert.match(fieldHeadingRule, /justify-content:\s*space-between/)
  assert.match(fieldLimitRule, /font-size:\s*22rpx/)
  assert.match(fieldLimitRule, /color:\s*#adb5bd/)
  assert.match(statusChoiceRule, /background:\s*#f5f6f7/)
  assert.match(statusChoiceActiveRule, /color:\s*#ffffff/)
  assert.match(statusChoiceActiveRule, /background:\s*#212529/)
  assert.doesNotMatch(statusChoiceActiveRule, /box-shadow:\s*inset/)
  assert.match(statusChoiceTealRule, /color:\s*#868e96/)
  assert.match(statusChoiceMutedRule, /color:\s*#868e96/)
  assert.match(slotColorGridRule, /flex-wrap:\s*wrap/)
  assert.match(slotColorGridRule, /gap:\s*12rpx\s+0/)
  assert.match(slotColorGridRule, /justify-content:\s*space-between/)
  assert.match(slotColorChoiceRule, /width:\s*calc\(\(100%\s*-\s*36rpx\)\s*\/\s*4\)/)
  assert.match(slotColorChoiceRule, /flex:\s*0\s+0\s+calc\(\(100%\s*-\s*36rpx\)\s*\/\s*4\)/)
  assert.match(slotColorChoiceRule, /min-width:\s*0/)
  assert.match(slotColorChoiceRule, /color:\s*#40464d/)
  assert.match(slotColorChoiceRule, /border:\s*4rpx solid transparent/)
  assert.match(slotColorChoiceRule, /background:\s*#f3f5f6/)
  assert.match(slotColorChoiceActiveRule, /color:\s*#1e2125/)
  assert.match(slotColorChoiceActiveRule, /border-color:\s*#1e2125/)
  assert.match(slotColorChoiceDisabledRule, /opacity:/)
  assert.match(slotColorChoiceActiveRule, /background:\s*#ffffff/)
  assert.doesNotMatch(slotColorChoiceActiveRule, /box-shadow:/)
  assert.match(sheetOverlayRule, /position:\s*fixed/)
  assert.match(sheetOverlayRule, /align-items:\s*flex-end/)
  assert.match(sheetRule, /transform:\s*translateY\(32rpx\)/)
  assert.match(sheetRule, /border-radius:\s*56rpx 56rpx 0 0/)
  assert.match(fieldInputRule, /min-height:\s*84rpx/)
  assert.match(primaryButtonRule, /height:\s*96rpx/)
  assert.match(scheduleSlotGridRule, /display:\s*flex/)
  assert.match(scheduleSlotGridRule, /flex-wrap:\s*wrap/)
  assert.match(scheduleSlotCardRule, /width:\s*calc\(50%\s*-\s*8rpx\)/)
  assert.match(scheduleStatusRule, /display:\s*inline-flex/)
  assert.match(scheduleStatusRule, /align-items:\s*center/)
  assert.match(scheduleStatusRule, /gap:\s*8rpx/)
  assert.match(scheduleStatusRule, /padding:\s*0/)
  assert.match(scheduleStatusRule, /background:\s*transparent/)
  assert.match(scheduleStatusDotRule, /width:\s*12rpx/)
  assert.match(scheduleStatusDotRule, /height:\s*12rpx/)
  assert.match(scheduleStatusDotRule, /background:\s*currentColor/)
  assert.match(scheduleStatusDotRule, /border-radius:\s*50%/)
  assert.match(scheduleStatusTealRule, /color:\s*#0f766e/)
  assert.match(scheduleStatusAmberRule, /color:\s*#8a4b09/)
  assert.match(scheduleStatusRoseRule, /color:\s*#a9354f/)
  assert.match(scheduleStatusMutedRule, /color:\s*#66727f/)
  assert.doesNotMatch(scheduleStatusTealRule, /background:/)
  assert.doesNotMatch(scheduleStatusAmberRule, /background:/)
  assert.doesNotMatch(scheduleStatusRoseRule, /background:/)
  assert.doesNotMatch(scheduleStatusMutedRule, /background:/)
  assert.match(scheduleStatusRowRule, /display:\s*flex/)
  assert.match(scheduleStatusRowRule, /flex-wrap:\s*wrap/)
})

test('schedule page keeps existing content while split reads are loading', () => {
  const pageJs = readProjectFile('pages/schedule/schedule.js')

  assert.match(pageJs, /slotDefinitionsLoading:\s*true/)
  assert.match(pageJs, /calendarLoading:\s*true/)
  assert.match(pageJs, /dayLoading:\s*true/)
  assert.doesNotMatch(
    pageJs,
    /'overview\.month':\s*normalizeMonthOverview\(\{\s*yearMonth:\s*selectedMonth\s*\},\s*selectedDate\s*\)/
  )
  assert.doesNotMatch(
    pageJs,
    /'overview\.month':\s*sameMonth\s*\?[\s\S]*?:\s*normalizeMonthOverview\(\{\s*yearMonth:\s*selectedMonth\s*\},\s*date\s*\)/
  )
  assert.match(pageJs, /if \(sameMonth\) \{[\s\S]*this\.loadDaySchedules\(false\)/)
  assert.doesNotMatch(pageJs, /handleRetry\(\)/)
})
