const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJson = fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8')
const indexJs = fs.readFileSync(path.join(__dirname, '../pages/index/index.js'), 'utf8')
const visitsJsPath = path.join(__dirname, '../pages/visits/visits.js')
const visitsJsonPath = path.join(__dirname, '../pages/visits/visits.json')
const visitsWxmlPath = path.join(__dirname, '../pages/visits/visits.wxml')
const visitsWxssPath = path.join(__dirname, '../pages/visits/visits.wxss')

function readVisitsRule(selector) {
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = visitsWxss.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

test('mine visit entry navigates to visit records page', () => {
  assert.match(appJson, /"pages\/visits\/visits"/)
  assert.match(indexJs, /if\s*\(\s*type\s*===\s*'visits'\s*\)/)
  assert.match(indexJs, /url:\s*'\/pages\/visits\/visits'/)
})

test('visit records page files match prototype structure and backend endpoint', () => {
  assert.equal(fs.existsSync(visitsJsPath), true)
  assert.equal(fs.existsSync(visitsJsonPath), true)
  assert.equal(fs.existsSync(visitsWxmlPath), true)
  assert.equal(fs.existsSync(visitsWxssPath), true)

  const visitsJs = fs.readFileSync(visitsJsPath, 'utf8')
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')

  assert.match(visitsJs, /const MINE_VISITS_URL = '\/api\/mine\/visits'/)
  assert.match(visitsJs, /url:\s*MINE_VISITS_URL/)
  assert.match(visitsJs, /normalizeVisitRecords/)
  assert.match(visitsWxml, /navigation-bar title="访问记录" back="\{\{true\}\}"/)
  assert.match(visitsWxml, /class="metric-grid"/)
  assert.match(visitsWxml, /近 7 日访问趋势/)
  assert.match(visitsWxml, /访问明细/)
  assert.match(visitsWxml, /bindtap="handleVisitRowTap"/)
  assert.match(visitsWxml, /visit-event-sheet-mask/)
  assert.match(visitsWxml, /selectedVisitRecord\.events/)
  assert.match(visitsWxml, /bindscrolltolower="handleVisitEventScrollToLower"/)
  assert.match(visitsWxml, /lower-threshold="120"/)
  assert.match(visitsWxml, /eventSheetLoadingMore/)
  assert.match(visitsWxml, /bindtap="handleCloseEventSheet"/)
  assert.match(visitsWxml, /class="\{\{item\.followToneClass\}\}"/)
  assert.match(visitsWxml, /<canvas[^>]*wx:if="\{\{!eventSheetVisible\}\}"[^>]*id="trendLineCanvas"[^>]*class="trend-line-canvas"[^>]*type="2d"/)
  assert.match(visitsJs, /drawTrendLineChart/)
  assert.match(visitsJs, /this\.data\.eventSheetVisible/)
  assert.match(visitsJs, /handleVisitRowTap/)
  assert.match(visitsJs, /handleVisitEventScrollToLower/)
  assert.match(visitsJs, /pageNo/)
  assert.match(visitsJs, /pageSize/)
  assert.match(visitsJs, /handleCloseEventSheet/)
  assert.match(visitsJs, /selectedVisitRecord/)
  assert.match(visitsJs, /\$\{MINE_VISITS_URL\}\/\$\{recordId\}\/events/)
  assert.match(visitsJs, /createSelectorQuery\(\)\.in\(this\)/)
  assert.match(visitsJs, /ctx\.lineTo/)
  assert.match(visitsJs, /ctx\.arc/)
  assert.match(visitsJs, /ctx\.fillText\(String\(point\.value\)/)
  assert.match(visitsWxss, /\.visit-list/)
  assert.match(visitsWxss, /\.visit-event-sheet-mask/)
  assert.match(visitsWxss, /\.visit-event-sheet-panel/)
  assert.match(visitsWxss, /\.visit-event-item/)
  assert.match(visitsWxss, /\.visit-event-load-more/)
  assert.match(visitsWxss, /\.trend-line-canvas/)
  assert.doesNotMatch(visitsWxss, /\.trend-bars/)
})

test('visit records detail rows keep avatar, copy and follow status in one scan row', () => {
  const visitRowRule = readVisitsRule('.visit-row')
  const visitorIconRule = readVisitsRule('.visitor-icon')
  const visitCopyRule = readVisitsRule('.visit-copy')

  assert.match(visitRowRule, /display:\s*flex/)
  assert.match(visitRowRule, /align-items:\s*center/)
  assert.doesNotMatch(visitRowRule, /display:\s*grid/)
  assert.doesNotMatch(visitRowRule, /grid-template-columns/)
  assert.match(visitorIconRule, /flex:\s*none/)
  assert.match(visitorIconRule, /border-radius:\s*50%/)
  assert.match(visitCopyRule, /flex:\s*1/)
  assert.match(visitCopyRule, /min-width:\s*0/)
})

test('visit records expose mark-followed action behind left swipe for unfollowed rows', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')

  assert.match(visitsWxml, /class="visit-swipe-row \{\{revealedVisitRecordId === item\.id && item\.canMarkFollowed \? 'revealed' : ''\}\}"/)
  assert.match(visitsWxml, /bindtouchstart="handleVisitTouchStart"[\s\S]*bindtouchmove="handleVisitTouchMove"[\s\S]*bindtouchend="handleVisitTouchEnd"[\s\S]*bindtouchcancel="handleVisitTouchCancel"/)
  assert.match(visitsWxml, /wx:if="\{\{item\.canMarkFollowed\}\}"[\s\S]*class="visit-follow-pane"/)
  assert.match(visitsWxml, /class="visit-follow-button"[\s\S]*catchtap="handleMarkVisitFollowedTap"[\s\S]*>标记已跟进<\/button>/)
  assert.match(visitsWxss, /\.visit-swipe-row\s*\{[\s\S]*position:\s*relative;[\s\S]*overflow:\s*hidden;/)
  assert.match(visitsWxss, /\.visit-swipe-row\.revealed \.visit-row\s*\{[\s\S]*transform:\s*translateX\(-168rpx\);/)
  assert.match(visitsWxss, /\.visit-swipe-row\.revealed \.visit-follow-pane\s*\{[\s\S]*transform:\s*translateX\(0\);[\s\S]*opacity:\s*1;[\s\S]*pointer-events:\s*auto;/)
})

test('visit records summary and trend labels avoid CSS grid on Skyline', () => {
  const metricGridRule = readVisitsRule('.metric-grid')
  const metricRule = readVisitsRule('.metric')
  const trendLabelRowRule = readVisitsRule('.trend-label-row')
  const trendLabelRule = readVisitsRule('.trend-label')

  assert.match(metricGridRule, /display:\s*flex/)
  assert.match(metricGridRule, /gap:\s*16rpx/)
  assert.doesNotMatch(metricGridRule, /display:\s*grid/)
  assert.match(metricRule, /flex:\s*1\s+1\s+0/)
  assert.match(metricRule, /min-width:\s*0/)
  assert.match(trendLabelRowRule, /display:\s*flex/)
  assert.match(trendLabelRowRule, /gap:\s*8rpx/)
  assert.doesNotMatch(trendLabelRowRule, /display:\s*grid/)
  assert.match(trendLabelRule, /flex:\s*1\s+1\s+0/)
  assert.match(trendLabelRule, /min-width:\s*0/)
})

test('visit event sheet keeps a tall mobile bottom sheet with an internal scroller', () => {
  const sheetPanelRule = readVisitsRule('.visit-event-sheet-panel')
  const eventListRule = readVisitsRule('.visit-event-list')

  assert.match(sheetPanelRule, /height:\s*8[0-9]vh/)
  assert.match(sheetPanelRule, /max-height:\s*calc\(100vh - 56rpx\)/)
  assert.match(eventListRule, /flex:\s*1/)
  assert.match(eventListRule, /min-height:\s*0/)
  assert.doesNotMatch(eventListRule, /max-height:\s*560rpx/)
})
