const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJson = fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8')
const indexJs = fs.readFileSync(path.join(__dirname, '../pages/index/index.js'), 'utf8')
const visitsJsPath = path.join(__dirname, '../pages/visits/visits.js')
const visitsJsonPath = path.join(__dirname, '../pages/visits/visits.json')
const visitsWxmlPath = path.join(__dirname, '../pages/visits/visits.wxml')
const visitsWxssPath = path.join(__dirname, '../pages/visits/visits.wxss')
const copyIconPath = path.join(__dirname, '../assets/system/copy-line.svg')

function readVisitsRule(selector) {
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = visitsWxss.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

test('mine visit entry navigates to visit records page', () => {
  assert.match(appJson, /"pages\/visits\/visits"/)
  assert.match(indexJs, /if\s*\(\s*type\s*===\s*'visits'\s*\)/)
  assert.match(indexJs, /url:\s*'\/pages\/visits\/visits'/)
})

test('visit records page files match prototype structure and backend endpoint', () => {
  assert.equal(fs.existsSync(visitsJsPath), true)
  assert.equal(fs.existsSync(visitsJsonPath), true)
  assert.equal(fs.existsSync(visitsWxmlPath), true)
  assert.equal(fs.existsSync(visitsWxssPath), true)
  assert.equal(fs.existsSync(copyIconPath), true)

  const visitsJs = fs.readFileSync(visitsJsPath, 'utf8')
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')

  assert.match(visitsJs, /const MINE_VISITS_URL = '\/api\/mine\/visits'/)
  assert.match(visitsJs, /const MINE_VISIT_STATISTICS_URL = '\/api\/mine\/visits\/statistics'/)
  assert.match(visitsJs, /const MINE_VISIT_RECORDS_URL = '\/api\/mine\/visits\/records'/)
  assert.match(visitsJs, /url:\s*MINE_VISIT_STATISTICS_URL/)
  assert.match(visitsJs, /url:\s*MINE_VISIT_RECORDS_URL/)
  assert.match(visitsJs, /normalizeVisitRecords/)
  assert.match(visitsWxml, /navigation-bar title="访问记录" back="\{\{true\}\}"/)
  assert.match(visitsWxml, /class="metric-grid"/)
  assert.match(visitsWxml, /data-action="\{\{item\.action\}\}"/)
  assert.match(visitsWxml, /bindtap="handleMetricTap"/)
  assert.match(visitsWxml, /近 7 日访问趋势/)
  assert.match(visitsWxml, /访问明细/)
  assert.match(visitsWxml, /class="visits-scroll"[\s\S]*bindscrolltolower="handleVisitRecordScrollToLower"/)
  assert.match(visitsWxml, /class="visits-scroll"[\s\S]*lower-threshold="160"/)
  assert.match(visitsWxml, /class="visit-list"[\s\S]*wx:if="\{\{visitRecordLoadingMore\}\}"[\s\S]*更多访问记录加载中/)
  assert.match(visitsWxml, /bindtap="handleVisitRowTap"/)
  assert.match(visitsWxml, /visit-event-sheet-mask/)
  assert.match(visitsWxml, /selectedVisitRecord\.events/)
  assert.match(visitsWxml, /bindscrolltolower="handleVisitEventScrollToLower"/)
  assert.match(visitsWxml, /lower-threshold="120"/)
  assert.match(visitsWxml, /eventSheetLoadingMore/)
  assert.match(visitsWxml, /bindtap="handleCloseEventSheet"/)
  assert.match(visitsWxml, /visit-detail-sheet-mask/)
  assert.match(visitsWxml, /bindscrolltolower="handleVisitDetailScrollToLower"/)
  assert.match(visitsWxml, /detailSheetLoadingMore/)
  assert.match(visitsWxml, /bindtap="handleCloseDetailSheet"/)
  assert.match(visitsWxml, /class="contact-lead-status"[\s\S]*class="\{\{item\.followToneClass\}\}">[\s\S]*\{\{item\.followStatusText\}\}/)
  assert.match(visitsWxml, /手机[\s\S]*class="contact-value-copy"[\s\S]*\{\{item\.phoneText\}\}[\s\S]*class="contact-copy-icon-button"[\s\S]*data-copy-text="\{\{item\.phoneCopyText\}\}"[\s\S]*handleCopyContactValueTap[\s\S]*src="\/assets\/system\/copy-line\.svg"/)
  assert.match(visitsWxml, /微信[\s\S]*class="contact-value-copy"[\s\S]*\{\{item\.wechatText\}\}[\s\S]*class="contact-copy-icon-button"[\s\S]*data-copy-text="\{\{item\.wechatCopyText\}\}"[\s\S]*handleCopyContactValueTap[\s\S]*src="\/assets\/system\/copy-line\.svg"/)
  assert.match(visitsWxml, /档期[\s\S]*\{\{item\.desiredScheduleText\}\}/)
  assert.match(visitsWxml, /来源作品集[\s\S]*\{\{item\.portfolioTitle\}\}[\s\S]*\{\{item\.portfolioTypeText\}\}/)
  assert.match(visitsWxml, /class="contact-lead-layout"[\s\S]*class="contact-lead-status"[\s\S]*class="\{\{item\.followToneClass\}\}"[\s\S]*class="contact-lead-main"[\s\S]*class="contact-lead-title-row"[\s\S]*wx:if="\{\{item\.canMarkFollowed\}\}"[\s\S]*class="contact-lead-action-column"[\s\S]*class="contact-lead-follow-button"/)
  assert.doesNotMatch(visitsWxml, /class="contact-lead-main"[\s\S]*class="contact-lead-status"/)
  assert.doesNotMatch(visitsWxml, /class="contact-lead-action-column"[\s\S]*class="contact-lead-status"/)
  assert.doesNotMatch(visitsWxml, /visit-detail-item-row contact-lead-head-row/)
  assert.doesNotMatch(visitsWxml, /class="visit-detail-meta-row"[\s\S]*class="contact-lead-follow-button"/)
  assert.doesNotMatch(visitsWxml, /class="contact-copy-button"/)
  assert.doesNotMatch(visitsWxml, />复制<\/button>/)
  assert.doesNotMatch(visitsWxml, /wx:else class="\{\{item\.followToneClass\}\}"/)
  assert.match(visitsWxml, /handleMarkContactLeadFollowedTap/)
  assert.match(visitsWxml, /handleCopyContactValueTap/)
  assert.match(visitsWxml, /class="\{\{item\.followToneClass\}\}"/)
  assert.match(visitsWxml, /<image[^>]*class="trend-line-image"[^>]*src="\{\{visitData\.trend\.chartSvg\}\}"[^>]*mode="scaleToFill"/)
  assert.doesNotMatch(visitsWxml, /<canvas/)
  assert.doesNotMatch(visitsWxml, /trendLineCanvas/)
  assert.doesNotMatch(visitsJs, /drawTrendLineChart/)
  assert.doesNotMatch(visitsJs, /createSelectorQuery\(\)\.in\(this\)/)
  assert.doesNotMatch(visitsJs, /ctx\.lineTo/)
  assert.doesNotMatch(visitsJs, /ctx\.arc/)
  assert.doesNotMatch(visitsJs, /ctx\.fillText/)
  assert.match(visitsJs, /handleVisitRowTap/)
  assert.match(visitsJs, /handleVisitRecordScrollToLower/)
  assert.match(visitsJs, /handleVisitEventScrollToLower/)
  assert.match(visitsJs, /handleMetricTap/)
  assert.match(visitsJs, /handleVisitDetailScrollToLower/)
  assert.match(visitsJs, /handleMarkContactLeadFollowedTap/)
  assert.match(visitsJs, /handleCopyContactValueTap/)
  assert.match(visitsJs, /pageNo/)
  assert.match(visitsJs, /pageSize/)
  assert.match(visitsJs, /handleCloseEventSheet/)
  assert.match(visitsJs, /handleCloseDetailSheet/)
  assert.match(visitsJs, /selectedVisitRecord/)
  assert.match(visitsJs, /\$\{MINE_VISITS_URL\}\/\$\{recordId\}\/events/)
  assert.match(visitsJs, /\/schedule-queries/)
  assert.match(visitsJs, /\/contact-leads/)
  assert.match(visitsWxss, /\.visit-list/)
  assert.match(visitsWxss, /\.visit-event-sheet-mask/)
  assert.match(visitsWxss, /\.visit-event-sheet-panel/)
  assert.match(visitsWxss, /\.visit-event-item/)
  assert.match(visitsWxss, /\.visit-event-load-more/)
  assert.match(visitsWxss, /\.visit-detail-sheet-panel/)
  assert.match(visitsWxss, /\.visit-detail-sheet-item/)
  assert.match(visitsWxss, /\.trend-line-image/)
  assert.doesNotMatch(visitsWxss, /\.trend-line-canvas/)
  assert.doesNotMatch(visitsWxss, /\.trend-bars/)
})

test('visit metrics share row containers and expose arrows only on interactive cells', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const metricGridRule = readVisitsRule('.metric-grid')
  const metricRowRule = readVisitsRule('.metric-row')
  const metricCellRule = readVisitsRule('.metric-cell')
  const metricDividerRule = readVisitsRule('.metric-divider')
  const metricArrowRule = readVisitsRule('.metric-arrow')

  assert.match(visitsWxml, /class="metric-row"[\s\S]*wx:for="\{\{visitData\.metricRows\}\}"/)
  assert.match(visitsWxml, /class="metric-divider"[\s\S]*wx:if="\{\{index > 0\}\}"/)
  assert.match(visitsWxml, /wx:if="\{\{item\.interactive\}\}" class="metric-arrow"/)
  assert.match(metricGridRule, /flex-direction:\s*column/)
  assert.match(metricRowRule, /display:\s*flex/)
  assert.match(metricRowRule, /border-radius:\s*40rpx/)
  assert.match(metricRowRule, /overflow:\s*hidden/)
  assert.match(metricCellRule, /position:\s*relative/)
  assert.match(metricDividerRule, /width:\s*1rpx/)
  assert.match(metricDividerRule, /background:\s*#e9ecef/)
  assert.match(metricArrowRule, /border-top:\s*4rpx solid #ced4da/)
  assert.match(metricArrowRule, /border-right:\s*4rpx solid #ced4da/)
  assert.match(metricArrowRule, /transform:\s*translateY\(-50%\) rotate\(45deg\)/)
})

test('visit records detail rows keep avatar, copy and follow status in one scan row', () => {
  const visitRowRule = readVisitsRule('.visit-row')
  const visitorIconRule = readVisitsRule('.visitor-icon')
  const visitCopyRule = readVisitsRule('.visit-copy')

  assert.match(visitRowRule, /display:\s*flex/)
  assert.match(visitRowRule, /align-items:\s*center/)
  assert.doesNotMatch(visitRowRule, /display:\s*grid/)
  assert.doesNotMatch(visitRowRule, /grid-template-columns/)
  assert.match(visitorIconRule, /flex:\s*none/)
  assert.match(visitorIconRule, /border-radius:\s*50%/)
  assert.match(visitCopyRule, /flex:\s*1/)
  assert.match(visitCopyRule, /min-width:\s*0/)
})

test('visit records expose mark-followed action behind left swipe for unfollowed rows', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitsWxss = fs.readFileSync(visitsWxssPath, 'utf8')

  assert.match(visitsWxml, /class="visit-swipe-row \{\{revealedVisitRecordId === item\.id && item\.canMarkFollowed \? 'revealed' : ''\}\}"/)
  assert.match(visitsWxml, /bindtouchstart="handleVisitTouchStart"[\s\S]*bindtouchmove="handleVisitTouchMove"[\s\S]*bindtouchend="handleVisitTouchEnd"[\s\S]*bindtouchcancel="handleVisitTouchCancel"/)
  assert.match(visitsWxml, /wx:if="\{\{item\.canMarkFollowed\}\}"[\s\S]*class="visit-follow-pane"/)
  assert.match(visitsWxml, /class="visit-follow-button"[\s\S]*catchtap="handleMarkVisitFollowedTap"[\s\S]*class="visit-follow-button-label"[\s\S]*<text>标记<\/text>[\s\S]*<text>已跟进<\/text>[\s\S]*<\/button>/)
  assert.match(visitsWxss, /\.visit-swipe-row\s*\{[\s\S]*position:\s*relative;[\s\S]*overflow:\s*hidden;/)
  assert.match(visitsWxss, /\.visit-swipe-row\.revealed \.visit-row\s*\{[\s\S]*transform:\s*translateX\(-168rpx\);/)
  assert.match(visitsWxss, /\.visit-swipe-row\.revealed \.visit-follow-pane\s*\{[\s\S]*transform:\s*translateX\(0\);[\s\S]*opacity:\s*1;[\s\S]*pointer-events:\s*auto;/)
})

test('visit record follow states use a color dot and the swipe action stays on two lines', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitRowFollowRule = readVisitsRule('.visit-row .follow-pill')
  const statusDotRule = readVisitsRule('.visit-follow-status-dot')
  const roseDotRule = readVisitsRule('.follow-pill.rose .visit-follow-status-dot')
  const tealDotRule = readVisitsRule('.follow-pill.teal .visit-follow-status-dot')
  const blueDotRule = readVisitsRule('.follow-pill.blue .visit-follow-status-dot')
  const actionLabelRule = readVisitsRule('.visit-follow-button-label')

  assert.match(visitsWxml, /class="visit-follow-button-label"[\s\S]*<text>标记<\/text>[\s\S]*<text>已跟进<\/text>/)
  assert.match(visitsWxml, /class="\{\{item\.followToneClass\}\}"[\s\S]*class="visit-follow-status-dot"[\s\S]*\{\{item\.followStatusText\}\}/)
  assert.match(visitRowFollowRule, /display:\s*flex/)
  assert.match(visitRowFollowRule, /gap:\s*8rpx/)
  assert.match(visitRowFollowRule, /padding:\s*0/)
  assert.match(visitRowFollowRule, /background:\s*transparent/)
  assert.match(statusDotRule, /width:\s*12rpx/)
  assert.match(statusDotRule, /height:\s*12rpx/)
  assert.match(statusDotRule, /border-radius:\s*50%/)
  assert.match(roseDotRule, /background:\s*#b55656/)
  assert.match(tealDotRule, /background:\s*#5c9e6e/)
  assert.match(blueDotRule, /background:\s*#212529/)
  assert.match(actionLabelRule, /display:\s*flex/)
  assert.match(actionLabelRule, /flex-direction:\s*column/)
})

test('visit records summary and trend labels avoid CSS grid on Skyline', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const metricGridRule = readVisitsRule('.metric-grid')
  const metricCellRule = readVisitsRule('.metric-cell')
  const metricRule = readVisitsRule('.metric')
  const trendLabelRowRule = readVisitsRule('.trend-label-row')
  const trendLabelRule = readVisitsRule('.trend-label')

  assert.match(visitsWxml, /class="metric-cell \{\{item\.interactive \? 'interactive' : ''\}\}"/)
  assert.match(metricGridRule, /display:\s*flex/)
  assert.match(metricGridRule, /flex-direction:\s*column/)
  assert.match(metricGridRule, /gap:\s*16rpx/)
  assert.doesNotMatch(metricGridRule, /display:\s*grid/)
  assert.match(metricCellRule, /flex:\s*1\s+1\s+0/)
  assert.match(metricCellRule, /(?:^|\n)\s*width:\s*50%/)
  assert.match(metricCellRule, /min-width:\s*0/)
  assert.match(metricCellRule, /box-sizing:\s*border-box/)
  assert.doesNotMatch(metricCellRule, /calc/)
  assert.match(metricRule, /(?:^|\n)\s*width:\s*100%/)
  assert.match(metricRule, /min-width:\s*0/)
  assert.match(trendLabelRowRule, /display:\s*flex/)
  assert.match(trendLabelRowRule, /gap:\s*8rpx/)
  assert.doesNotMatch(trendLabelRowRule, /display:\s*grid/)
  assert.match(trendLabelRule, /flex:\s*1\s+1\s+0/)
  assert.match(trendLabelRule, /min-width:\s*0/)
})

test('visit records main list stays in the page scroller on mobile Skyline', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const visitsScrollRule = readVisitsRule('.visits-scroll')
  const visitsContentRule = readVisitsRule('.visits-content')
  const visitListRule = readVisitsRule('.visit-list')

  assert.match(visitsWxml, /class="visits-scroll"[\s\S]*class="visit-list"/)
  assert.match(visitsScrollRule, /flex:\s*1/)
  assert.match(visitsScrollRule, /min-height:\s*0/)
  assert.match(visitsContentRule, /padding:\s*20rpx 32rpx calc\(56rpx \+ env\(safe-area-inset-bottom\)\)/)
  assert.doesNotMatch(visitListRule, /max-height:/)
  assert.doesNotMatch(visitListRule, /overflow-y:/)
})

test('visit trend line image spans the same content width as the date labels', () => {
  const trendChartRule = readVisitsRule('.trend-chart')
  const trendLineImageRule = readVisitsRule('.trend-line-image')
  const trendLabelRowRule = readVisitsRule('.trend-label-row')
  const trendLabelRule = readVisitsRule('.trend-label')

  assert.match(trendChartRule, /width:\s*100%/)
  assert.match(trendLineImageRule, /width:\s*646rpx/)
  assert.match(trendLineImageRule, /max-width:\s*100%/)
  assert.match(trendLineImageRule, /height:\s*156rpx/)
  assert.match(trendLabelRowRule, /display:\s*flex/)
  assert.match(trendLabelRule, /flex:\s*1\s+1\s+0/)
})

test('visit event sheet keeps a tall mobile bottom sheet with an internal scroller', () => {
  const sheetPanelRule = readVisitsRule('.visit-event-sheet-panel')
  const eventListRule = readVisitsRule('.visit-event-list')

  assert.match(sheetPanelRule, /height:\s*8[0-9]vh/)
  assert.match(sheetPanelRule, /max-height:\s*calc\(100vh - 56rpx\)/)
  assert.match(sheetPanelRule, /border-radius:\s*56rpx 56rpx 0 0/)
  assert.match(eventListRule, /flex:\s*1/)
  assert.match(eventListRule, /min-height:\s*0/)
  assert.doesNotMatch(eventListRule, /max-height:\s*560rpx/)
})

test('visit metric detail sheet keeps a tall mobile bottom sheet with an internal scroller', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const sheetPanelRule = readVisitsRule('.visit-detail-sheet-panel')
  const detailListRule = readVisitsRule('.visit-detail-sheet-list')
  const contactMethodRowRule = readVisitsRule('.contact-method-row')
  const contactMethodCopyRule = readVisitsRule('.contact-method-copy')
  const contactValueCopyRule = readVisitsRule('.contact-value-copy')
  const contactCopyIconButtonRule = readVisitsRule('.contact-copy-icon-button')
  const contactCopyIconRule = readVisitsRule('.contact-copy-icon')
  const contactLeadLayoutRule = readVisitsRule('.contact-lead-layout')
  const contactLeadMainRule = readVisitsRule('.contact-lead-main')
  const contactLeadTitleRowRule = readVisitsRule('.contact-lead-title-row')
  const contactLeadActionColumnRule = readVisitsRule('.contact-lead-action-column')
  const contactLeadStatusRule = readVisitsRule('.contact-lead-status')
  const contactLeadStatusPillRule = readVisitsRule('.contact-lead-status .follow-pill')
  const contactLeadStatusDotRule = readVisitsRule('.contact-lead-status-dot')
  const contactLeadButtonRule = readVisitsRule('.contact-lead-follow-button')
  const portfolioTypeTagRule = readVisitsRule('.portfolio-type-tag')

  assert.match(sheetPanelRule, /height:\s*8[0-9]vh/)
  assert.match(sheetPanelRule, /max-height:\s*calc\(100vh - 56rpx\)/)
  assert.match(sheetPanelRule, /border-radius:\s*56rpx 56rpx 0 0/)
  assert.match(detailListRule, /flex:\s*1/)
  assert.match(detailListRule, /min-height:\s*0/)
  assert.match(contactMethodRowRule, /display:\s*flex/)
  assert.match(contactMethodRowRule, /align-items:\s*center/)
  assert.match(contactMethodCopyRule, /align-items:\s*center/)
  assert.match(contactMethodCopyRule, /gap:\s*10rpx/)
  assert.match(contactValueCopyRule, /flex:\s*none/)
  assert.match(contactValueCopyRule, /display:\s*inline-flex/)
  assert.match(contactValueCopyRule, /gap:\s*4rpx/)
  assert.match(contactCopyIconButtonRule, /width:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /min-width:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /max-width:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /height:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /min-height:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /max-height:\s*38rpx/)
  assert.match(contactCopyIconButtonRule, /padding:\s*0/)
  assert.match(contactCopyIconButtonRule, /font-size:\s*0/)
  assert.match(contactCopyIconButtonRule, /background:\s*transparent/)
  assert.match(contactCopyIconRule, /width:\s*30rpx/)
  assert.match(contactCopyIconRule, /height:\s*30rpx/)
  assert.match(contactLeadLayoutRule, /display:\s*flex/)
  assert.match(contactLeadLayoutRule, /align-items:\s*stretch/)
  assert.match(contactLeadLayoutRule, /gap:\s*18rpx/)
  assert.match(contactLeadLayoutRule, /position:\s*relative/)
  assert.match(contactLeadLayoutRule, /padding-right:\s*190rpx/)
  assert.match(contactLeadMainRule, /flex:\s*1/)
  assert.match(contactLeadMainRule, /min-width:\s*0/)
  assert.match(contactLeadTitleRowRule, /display:\s*flex/)
  assert.match(contactLeadTitleRowRule, /align-items:\s*center/)
  assert.match(contactLeadTitleRowRule, /gap:\s*12rpx/)
  assert.match(contactLeadStatusRule, /position:\s*absolute/)
  assert.match(contactLeadStatusRule, /top:\s*0/)
  assert.match(contactLeadStatusRule, /right:\s*0/)
  assert.match(contactLeadStatusRule, /justify-content:\s*flex-end/)
  assert.match(contactLeadActionColumnRule, /position:\s*absolute/)
  assert.match(contactLeadActionColumnRule, /top:\s*0/)
  assert.match(contactLeadActionColumnRule, /right:\s*14rpx/)
  assert.match(contactLeadActionColumnRule, /bottom:\s*0/)
  assert.match(contactLeadActionColumnRule, /width:\s*176rpx/)
  assert.match(contactLeadActionColumnRule, /flex-direction:\s*column/)
  assert.match(contactLeadActionColumnRule, /align-items:\s*flex-end/)
  assert.match(contactLeadActionColumnRule, /justify-content:\s*center/)
  assert.match(contactLeadActionColumnRule, /gap:\s*8rpx/)
  assert.match(visitsWxml, /class="contact-lead-status"[\s\S]*class="\{\{item\.followToneClass\}\}"[\s\S]*class="contact-lead-status-dot"[\s\S]*\{\{item\.followStatusText\}\}/)
  assert.match(contactLeadStatusPillRule, /gap:\s*8rpx/)
  assert.match(contactLeadStatusPillRule, /padding:\s*0/)
  assert.match(contactLeadStatusPillRule, /font-size:\s*25rpx/)
  assert.match(contactLeadStatusPillRule, /display:\s*flex/)
  assert.match(contactLeadStatusPillRule, /background:\s*transparent/)
  assert.match(contactLeadStatusDotRule, /width:\s*12rpx/)
  assert.match(contactLeadStatusDotRule, /height:\s*12rpx/)
  assert.match(contactLeadStatusDotRule, /border-radius:\s*50%/)
  assert.match(contactLeadStatusDotRule, /background:\s*currentColor/)
  assert.match(contactLeadButtonRule, /width:\s*176rpx/)
  assert.match(contactLeadButtonRule, /min-width:\s*176rpx/)
  assert.match(contactLeadButtonRule, /max-width:\s*176rpx/)
  assert.match(contactLeadButtonRule, /min-height:\s*54rpx/)
  assert.match(contactLeadButtonRule, /max-height:\s*54rpx/)
  assert.match(contactLeadButtonRule, /display:\s*flex/)
  assert.match(contactLeadButtonRule, /font-size:\s*24rpx/)
  assert.match(contactLeadButtonRule, /border:\s*1rpx solid rgba\(92,\s*158,\s*110,\s*0\.28\)/)
  assert.match(contactLeadButtonRule, /background:\s*#ffffff/)
  assert.match(contactLeadButtonRule, /border-radius:\s*999rpx/)
  assert.match(portfolioTypeTagRule, /color:\s*#868e96/)
  assert.match(portfolioTypeTagRule, /border:\s*1rpx solid #dee2e6/)
  assert.match(portfolioTypeTagRule, /background:\s*#ffffff/)
})

test('visit records use approved semantic status tones', () => {
  const detailStatusTealRule = readVisitsRule('.detail-status.teal')
  const detailStatusRoseRule = readVisitsRule('.detail-status.rose')
  const followTealRule = readVisitsRule('.follow-pill.teal')
  const followRoseRule = readVisitsRule('.follow-pill.rose')
  const followBlueRule = readVisitsRule('.follow-pill.blue')
  const visitorRoseRule = readVisitsRule('.visitor-icon.rose')
  const visitorTealRule = readVisitsRule('.visitor-icon.teal')
  const visitorBlueRule = readVisitsRule('.visitor-icon.blue')

  assert.match(detailStatusTealRule, /color:\s*#5c9e6e/)
  assert.match(detailStatusRoseRule, /color:\s*#b55656/)
  assert.match(followTealRule, /color:\s*#5c9e6e/)
  assert.match(followRoseRule, /color:\s*#b55656/)
  assert.match(followBlueRule, /color:\s*#212529/)
  ;[visitorRoseRule, visitorTealRule, visitorBlueRule].forEach((rule) => {
    assert.match(rule, /color:\s*#6c757d/)
    assert.match(rule, /background:\s*#e9ecef/)
  })
})

test('schedule query detail status uses a color dot and text without a pill', () => {
  const visitsWxml = fs.readFileSync(visitsWxmlPath, 'utf8')
  const detailStatusRule = readVisitsRule('.detail-status')
  const detailStatusDotRule = readVisitsRule('.detail-status-dot')

  assert.match(visitsWxml, /class="\{\{item\.resultToneClass\}\}"[\s\S]*class="detail-status-dot"[\s\S]*\{\{item\.resultStatusText\}\}/)
  assert.match(detailStatusRule, /display:\s*flex/)
  assert.match(detailStatusRule, /align-items:\s*center/)
  assert.match(detailStatusRule, /gap:\s*8rpx/)
  assert.match(detailStatusRule, /padding:\s*0/)
  assert.match(detailStatusRule, /border:\s*0/)
  assert.match(detailStatusRule, /background:\s*transparent/)
  assert.match(detailStatusDotRule, /width:\s*12rpx/)
  assert.match(detailStatusDotRule, /height:\s*12rpx/)
  assert.match(detailStatusDotRule, /border-radius:\s*50%/)
  assert.match(detailStatusDotRule, /background:\s*currentColor/)
})
