const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const { getRegisteredPageRoutes } = require('./helpers/app-pages')

const appJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8'))
const registeredPageRoutes = getRegisteredPageRoutes(appJson)

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

function readBetween(content, startPattern, endPattern) {
  const start = content.search(startPattern)
  assert.notEqual(start, -1)
  const rest = content.slice(start)
  const end = rest.search(endPattern)
  assert.notEqual(end, -1)
  return rest.slice(0, end)
}

function assertSoftLayerAnimation(wxss, overlaySelector, panelSelector) {
  const overlayRule = readRule(wxss, overlaySelector)
  const visibleOverlayRule = readRule(wxss, `${overlaySelector}.visible`)
  const panelRule = readRule(wxss, panelSelector)
  const visiblePanelRule = readRule(wxss, `${overlaySelector}.visible ${panelSelector}`)

  assert.match(overlayRule, /opacity:\s*0/)
  assert.match(overlayRule, /pointer-events:\s*none/)
  assert.match(overlayRule, /transition:[^;]*opacity\s+\d+ms/)
  assert.match(visibleOverlayRule, /opacity:\s*1/)
  assert.match(visibleOverlayRule, /pointer-events:\s*auto/)
  assert.match(panelRule, /transform:/)
  assert.match(panelRule, /transition:[^;]*transform\s+\d+ms/)
  assert.match(visiblePanelRule, /transform:/)
  assert.doesNotMatch(panelRule, /translateY\(32rpx\)/)
  assert.doesNotMatch(panelRule, /transition:\s*transform 180ms ease/)
}

test('app registers works pages in the mini program', () => {
  assert.ok(registeredPageRoutes.includes('pages/works/works'))
  assert.ok(registeredPageRoutes.includes('pages/works/work-add/work-add'))
  assert.ok(registeredPageRoutes.includes('pages/works/work-edit/work-edit'))
})

test('mine and schedule bottom tabs navigate to works page', () => {
  const indexJs = read('pages/index/index.js')
  const scheduleJs = read('pages/schedule/schedule.js')

  assert.match(indexJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
  assert.match(scheduleJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
})

test('work library uses the same adaptive viewport contract in formal and mock pages', () => {
  const styleFiles = [
    'pages/works/works.wxss',
    'pages/mock/styles/works.wxss'
  ]

  styleFiles.forEach((styleFile) => {
    const wxss = read(styleFile)
    const worksScrollRule = readRule(wxss, '.works-scroll')
    const worksContentRule = readRule(wxss, '.works-content')
    const libraryPanelRule = readRule(wxss, '.library-panel')
    const workListScrollRule = readRule(wxss, '.work-list-scroll')

    assert.match(worksScrollRule, /flex:\s*1/)
    assert.match(worksScrollRule, /height:\s*0/)
    assert.match(worksScrollRule, /min-height:\s*0/)
    assert.match(worksContentRule, /height:\s*100%/)
    assert.match(worksContentRule, /display:\s*flex/)
    assert.match(worksContentRule, /flex-direction:\s*column/)
    assert.match(
      worksContentRule,
      /padding:\s*20rpx 32rpx calc\(172rpx \+ env\(safe-area-inset-bottom\)\)/
    )
    assert.match(libraryPanelRule, /flex:\s*1 1 auto/)
    assert.match(libraryPanelRule, /min-height:\s*0/)
    assert.match(workListScrollRule, /flex:\s*1 1 auto/)
    assert.match(workListScrollRule, /height:\s*0/)
    assert.match(workListScrollRule, /min-height:\s*0/)
  })
})

test('works pages expose expected upload and edit structure', () => {
  const worksWxml = read('pages/works/works.wxml')
  const worksWxss = read('pages/works/works.wxss')
  const worksJs = read('pages/works/works.js')
  const addJs = read('pages/works/work-add/work-add.js')
  const addWxml = read('pages/works/work-add/work-add.wxml')
  const addWxss = read('pages/works/work-add/work-add.wxss')
  const editWxml = read('pages/works/work-edit/work-edit.wxml')
  const worksContentRule = readRule(worksWxss, '.works-content')
  const libraryPanelRule = readRule(worksWxss, '.library-panel')
  const workCardRule = readRule(worksWxss, '.work-card')
  const sheetRule = readRule(worksWxss, '.work-edit-panel')
  const referencePillRule = readRule(worksWxss, '.reference-pill')
  const statusBadgeRule = readRule(worksWxss, '.status-badge')
  const statusDotRule = readRule(worksWxss, '.status-dot')
  const statusPassedRule = readRule(worksWxss, '.status-badge.passed')
  const statusRejectedRule = readRule(worksWxss, '.status-badge.rejected')
  const uploadErrorRule = readRule(addWxss, '.error-copy')
  const workAddButtonRule = readRule(addWxss, '.primary-button')
  const tagPickerTemplate = readBetween(
    addWxml,
    /<scroll-view wx:else class="tag-option-list"/,
    /<view class="tag-picker-actions">/
  )
  const tagOptionRule = readRule(addWxss, '.tag-option')
  const tagOptionDotRule = readRule(addWxss, '.tag-option-dot')
  const tagOptionNameRule = readRule(addWxss, '.tag-option-name')
  const tagOptionCheckRule = readRule(addWxss, '.tag-option-check')
  const tagFilterTemplate = readBetween(worksWxml, /<view class="filter-panel">/, /<view class="library-panel">/)
  const tagDialogTemplate = readBetween(worksWxml, /<view class="tag-dialog /, /<view class="work-edit-mask image-edit-mask /)
  const tagActiveRule = readRule(worksWxss, '.tag-pill.active')
  const tagManageRule = readRule(worksWxss, '.tag-pill.manage')
  const tagDeleteRule = readRule(worksWxss, '.tag-delete')
  const tagAddButtonRule = readRule(worksWxss, '.tag-add-button')
  const tagInputRule = readRule(worksWxss, '.tag-input')
  const tagInputPlaceholderRule = readRule(worksWxss, '.tag-input-placeholder')
  const colorChoiceRule = readRule(worksWxss, '.color-choice')
  const activeColorChoiceRule = readRule(worksWxss, '.color-choice.active')
  const tagErrorRule = readRule(worksWxss, '.tag-error')

  assert.match(worksWxml, /搜索作品标题、标签/)
  assert.match(worksWxml, /长宽比/)
  assert.match(worksWxml, /class="search-clear"[\s\S]*wx:if="\{\{keyword\}\}"[\s\S]*catchtap="handleClearSearch"[\s\S]*aria-label="清空搜索"/)
  assert.match(worksWxss, /\.search-clear\s*\{[\s\S]*width:\s*44rpx;[\s\S]*height:\s*44rpx;[\s\S]*border-radius:\s*50%;/)
  assert.match(worksJs, /handleClearSearch\(\)\s*\{[\s\S]*keyword:\s*''[\s\S]*this\.loadWorks\(true\)/)
  assert.match(worksWxml, /批量管理/)
  assert.match(worksWxml, /<view class="works-scroll">[\s\S]*class="works-content" bindtap="handleCloseTagManageMode"/)
  assert.doesNotMatch(worksWxml, /<scroll-view class="works-scroll"[\s\S]*bindscrolltolower="handleScrollToLower"/)
  assert.match(worksWxml, /class="filter-panel"/)
  assert.match(worksWxml, /wx:for="\{\{list\.mediaFilters\}\}"[\s\S]*bindtap="handleMediaTypeTap"/)
  assert.match(worksWxml, /class="filter-shell" catchtap="handleFilterShellTap"/)
  assert.match(worksWxml, /<view[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.match(tagFilterTemplate, /style="\{\{tagManageMode && item\.id \? '' : \(\(\(!selectedTagId && !item\.id\) \|\| selectedTagId === item\.id\) \? item\.activeStyle : item\.filterStyle\)\}\}"/)
  assert.doesNotMatch(worksWxml, /<button[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.match(worksWxml, /bindlongpress="handleTagLongPress"/)
  assert.match(tagFilterTemplate, /wx:if="\{\{item\.id && \(tagManageMode \|\| selectedTagId !== item\.id\)\}\}"[\s\S]*class="tag-color-dot"[\s\S]*style="background: \{\{item\.color\}\};"/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*catchtap="handleTagDeleteTap"/)
  assert.match(tagFilterTemplate, /class="tag-delete"[\s\S]*aria-role="button"[\s\S]*aria-label="删除标签\{\{item\.name\}\}"/)
  assert.doesNotMatch(tagFilterTemplate, /class="tag-delete"[\s\S]*style="\{\{item\.deleteStyle\}\}"/)
  assert.match(worksWxml, /class="tag-add-button"[\s\S]*catchtap="handleOpenCreateTagDialog"[\s\S]*\+/)
  assert.doesNotMatch(worksWxml, /<button[^>]*class="[^"]*tag-add-button/)
  assert.match(worksWxml, /class="tag-dialog \{\{tagDialogVisible \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(worksWxml, /class="tag-dialog" wx:if="\{\{tagDialogVisible\}\}"/)
  assert.match(worksWxml, /class="work-edit-mask image-edit-mask \{\{imageEditSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel image-edit-panel"/)
  assert.match(worksWxml, /<scroll-view wx:if="\{\{!thumbnailCropVisible\}\}" class="work-edit-scroll image-edit-scroll" scroll-y>[\s\S]*<view class="work-edit-content">/)
  assert.doesNotMatch(worksWxml, /<scroll-view[^>]*class="work-edit-scroll image-edit-scroll"[^>]*type="list"/)
  assert.doesNotMatch(worksWxml, /imageEditForm\.previewPath/)
  assert.doesNotMatch(worksWxml, /thumbnail-crop-mask/)
  assert.doesNotMatch(worksWxss, /\.thumbnail-crop-mask/)
  assert.match(worksWxml, /wx:if="\{\{imageEditForm\.thumbnailPreviewPath && !thumbnailPreviewRenderFlip\}\}"[\s\S]*class="local-cover-preview thumbnail-preview"[\s\S]*src="\{\{imageEditForm\.thumbnailPreviewPath\}\}"[\s\S]*mode="widthFix"/)
  assert.match(worksWxml, /wx:elif="\{\{imageEditForm\.thumbnailPreviewPath\}\}"[\s\S]*class="local-cover-preview thumbnail-preview"[\s\S]*src="\{\{imageEditForm\.thumbnailPreviewPath\}\}"[\s\S]*mode="widthFix"/)
  assert.match(worksWxml, /wx:if="\{\{!thumbnailCropVisible\}\}"[\s\S]*class="cover-section thumbnail-section"/)
  assert.match(worksWxml, /wx:else[\s\S]*class="work-edit-scroll image-edit-scroll thumbnail-crop-editor"/)
  assert.match(worksWxml, /catchtouchstart="handleThumbnailCropTouchStart"[\s\S]*catchtouchmove="handleThumbnailCropTouchMove"/)
  assert.match(worksWxss, /\.thumbnail-ratio-list\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-wrap:\s*wrap;[\s\S]*overflow:\s*visible;/)
  assert.doesNotMatch(worksWxss, /\.thumbnail-ratio-list\s*\{[\s\S]*overflow-x:\s*auto;/)
  assert.match(worksWxss, /\.thumbnail-ratio\s*\{[\s\S]*flex:\s*0 0 calc\(\(100% - 12rpx\) \/ 2\);[\s\S]*max-width:\s*calc\(\(100% - 12rpx\) \/ 2\);/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品标题[\s\S]*\{\{imageEditFieldCounters\.title\}\}/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品说明[\s\S]*\{\{imageEditFieldCounters\.description\}\}/)
  assert.match(worksWxml, /bindinput="handleImageEditInput"/)
  assert.match(worksWxml, /catchtap="handleConfirmImageEdit"/)
  assert.match(worksWxml, /class="work-edit-mask video-edit-mask \{\{videoEditSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel video-edit-panel"/)
  assert.match(worksWxml, /<scroll-view class="work-edit-scroll video-edit-scroll" scroll-y>[\s\S]*<view class="work-edit-content">/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品标题[\s\S]*\{\{videoEditFieldCounters\.title\}\}/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品说明[\s\S]*\{\{videoEditFieldCounters\.description\}\}/)
  assert.match(worksWxml, /class="cover-export-button"[\s\S]*bindtap="handleStartVideoCoverEdit"[\s\S]*选帧修改封面/)
  assert.match(worksWxml, /class="cover-upload-button"[\s\S]*bindtap="handleChooseVideoCoverUpload"[\s\S]*上传封面/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === ''\}\}"[\s\S]*选帧修改封面[\s\S]*上传封面/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === 'frame'\}\}"[\s\S]*class="cover-edit-toolbar"[\s\S]*bindtap="handleExportVideoCover"[\s\S]*使用当前帧[\s\S]*id="workCoverVideo"[\s\S]*src="\{\{videoEditForm\.tempFilePath\}\}"/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === 'local'\}\}"[\s\S]*class="local-cover-preview"[\s\S]*src="\{\{videoEditForm\.localCoverPath\}\}"[\s\S]*bindtap="handleChooseVideoCoverUpload"[\s\S]*重新选择/)
  assert.match(worksWxml, /class="cover-edit-toolbar"[\s\S]*\{\{videoFrameTimeText\}\} \/ \{\{videoEditForm\.durationText\}\}/)
  assert.match(worksWxml, /class="work-edit-confirm"[\s\S]*catchtap="handleConfirmVideoEdit"[\s\S]*完成/)
  assert.match(worksWxml, /class="work-edit-mask animation-edit-mask \{\{animationEditSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel animation-edit-panel"/)
  assert.match(worksWxml, /class="work-edit-scroll animation-edit-scroll"[\s\S]*animationEditForm\.coverEdit\.previewUrl/)
  assert.match(worksWxml, /min="1"[\s\S]*max="\{\{animationEditForm\.coverEdit\.frameCount\}\}"[\s\S]*step="1"/)
  assert.match(worksWxml, /bindtap="handleUseAnimationCoverFrame"[\s\S]*使用当前帧/)
  assert.match(worksWxml, /catchtap="handleConfirmAnimationEdit"[\s\S]*完成/)
  assert.doesNotMatch(worksWxml, /editSheetVisible/)
  assert.doesNotMatch(worksWxml, /editForm\./)
  assert.doesNotMatch(worksWxml, /id="workCoverCanvas"/)
  assert.match(worksWxml, /标签文字/)
  assert.match(worksWxml, /标签颜色/)
  assert.match(worksWxml, /wx:for="\{\{tagColorOptions\}\}"/)
  assert.doesNotMatch(tagDialogTemplate, /class="color-choice[^"]*"[\s\S]*style="\{\{item\.choiceStyle\}\}"/)
  assert.match(tagDialogTemplate, /class="tag-input"[\s\S]*placeholder-class="tag-input-placeholder"/)
  assert.match(worksWxml, /class="library-panel"/)
  assert.match(worksWxml, /class="reference-pill/)
  assert.match(worksWxml, /class="work-status-row"[\s\S]*class="status-badge \{\{item\.auditStatusTone\}\}"[\s\S]*class="status-dot"[\s\S]*\{\{item\.auditStatusText\}\}/)
  assert.doesNotMatch(worksWxml, /class="audit-pill \{\{item\.auditStatusTone\}\}"/)
  assert.match(worksWxml, /wx:if="\{\{item\.showAuditRejectReason\}\}"[\s\S]*class="audit-reject-row"[\s\S]*class="audit-reject-icon"[\s\S]*![\s\S]*wx:for="\{\{item\.auditReasons\}\}"[\s\S]*wx:for-item="reason"[\s\S]*class="audit-reject-text"[\s\S]*\{\{reason\.message\}\}/)
  assert.match(worksWxml, /class="audit-resubmit-row"[\s\S]*class="audit-round-text"[\s\S]*\{\{item\.auditRoundText\}\}/)
  assert.match(worksWxml, /wx:if="\{\{item\.canResubmitAudit\}\}"[\s\S]*class="audit-resubmit-button"[\s\S]*loading="\{\{resubmittingWorkId === item\.id\}\}"[\s\S]*disabled="\{\{resubmittingWorkId === item\.id\}\}"[\s\S]*catchtap="handleAuditResubmitTap"[\s\S]*重新审核/)
  assert.match(worksWxss, /\.work-status-row\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-wrap:\s*wrap;/)
  assert.match(referencePillRule, /height:\s*42rpx/)
  assert.match(referencePillRule, /border:\s*1rpx solid #e9ecef/)
  assert.match(referencePillRule, /background:\s*#ffffff/)
  assert.match(statusBadgeRule, /gap:\s*8rpx/)
  assert.doesNotMatch(statusBadgeRule, /border:|background:/)
  assert.match(statusDotRule, /width:\s*12rpx/)
  assert.match(statusDotRule, /height:\s*12rpx/)
  assert.match(statusPassedRule, /color:\s*#5c9e6e/)
  assert.match(statusRejectedRule, /color:\s*#b55656/)
  assert.match(worksContentRule, /padding:\s*20rpx 32rpx calc\(172rpx \+ env\(safe-area-inset-bottom\)\)/)
  assert.match(libraryPanelRule, /border-radius:\s*48rpx/)
  assert.match(workCardRule, /border-radius:\s*40rpx/)
  assert.match(sheetRule, /border-radius:\s*56rpx 56rpx 0 0/)
  assert.match(uploadErrorRule, /color:\s*#b55656/)
  assert.match(workAddButtonRule, /background:\s*#212529/)
  assert.match(worksWxss, /\.audit-reject-row\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*flex-start;/)
  assert.match(worksWxss, /\.audit-reject-icon\s*\{[\s\S]*background:\s*#f6c343;/)
  assert.match(worksWxss, /\.audit-resubmit-row\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*align-items:\s*stretch;/)
  assert.match(worksWxss, /\.audit-round-text\s*\{[\s\S]*width:\s*100%;[\s\S]*flex:\s*none;/)
  assert.match(worksWxss, /\.audit-resubmit-button\s*\{[\s\S]*width:\s*136rpx;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*flex-end;[\s\S]*border-radius:\s*999rpx;/)
  assert.match(worksWxml, /class="work-swipe-row \{\{revealedWorkId === item\.id \? 'revealed' : ''\}\} \{\{batchMode \? 'batch-mode' : ''\}\}"/)
  assert.match(worksWxml, /<scroll-view[\s\S]*wx:else[\s\S]*class="work-list-scroll"[\s\S]*scroll-y[\s\S]*type="list"[\s\S]*bindscrolltolower="handleScrollToLower"[\s\S]*>[\s\S]*<view class="work-list">/)
  assert.match(worksWxml, /class="work-select \{\{item\.selected \? 'selected' : ''\}\}"/)
  assert.match(worksWxml, /wx:if="\{\{item\.mediaType === 'VIDEO'\}\}"[\s\S]*class="play-badge"[\s\S]*catchtap="handlePlayVideoTap"[\s\S]*aria-label="播放视频"/)
  assert.doesNotMatch(worksWxml, /class="thumb-order"/)
  assert.doesNotMatch(worksWxss, /\.thumb-order/)
  assert.match(worksWxml, /class="image-preview-mask \{\{imagePreviewVisible \? 'visible' : ''\}\}"[\s\S]*class="image-preview-title"[\s\S]*\{\{imagePreview\.title\}\}[\s\S]*class="image-preview-close"[\s\S]*catchtap="handleCloseImagePreview"[\s\S]*aria-label="关闭图片"[\s\S]*<image[\s\S]*wx:if="\{\{imagePreviewVisible && imagePreview\.src\}\}"[\s\S]*class="image-preview-media"[\s\S]*src="\{\{imagePreview\.src\}\}"[\s\S]*webp="\{\{true\}\}"[\s\S]*mode="aspectFit"/)
  assert.match(worksWxml, /class="video-preview-mask \{\{videoPreviewVisible \? 'visible' : ''\}\}"[\s\S]*id="workPreviewVideo"[\s\S]*src="\{\{videoPreview\.src\}\}"[\s\S]*poster="\{\{videoPreview\.poster\}\}"[\s\S]*autoplay="\{\{true\}\}"/)
  assert.match(worksWxml, /bindtouchstart="handleWorkTouchStart"[\s\S]*bindtouchmove="handleWorkTouchMove"[\s\S]*bindtouchend="handleWorkTouchEnd"[\s\S]*bindtouchcancel="handleWorkTouchCancel"/)
  assert.match(worksWxml, /class="work-delete-pane"[\s\S]*class="work-delete-button"[\s\S]*catchtap="handleDeleteWorkTap"[\s\S]*删除/)
  assert.match(worksWxss, /\.work-swipe-row\.revealed \.work-card\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(worksWxss, /\.work-delete-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(worksWxss, /\.work-delete-button\s*\{[\s\S]*width:\s*128rpx;[\s\S]*height:\s*100%;[\s\S]*border-radius:\s*0;/)
  assert.match(worksWxml, /class="batch-panel"/)
  assert.match(worksWxml, /class="list-actions"[\s\S]*class="text-action \{\{batchMode \? 'active' : ''\}\}"[\s\S]*class="tag-add-button work-add-button"[\s\S]*catchtap="handleAddTap"[\s\S]*\+/)
  assert.doesNotMatch(worksWxml, /class="primary-button full page-add-button"/)
  assert.match(worksWxml, /class="empty-logo-frame"[\s\S]*<image[\s\S]*class="empty-logo"[\s\S]*src="\/assets\/system\/work-logo-100kb\.jpg"[\s\S]*mode="aspectFit"/)
  assert.doesNotMatch(worksWxml, /class="empty-icon"/)
  assert.match(worksWxss, /\.empty-logo-frame\s*\{[\s\S]*overflow:\s*hidden;[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.42\);/)
  assert.doesNotMatch(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.5\);/)
  assert.match(worksWxml, /class="library-panel"[\s\S]*class="list-actions"[\s\S]*class="batch-panel"/)
  assert.match(worksWxml, /class="batch-panel" wx:if="\{\{batchMode && !loading && !errorMessage\}\}"/)
  assert.match(worksWxml, /class="batch-heading"[\s\S]*class="batch-copy"[\s\S]*class="batch-heading-actions"[\s\S]*class="batch-count"[\s\S]*class="batch-select-all"[\s\S]*bindtap="handleSelectAllBatchTap"[\s\S]*\{\{batchSelectAllText\}\}/)
  assert.match(worksWxml, /bindtap="handleBatchDeleteTap"/)
  assert.match(worksWxml, /bindtap="handleBatchPortfolioTap"/)
  assert.match(worksWxml, /bindtap="handleOpenSortMode"/)
  assert.match(worksWxml, /class="sort-mode-mask \{\{sortMode \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(worksWxml, /class="sort-mode-mask" wx:if="\{\{sortMode\}\}"/)
  assert.match(worksWxml, /class="sort-work-row \{\{sortDraggingWorkId === item\.id \? 'dragging' : ''\}\}"[\s\S]*style="\{\{sortDraggingWorkId === item\.id \? sortDragStyle : ''\}\}"[\s\S]*bindlongpress="handleSortDragStart"[\s\S]*bindtouchmove="handleSortDragMove"[\s\S]*bindtouchend="handleSortDragEnd"[\s\S]*bindtouchcancel="handleSortDragCancel"/)
  assert.match(worksWxml, /class="sort-drag-handle"/)
  assert.doesNotMatch(worksWxml, /class="sort-move-button"/)
  assert.doesNotMatch(worksWxml, />上移<\/button>/)
  assert.doesNotMatch(worksWxml, />下移<\/button>/)
  assert.match(worksWxml, /catchtap="handleSaveSort"/)
  assert.doesNotMatch(worksWxml, /class="empty-state"[\s\S]*bindtap="handleAddTap"[\s\S]*<\/view>\s*<view wx:else class="work-list"/)
  assert.doesNotMatch(worksWxml, /class="summary-strip"/)
  assert.doesNotMatch(worksWxml, /class="works-toolbar"/)
  assert.match(worksWxss, /\.filter-shell\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.works-content\s*\{[\s\S]*height:\s*100%;[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*padding:\s*20rpx 32rpx calc\(172rpx \+ env\(safe-area-inset-bottom\)\);/)
  assert.match(worksWxss, /\.library-panel\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*min-height:\s*0;[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(worksWxss, /\.work-list-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;[\s\S]*min-height:\s*0;[\s\S]*margin-top:\s*18rpx;/)
  assert.match(worksWxss, /\.sort-work-row\.dragging\s*\{[\s\S]*border-color:\s*#3d6fad;/)
  assert.match(worksWxss, /\.sort-work-row\s*\{[\s\S]*transition:\s*transform 160ms cubic-bezier\(0\.2, 0, 0, 1\)/)
  assert.match(worksWxss, /\.sort-work-row\.dragging\s*\{[\s\S]*will-change:\s*transform;/)
  assert.match(worksWxss, /\.sort-drag-handle\s*\{[\s\S]*width:\s*56rpx;[\s\S]*height:\s*64rpx;/)
  assert.doesNotMatch(worksWxss, /\.sort-move-button\s*\{/)
  assert.match(worksWxss, /\.tag-add-button\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.tag-delete\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*<text class="tag-delete-mark">×<\/text>[\s\S]*<\/view>/)
  assert.match(worksWxss, /\.tag-delete-mark\s*\{[\s\S]*transform:\s*translateY\(-1rpx\);/)
  assert.match(tagManageRule, /color:\s*#212529/)
  assert.match(tagManageRule, /font-weight:\s*600/)
  assert.match(tagManageRule, /border-color:\s*#e9ecef/)
  assert.match(tagManageRule, /background:\s*#ffffff/)
  assert.match(tagManageRule, /box-shadow:\s*none/)
  assert.match(worksWxss, /\.tag-pill\.manage::before\s*\{[^}]*display:\s*none;/)
  assert.match(worksWxss, /\.tag-color-dot\s*\{[^}]*width:\s*12rpx;[^}]*height:\s*12rpx;[^}]*border-radius:\s*50%;/)
  assert.match(tagDeleteRule, /color:\s*#b55656/)
  assert.match(tagDeleteRule, /border:\s*1rpx solid #e8caca/)
  assert.match(tagDeleteRule, /background:\s*#faf2f2/)
  assert.doesNotMatch(tagDeleteRule, /box-shadow:/)
  assert.match(tagAddButtonRule, /color:\s*#212529/)
  assert.match(tagAddButtonRule, /border:\s*1rpx solid #e9ecef/)
  assert.match(tagAddButtonRule, /background:\s*#ffffff/)
  assert.doesNotMatch(tagAddButtonRule, /linear-gradient|box-shadow/)
  assert.match(worksWxml, /class="tag-dialog-grabber"/)
  assert.match(worksWxss, /\.tag-dialog\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*flex-end;[\s\S]*padding:\s*0;/)
  assert.match(worksWxss, /\.tag-dialog-panel\s*\{[\s\S]*position:\s*relative;[\s\S]*width:\s*100%;[\s\S]*border-radius:\s*56rpx 56rpx 0 0;/)
  assert.match(tagInputRule, /border:\s*0/)
  assert.match(tagInputRule, /border-radius:\s*999rpx/)
  assert.match(tagInputRule, /background:\s*#f5f6f7/)
  assert.match(tagInputPlaceholderRule, /color:\s*#adb5bd/)
  assert.match(tagInputPlaceholderRule, /font-weight:\s*400/)
  assert.match(colorChoiceRule, /border:\s*1rpx solid #e9ecef/)
  assert.match(colorChoiceRule, /border-radius:\s*999rpx/)
  assert.match(colorChoiceRule, /background:\s*#ffffff/)
  assert.match(activeColorChoiceRule, /border-color:\s*#212529/)
  assert.doesNotMatch(activeColorChoiceRule, /box-shadow:/)
  assert.match(tagErrorRule, /color:\s*#b55656/)
  assert.match(worksWxss, /\.secondary-button,\s*\.dialog-button\s*\{[^}]*border-radius:\s*999rpx;/)
  assert.match(worksWxss, /\.secondary-button\s*\{[^}]*color:\s*#212529;[^}]*border:\s*1rpx solid #e9ecef;/)
  assert.match(worksWxss, /\.dialog-button\s*\{[^}]*color:\s*#ffffff;[^}]*background:\s*#212529;/)
  assert.match(worksWxss, /\.work-edit-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(worksWxss, '.tag-dialog', '.tag-dialog-panel')
  assertSoftLayerAnimation(worksWxss, '.work-edit-mask', '.work-edit-panel')
  assertSoftLayerAnimation(worksWxss, '.sort-mode-mask', '.sort-mode-panel')
  assertSoftLayerAnimation(worksWxss, '.image-preview-mask', '.image-preview-panel')
  assertSoftLayerAnimation(worksWxss, '.video-preview-mask', '.video-preview-panel')
  assert.match(worksWxss, /\.image-preview-mask,\s*[\s\S]*\.video-preview-mask\s*\{[\s\S]*transition:\s*opacity\s+260ms\s+ease;/)
  assert.match(worksWxss, /\.image-preview-panel,\s*[\s\S]*\.video-preview-panel\s*\{[\s\S]*transition:\s*transform\s+260ms/)
  assert.match(worksWxss, /\.image-preview-close,\s*[\s\S]*\.video-preview-close\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.work-edit-panel\s*\{[\s\S]*overflow:\s*hidden;/)
  assert.match(worksWxss, /\.work-edit-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;[\s\S]*min-height:\s*0;/)
  assert.doesNotMatch(worksWxss, /\.work-edit-panel\s*\{[^}]*height:\s*auto;/)
  assert.doesNotMatch(worksWxss, /\.work-edit-scroll\s*\{[^}]*height:\s*auto;/)
  assert.doesNotMatch(worksWxss, /\.image-edit-mask\s+\.work-edit-panel/)
  assert.doesNotMatch(worksWxss, /\.image-edit-mask\s+\.work-edit-scroll/)
  assert.doesNotMatch(worksWxss, /\.video-edit-mask\s+\.work-edit-panel/)
  assert.doesNotMatch(worksWxss, /\.video-edit-mask\s+\.work-edit-scroll/)
  const imageEditPanelRule = readRule(worksWxss, '.image-edit-panel')
  const imageEditScrollRule = readRule(worksWxss, '.image-edit-scroll')
  const videoEditPanelRule = readRule(worksWxss, '.video-edit-panel')
  const videoEditScrollRule = readRule(worksWxss, '.video-edit-scroll')
  assert.match(imageEditPanelRule, /height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(imageEditPanelRule, /max-height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(imageEditPanelRule, /height:\s*auto/)
  assert.match(imageEditScrollRule, /flex:\s*1 1 auto;/)
  assert.match(imageEditScrollRule, /height:\s*0;/)
  assert.match(imageEditScrollRule, /min-height:\s*0;/)
  assert.doesNotMatch(imageEditScrollRule, /height:\s*auto/)
  assert.doesNotMatch(imageEditScrollRule, /max-height:\s*calc/)
  assert.match(videoEditPanelRule, /height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(videoEditPanelRule, /max-height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(videoEditPanelRule, /height:\s*auto/)
  assert.match(videoEditScrollRule, /flex:\s*1 1 auto;/)
  assert.match(videoEditScrollRule, /height:\s*0;/)
  assert.match(videoEditScrollRule, /min-height:\s*0;/)
  assert.doesNotMatch(videoEditScrollRule, /height:\s*auto/)
  assert.doesNotMatch(videoEditScrollRule, /max-height:\s*calc/)
  assert.match(worksWxml, /<scroll-view wx:else class="work-edit-scroll image-edit-scroll thumbnail-crop-editor" scroll-y>/)
  assert.match(worksWxss, /\.thumbnail-crop-editor\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.doesNotMatch(readRule(worksWxss, '.thumbnail-crop-editor'), /height:\s*auto/)
  assert.match(worksWxss, /\.field-heading\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(worksWxss, /\.field-limit\s*\{[\s\S]*color:\s*#8b96a3;/)
  assert.match(worksWxss, /\.cover-edit-toolbar\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.cover-use-frame-button\s*\{[\s\S]*min-width:\s*176rpx;/)
  assert.doesNotMatch(worksWxss, /\.frame-export-canvas\s*\{/)
  assert.match(worksWxss, /\.color-grid\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-wrap:\s*wrap;/)
  assert.doesNotMatch(worksWxss, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(worksWxss, /\.color-choice\s*\{[\s\S]*width:\s*31\.3%;[\s\S]*flex:\s*none;/)
  assert.match(worksWxss, /\.tag-scroll\s*\{[\s\S]*height:\s*64rpx;/)
  assert.match(worksWxss, /\.tag-row\s*\{[\s\S]*height:\s*64rpx;[\s\S]*display:\s*inline-flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.tag-pill\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;[\s\S]*display:\s*inline-flex;[\s\S]*flex:\s*0 0 auto;/)
  assert.match(tagActiveRule, /font-weight:\s*600/)
  assert.doesNotMatch(tagActiveRule, /box-shadow:|transform:/)
  assert.match(worksWxss, /\.tag-pill\.active::before\s*\{[\s\S]*content:\s*"";[\s\S]*display:\s*block;[\s\S]*width:\s*10rpx;[\s\S]*height:\s*10rpx;[\s\S]*background:\s*#ffffff;/)
  assert.doesNotMatch(worksWxss, /\.tag-pill\s*\{[\s\S]*min-width:\s*116rpx;/)
  assert.match(worksWxss, /\.list-heading,\s*[\s\S]*\.list-actions,\s*[\s\S]*\.batch-heading\s*\{[\s\S]*width:\s*100%;[\s\S]*justify-content:\s*space-between;/)
  assert.match(worksWxss, /\.section-title,\s*[\s\S]*\.batch-title\s*\{[\s\S]*flex:\s*1 1 auto;/)
  assert.match(worksWxss, /\.list-actions\s*\{[\s\S]*width:\s*auto;[\s\S]*flex:\s*none;[\s\S]*gap:\s*14rpx;/)
  assert.match(worksWxss, /\.work-add-button\s*\{[\s\S]*flex:\s*none;/)
  assert.doesNotMatch(worksWxss, /\.page-add-button\s*\{/)
  assert.match(worksWxss, /\.text-action\s*\{[\s\S]*min-width:\s*128rpx;[\s\S]*max-width:\s*128rpx;/)
  assert.match(worksWxss, /\.batch-copy\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*min-width:\s*0;/)
  assert.match(worksWxss, /\.batch-heading-actions\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*flex:\s*none;[\s\S]*gap:\s*12rpx;/)
  assert.match(worksWxss, /\.batch-select-all\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*88rpx;[\s\S]*max-width:\s*136rpx;[\s\S]*height:\s*50rpx;/)
  assert.match(addJs, /createChooseMediaOptions/)
  assert.match(addJs, /buildUploadCompleteFailureMessage/)
  assert.match(addJs, /buildUploadProgressSummary/)
  assert.doesNotMatch(addJs, /failedItems\[0\]/)
  assert.match(addWxml, /一次最多勾选 9 个/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*已选作品[\s\S]*\{\{files\.length\}\} \/ 9[\s\S]*class="selected-work-list(?:\s|")/)
  assert.match(addWxml, /class="selected-work-list count-\{\{files\.length > 3 \? 'many' : files\.length\}\}"/)
  assert.match(addWxml, /class="selected-work-row"[\s\S]*\{\{item\.title \|\| item\.fileName\}\}[\s\S]*\{\{item\.metaText\}\}/)
  assert.match(addWxml, /class="selected-work-progress"[\s\S]*class="selected-work-progress-fill"[\s\S]*customCoverProgress[\s\S]*item\.progress/)
  assert.match(addWxml, /class="selected-work-thumb \{\{item\.isVideo \? 'video' : ''\}\}"/)
  assert.match(addWxml, /class="selected-work-swipe-row \{\{revealedFileId === item\.id \? 'revealed' : ''\}\}"/)
  assert.match(addWxml, /bindtouchstart="handleFileTouchStart"[\s\S]*bindtouchmove="handleFileTouchMove"[\s\S]*bindtouchend="handleFileTouchEnd"/)
  assert.match(addWxml, /class="selected-work-remove-pane"[\s\S]*class="selected-work-remove-button"[\s\S]*catchtap="handleRemoveFile"[\s\S]*移除/)
  assert.match(addWxml, /class="selected-work-row"[\s\S]*bindtap="handleOpenFileEditor"[\s\S]*\{\{item\.title \|\| item\.fileName\}\}/)
  assert.match(addWxml, /class="work-edit-mask \{\{editForm\.isVideo \? 'video-edit-mask' : 'image-edit-mask'\}\} \{\{editSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel"/)
  assert.doesNotMatch(addWxml, /class="work-edit-mask" wx:if="\{\{editSheetVisible\}\}"/)
  assert.match(addWxml, /<image wx:if="\{\{!editForm\.isVideo\}\}" class="work-preview-media" src="\{\{editForm\.tempFilePath\}\}" webp="\{\{true\}\}" mode="aspectFit"><\/image>/)
  assert.doesNotMatch(addWxml, /<image wx:if="\{\{!editForm\.isVideo\}\}" class="work-preview-media" src="\{\{editForm\.tempFilePath\}\}" mode="aspectFill"><\/image>/)
  assert.match(addWxml, /placeholder="填写作品标题"[\s\S]*bindinput="handleEditInput"/)
  assert.match(addWxml, /placeholder="填写作品说明"[\s\S]*maxlength="1000"[\s\S]*bindinput="handleEditInput"/)
  assert.doesNotMatch(addWxml, /wx:if="\{\{editForm\.isVideo\}\}"[\s\S]*class="cover-edit-toolbar"/)
  assert.doesNotMatch(addWxml, /id="workCoverVideo"/)
  assert.doesNotMatch(addWxml, /class="cover-slider"/)
  assert.doesNotMatch(addWxml, /class="cover-export-button"[\s\S]*bindtap="handleExportVideoCover"[\s\S]*使用当前帧做封面/)
  assert.doesNotMatch(addWxml, /id="workCoverCanvas"/)
  assert.doesNotMatch(addWxml, /canvas-id="workCoverCanvas"/)
  assert.match(addWxml, /<view class="tag-panel">[\s\S]*统一标签（可选）[\s\S]*class="tag-add-trigger"[\s\S]*catchtap="handleOpenTagPicker"[\s\S]*\+添加[\s\S]*作品说明可保存后补充/)
  assert.match(addWxml, /wx:for="\{\{unifiedTags\}\}"[\s\S]*class="tag-chip"[\s\S]*style="\{\{item\.style\}\}"[\s\S]*\{\{item\.name\}\}/)
  assert.doesNotMatch(addWxml, /class="tag-chip \{\{index === 1 \? 'blue' : 'teal'\}\}"/)
  assert.doesNotMatch(addWxml, /<view wx:if="\{\{files\.length > 0\}\}" class="tag-panel">/)
  assert.match(addWxml, /class="tag-note" wx:if="\{\{files\.length > 0\}\}"/)
  assert.match(addWxml, /class="tag-note muted" wx:else/)
  assert.match(addWxml, /class="primary-button \{\{files\.length === 0 \? 'empty-disabled' : ''\}\}"/)
  assert.match(addWxml, /class="primary-button-label"[\s\S]*\{\{saving \? uploadOverallText : '保存作品'\}\}/)
  assert.match(addWxml, /class="primary-button-progress"[\s\S]*class="primary-button-progress-fill"[\s\S]*width:\s*\{\{uploadOverallProgress\}\}%/)
  assert.match(addWxml, /disabled="\{\{saving\}\}"/)
  assert.doesNotMatch(addWxml, /disabled="\{\{saving \|\| files\.length === 0\}\}"/)
  assert.doesNotMatch(addWxml, /placeholder="统一标签"/)
  assert.doesNotMatch(addWxml, /class="tag-input"/)
  assert.match(addWxml, /class="tag-picker-mask \{\{tagPickerVisible \? 'visible' : ''\}\}"[\s\S]*class="tag-picker-panel"/)
  assert.doesNotMatch(addWxml, /class="tag-picker-mask" wx:if="\{\{tagPickerVisible\}\}"/)
  assert.match(addWxml, /<scroll-view wx:else class="tag-option-list"[^>]*style="height:\s*\{\{tagOptionListHeight\}\}rpx;"/)
  assert.match(addWxml, /wx:for="\{\{tagPickerTags\}\}"[\s\S]*class="tag-option \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*catchtap="handleToggleUnifiedTag"/)
  assert.match(
    tagPickerTemplate,
    /style="\{\{item\.selected \? item\.activeStyle : item\.filterStyle\}\}"/
  )
  assert.match(
    tagPickerTemplate,
    /class="tag-option-dot"[\s\S]*style="background:\s*\{\{item\.selected \? '#ffffff' : item\.color\}\};"/
  )
  assert.match(
    tagPickerTemplate,
    /class="tag-option-name"\s+style="color:\s*\{\{item\.selected \? '#ffffff' : item\.color\}\};"[\s\S]*\{\{item\.name\}\}/
  )
  assert.match(
    tagPickerTemplate,
    /wx:if="\{\{item\.selected\}\}" class="tag-option-check">✓<\/view>/
  )
  assert.match(addWxml, /class="tag-picker-confirm"[\s\S]*catchtap="handleConfirmTagPicker"[\s\S]*完成/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*class="tag-panel"[\s\S]*class="error-copy"/)
  assert.doesNotMatch(addWxml, /class="selected-card"/)
  assert.doesNotMatch(addWxml, /class="desc-input"/)
  assert.match(addJs, /WORK_TAGS_API_URL\s*=\s*'\/api\/mine\/works\/tags'/)
  assert.match(addJs, /handleOpenFileEditor/)
  assert.match(addJs, /handleFileTouchStart/)
  assert.doesNotMatch(addJs, /handleExportVideoCover/)
  assert.doesNotMatch(addJs, /createVideoDecoder/)
  assert.doesNotMatch(addJs, /writeRgbaFrameToCanvas/)
  assert.doesNotMatch(addJs, /wx\.canvasPutImageData/)
  assert.match(worksJs, /coverEditMode:\s*''/)
  assert.match(worksJs, /handleChooseVideoCoverUpload/)
  assert.match(worksJs, /uploadVideoCoverOnConfirm/)
  assert.match(worksJs, /coverTaskId/)
  assert.match(addJs, /normalizeWorkTags/)
  assert.match(addJs, /handleOpenTagPicker/)
  assert.match(addJs, /handleToggleUnifiedTag/)
  assert.match(addJs, /handleConfirmTagPicker/)
  assert.match(addJs, /tagOptionListHeight/)
  assert.match(addJs, /buildWorkTagOptionListHeight/)
  assert.match(addWxss, /\.work-add-content\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(addWxss, /\.upload-box\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.empty-state\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;/)
  assert.match(addWxss, /\.primary-button\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.primary-button\.empty-disabled\s*\{[\s\S]*color:\s*#5f6b78;[\s\S]*background:\s*#e6ebf0;[\s\S]*box-shadow:\s*none;/)
  assert.match(addWxss, /\.tag-note\s*\{[\s\S]*margin-top:\s*16rpx;[\s\S]*padding:\s*18rpx 20rpx;/)
  assert.match(addWxss, /\.tag-note\.muted\s*\{[\s\S]*color:\s*#7b8794;/)
  assert.match(addWxss, /\.tag-add-trigger\s*\{[\s\S]*width:\s*auto;[\s\S]*height:\s*50rpx;[\s\S]*flex:\s*0 0 auto;[\s\S]*align-self:\s*flex-start;/)
  assert.match(addWxss, /\.cover-edit-toolbar\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(addWxss, /\.cover-use-frame-button\s*\{[\s\S]*min-width:\s*176rpx;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*border:\s*1rpx solid #d7dee5;[\s\S]*border-radius:\s*16rpx;/)
  assert.match(addWxss, /\.selected-work-list\s*\{[\s\S]*height:\s*528rpx;[\s\S]*max-height:\s*528rpx;[\s\S]*overflow:\s*hidden;/)
  assert.match(addWxss, /\.selected-work-list\.count-1\s*\{[\s\S]*height:\s*160rpx;/)
  assert.match(addWxss, /\.selected-work-list\.count-2\s*\{[\s\S]*height:\s*336rpx;/)
  assert.match(addWxss, /\.selected-work-list\.count-3\s*\{[\s\S]*height:\s*512rpx;/)
  assert.match(addWxss, /\.selected-work-list-content\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(addWxss, /\.selected-work-row\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.doesNotMatch(addWxss, /\.selected-work-row\s*\{[\s\S]*grid-template-columns:/)
  assert.match(addWxss, /\.selected-work-copy\s*\{[\s\S]*flex:\s*1 1 0;[\s\S]*min-width:\s*0;/)
  assert.match(addWxss, /\.selected-work-progress\s*\{[\s\S]*width:\s*100%;/)
  assert.match(addWxss, /\.selected-work-progress-fill\s*\{[\s\S]*height:\s*100%;/)
  assert.match(addWxss, /\.selected-work-swipe-row\.revealed \.selected-work-row\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(addWxss, /\.selected-work-remove-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.doesNotMatch(addWxss, /\.tag-panel\s*\{[\s\S]*display:\s*grid;/)
  assert.match(addWxss, /\.tag-row\s*\{[\s\S]*margin-top:\s*12rpx;[\s\S]*display:\s*flex;/)
  assert.match(addWxss, /\.tag-picker-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(addWxss, '.tag-picker-mask', '.tag-picker-panel')
  const addTagOptionListRule = readRule(addWxss, '.tag-option-list')
  const addTagOptionListContentRule = readRule(addWxss, '.tag-option-list-content')
  const addTagPickerActionsRule = readRule(addWxss, '.tag-picker-actions')
  assert.match(addTagOptionListRule, /max-height:\s*520rpx;/)
  assert.match(addTagOptionListRule, /flex:\s*none;/)
  assert.doesNotMatch(addTagOptionListRule, /(^|\n)\s*height:\s*320rpx;/)
  assert.match(addTagOptionListContentRule, /display:\s*flex;/)
  assert.match(addTagOptionListContentRule, /flex-wrap:\s*wrap;/)
  assert.match(addTagPickerActionsRule, /flex:\s*none;/)
  assert.match(tagOptionRule, /width:\s*auto;/)
  assert.match(tagOptionRule, /flex:\s*0 0 auto;/)
  assert.match(tagOptionRule, /height:\s*50rpx/)
  assert.match(tagOptionRule, /display:\s*inline-flex/)
  assert.match(tagOptionRule, /justify-content:\s*center/)
  assert.match(tagOptionRule, /gap:\s*8rpx/)
  assert.match(tagOptionRule, /padding:\s*0 20rpx/)
  assert.match(tagOptionDotRule, /width:\s*12rpx/)
  assert.match(tagOptionDotRule, /height:\s*12rpx/)
  assert.match(tagOptionDotRule, /border-radius:\s*50%/)
  assert.match(tagOptionNameRule, /flex:\s*none/)
  assert.doesNotMatch(tagOptionNameRule, /min-width:\s*0/)
  assert.match(tagOptionCheckRule, /color:\s*inherit/)
  assert.match(addWxss, /\.work-edit-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(addWxss, '.work-edit-mask', '.work-edit-panel')
  assert.match(addWxss, /\.work-edit-panel\s*\{[\s\S]*height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(addWxss, /\.work-edit-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;/)
  assert.match(addWxss, /\.image-edit-mask \.work-edit-panel\s*\{[\s\S]*height:\s*auto;[\s\S]*max-height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(addWxss, /\.image-edit-mask \.work-edit-scroll\s*\{[\s\S]*flex:\s*0 1 auto;[\s\S]*height:\s*auto;[\s\S]*max-height:\s*calc\(78vh - 176rpx - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(addWxss, /\.work-edit-scroll\s*\{[\s\S]*max-height:\s*64vh;/)
  assert.match(addWxss, /\.primary-button-progress\s*\{[\s\S]*width:\s*240rpx;[\s\S]*height:\s*8rpx;/)
  assert.doesNotMatch(addWxss, /\.frame-export-canvas\s*\{/)
  assert.match(editWxml, /引用/)
  assert.match(editWxml, /保存/)
})

test('works edit sheets contain tag selectors and referenced-work notice', () => {
  const worksWxml = read('pages/works/works.wxml')
  const worksJs = read('pages/works/works.js')

  assert.match(worksWxml, /handleImageEditTagToggle/)
  assert.match(worksWxml, /handleVideoEditTagToggle/)
  assert.match(worksWxml, /imageEditForm\.tagOptions/)
  assert.match(worksWxml, /videoEditForm\.tagOptions/)
  assert.match(worksWxml, /imageEditForm\.tagEditNotice/)
  assert.match(worksWxml, /videoEditForm\.tagEditNotice/)
  assert.match(worksJs, /已引用作品只能新增标签/)
})

test('works edit sheets refresh list after successful save', () => {
  const worksJs = read('pages/works/works.js')
  const imageConfirmBody = readBetween(
    worksJs,
    /async handleConfirmImageEdit\(\)/,
    /handleVideoEditMetadata\(event\)/
  )
  const videoConfirmBody = readBetween(
    worksJs,
    /async handleConfirmVideoEdit\(\)/,
    /async handleConfirmAnimationEdit\(\)/
  )
  const animationConfirmBody = readBetween(
    worksJs,
    /async handleConfirmAnimationEdit\(\)/,
    /patchWorkInList\(sourceForm/
  )

  assert.match(imageConfirmBody, /await this\.loadWorks\(true\)/)
  assert.match(videoConfirmBody, /await this\.loadWorks\(true\)/)
  assert.match(animationConfirmBody, /await this\.loadWorks\(true\)/)
  assert.match(animationConfirmBody, /coverFrameNumber:\s*coverEdit\.selectedFrame/)
  assert.match(animationConfirmBody, /coverFrameIdempotencyKey:\s*coverEdit\.idempotencyKey/)
})

test('works edit sheet tag options use defined tag color styles', () => {
  const worksWxml = read('pages/works/works.wxml')
  const coloredTagOptions = worksWxml.match(/class="edit-tag-option[\s\S]*?style="\{\{item\.selected \? item\.activeStyle : item\.style\}\}"/g) || []

  assert.equal(coloredTagOptions.length, 3)
})
