const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8'))

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

function readRule(content, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = content.match(new RegExp(`${escapedSelector}\\s*\\{([^}]*)\\}`))
  return match ? match[1] : ''
}

function assertSoftLayerAnimation(wxss, overlaySelector, panelSelector) {
  const overlayRule = readRule(wxss, overlaySelector)
  const visibleOverlayRule = readRule(wxss, `${overlaySelector}.visible`)
  const panelRule = readRule(wxss, panelSelector)
  const visiblePanelRule = readRule(wxss, `${overlaySelector}.visible ${panelSelector}`)

  assert.match(overlayRule, /opacity:\s*0/)
  assert.match(overlayRule, /pointer-events:\s*none/)
  assert.match(overlayRule, /transition:[^;]*opacity\s+\d+ms/)
  assert.match(visibleOverlayRule, /opacity:\s*1/)
  assert.match(visibleOverlayRule, /pointer-events:\s*auto/)
  assert.match(panelRule, /transform:/)
  assert.match(panelRule, /transition:[^;]*transform\s+\d+ms/)
  assert.match(visiblePanelRule, /transform:/)
  assert.doesNotMatch(panelRule, /translateY\(32rpx\)/)
  assert.doesNotMatch(panelRule, /transition:\s*transform 180ms ease/)
}

test('app registers works pages in the mini program', () => {
  assert.ok(appJson.pages.includes('pages/works/works'))
  assert.ok(appJson.pages.includes('pages/work-add/work-add'))
  assert.ok(appJson.pages.includes('pages/work-edit/work-edit'))
})

test('mine and schedule bottom tabs navigate to works page', () => {
  const indexJs = read('pages/index/index.js')
  const scheduleJs = read('pages/schedule/schedule.js')

  assert.match(indexJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
  assert.match(scheduleJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
})

test('works pages expose expected upload and edit structure', () => {
  const worksWxml = read('pages/works/works.wxml')
  const worksWxss = read('pages/works/works.wxss')
  const worksJs = read('pages/works/works.js')
  const addJs = read('pages/work-add/work-add.js')
  const addWxml = read('pages/work-add/work-add.wxml')
  const addWxss = read('pages/work-add/work-add.wxss')
  const editWxml = read('pages/work-edit/work-edit.wxml')

  assert.match(worksWxml, /搜索作品标题、标签/)
  assert.match(worksWxml, /class="search-clear"[\s\S]*wx:if="\{\{keyword\}\}"[\s\S]*catchtap="handleClearSearch"[\s\S]*aria-label="清空搜索"/)
  assert.match(worksWxss, /\.search-clear\s*\{[\s\S]*width:\s*44rpx;[\s\S]*height:\s*44rpx;[\s\S]*border-radius:\s*50%;/)
  assert.match(worksJs, /handleClearSearch\(\)\s*\{[\s\S]*keyword:\s*''[\s\S]*this\.loadWorks\(true\)/)
  assert.match(worksWxml, /批量管理/)
  assert.match(worksWxml, /<view class="works-scroll">[\s\S]*class="works-content" bindtap="handleCloseTagManageMode"/)
  assert.doesNotMatch(worksWxml, /<scroll-view class="works-scroll"[\s\S]*bindscrolltolower="handleScrollToLower"/)
  assert.match(worksWxml, /class="filter-panel"/)
  assert.match(worksWxml, /class="filter-shell" catchtap="handleFilterShellTap"/)
  assert.match(worksWxml, /<view[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.match(worksWxml, /style="\{\{\(\(!selectedTagId && !item\.id\) \|\| selectedTagId === item\.id\) \? item\.activeStyle : item\.style\}\}"/)
  assert.doesNotMatch(worksWxml, /<button[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.match(worksWxml, /bindlongpress="handleTagLongPress"/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*catchtap="handleTagDeleteTap"/)
  assert.match(worksWxml, /class="tag-add-button"[\s\S]*catchtap="handleOpenCreateTagDialog"[\s\S]*\+/)
  assert.doesNotMatch(worksWxml, /<button[^>]*class="[^"]*tag-add-button/)
  assert.match(worksWxml, /class="tag-dialog \{\{tagDialogVisible \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(worksWxml, /class="tag-dialog" wx:if="\{\{tagDialogVisible\}\}"/)
  assert.match(worksWxml, /class="work-edit-mask image-edit-mask \{\{imageEditSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel"/)
  assert.match(worksWxml, /<scroll-view class="work-edit-scroll" scroll-y>[\s\S]*<view class="work-edit-content">/)
  assert.doesNotMatch(worksWxml, /<scroll-view class="work-edit-scroll" scroll-y type="list">/)
  assert.match(worksWxml, /<image class="work-preview-media" src="\{\{imageEditForm\.previewPath\}\}" mode="aspectFit"><\/image>/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品标题[\s\S]*\{\{imageEditFieldCounters\.title\}\}/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品说明[\s\S]*\{\{imageEditFieldCounters\.description\}\}/)
  assert.match(worksWxml, /bindinput="handleImageEditInput"/)
  assert.match(worksWxml, /catchtap="handleConfirmImageEdit"/)
  assert.match(worksWxml, /class="work-edit-mask video-edit-mask \{\{videoEditSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel"/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品标题[\s\S]*\{\{videoEditFieldCounters\.title\}\}/)
  assert.match(worksWxml, /class="field-heading"[\s\S]*作品说明[\s\S]*\{\{videoEditFieldCounters\.description\}\}/)
  assert.match(worksWxml, /class="cover-export-button"[\s\S]*bindtap="handleStartVideoCoverEdit"[\s\S]*选帧修改封面/)
  assert.match(worksWxml, /class="cover-upload-button"[\s\S]*bindtap="handleChooseVideoCoverUpload"[\s\S]*上传封面/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === ''\}\}"[\s\S]*选帧修改封面[\s\S]*上传封面/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === 'frame'\}\}"[\s\S]*class="cover-edit-toolbar"[\s\S]*bindtap="handleExportVideoCover"[\s\S]*使用当前帧[\s\S]*id="workCoverVideo"[\s\S]*src="\{\{videoEditForm\.tempFilePath\}\}"/)
  assert.match(worksWxml, /wx:if="\{\{videoEditForm\.coverEditMode === 'local'\}\}"[\s\S]*class="local-cover-preview"[\s\S]*src="\{\{videoEditForm\.localCoverPath\}\}"[\s\S]*bindtap="handleChooseVideoCoverUpload"[\s\S]*重新选择/)
  assert.match(worksWxml, /class="cover-edit-toolbar"[\s\S]*\{\{videoFrameTimeText\}\} \/ \{\{videoEditForm\.durationText\}\}/)
  assert.match(worksWxml, /class="work-edit-confirm"[\s\S]*catchtap="handleConfirmVideoEdit"[\s\S]*完成/)
  assert.doesNotMatch(worksWxml, /editSheetVisible/)
  assert.doesNotMatch(worksWxml, /editForm\./)
  assert.doesNotMatch(worksWxml, /id="workCoverCanvas"/)
  assert.match(worksWxml, /标签文字/)
  assert.match(worksWxml, /标签颜色/)
  assert.match(worksWxml, /wx:for="\{\{tagColorOptions\}\}"/)
  assert.match(worksWxml, /class="library-panel"/)
  assert.match(worksWxml, /class="reference-pill/)
  assert.match(worksWxml, /class="work-swipe-row \{\{revealedWorkId === item\.id \? 'revealed' : ''\}\} \{\{batchMode \? 'batch-mode' : ''\}\}"/)
  assert.match(worksWxml, /<scroll-view wx:else class="work-list-scroll" scroll-y type="list" bindscrolltolower="handleScrollToLower">[\s\S]*<view class="work-list">/)
  assert.match(worksWxml, /class="work-select \{\{item\.selected \? 'selected' : ''\}\}"/)
  assert.match(worksWxml, /wx:if="\{\{item\.mediaType === 'VIDEO'\}\}"[\s\S]*class="play-badge"[\s\S]*catchtap="handlePlayVideoTap"[\s\S]*aria-label="播放视频"/)
  assert.doesNotMatch(worksWxml, /class="thumb-order"/)
  assert.doesNotMatch(worksWxss, /\.thumb-order/)
  assert.match(worksWxml, /class="video-preview-mask \{\{videoPreviewVisible \? 'visible' : ''\}\}"[\s\S]*id="workPreviewVideo"[\s\S]*src="\{\{videoPreview\.src\}\}"[\s\S]*poster="\{\{videoPreview\.poster\}\}"[\s\S]*autoplay="\{\{true\}\}"/)
  assert.match(worksWxml, /bindtouchstart="handleWorkTouchStart"[\s\S]*bindtouchmove="handleWorkTouchMove"[\s\S]*bindtouchend="handleWorkTouchEnd"[\s\S]*bindtouchcancel="handleWorkTouchCancel"/)
  assert.match(worksWxml, /class="work-delete-pane"[\s\S]*class="work-delete-button"[\s\S]*catchtap="handleDeleteWorkTap"[\s\S]*删除/)
  assert.match(worksWxss, /\.work-swipe-row\.revealed \.work-card\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(worksWxss, /\.work-delete-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(worksWxss, /\.work-delete-button\s*\{[\s\S]*width:\s*128rpx;[\s\S]*height:\s*100%;[\s\S]*border-radius:\s*0;/)
  assert.match(worksWxml, /class="batch-panel"/)
  assert.match(worksWxml, /class="list-actions"[\s\S]*class="text-action \{\{batchMode \? 'active' : ''\}\}"[\s\S]*class="tag-add-button work-add-button"[\s\S]*catchtap="handleAddTap"[\s\S]*\+/)
  assert.doesNotMatch(worksWxml, /class="primary-button full page-add-button"/)
  assert.match(worksWxml, /class="empty-logo-frame"[\s\S]*<image[\s\S]*class="empty-logo"[\s\S]*src="\/assets\/system\/work-logo-100kb\.jpg"[\s\S]*mode="aspectFit"/)
  assert.doesNotMatch(worksWxml, /class="empty-icon"/)
  assert.match(worksWxss, /\.empty-logo-frame\s*\{[\s\S]*overflow:\s*hidden;[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.42\);/)
  assert.doesNotMatch(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.5\);/)
  assert.match(worksWxml, /class="library-panel"[\s\S]*class="list-actions"[\s\S]*class="batch-panel"/)
  assert.match(worksWxml, /class="batch-panel" wx:if="\{\{batchMode && !loading && !errorMessage\}\}"/)
  assert.match(worksWxml, /class="batch-heading"[\s\S]*class="batch-copy"[\s\S]*class="batch-heading-actions"[\s\S]*class="batch-count"[\s\S]*class="batch-select-all"[\s\S]*bindtap="handleSelectAllBatchTap"[\s\S]*\{\{batchSelectAllText\}\}/)
  assert.match(worksWxml, /bindtap="handleBatchDeleteTap"/)
  assert.match(worksWxml, /bindtap="handleBatchPortfolioTap"/)
  assert.match(worksWxml, /bindtap="handleOpenSortMode"/)
  assert.match(worksWxml, /class="sort-mode-mask \{\{sortMode \? 'visible' : ''\}\}"/)
  assert.doesNotMatch(worksWxml, /class="sort-mode-mask" wx:if="\{\{sortMode\}\}"/)
  assert.match(worksWxml, /class="sort-work-row \{\{sortDraggingWorkId === item\.id \? 'dragging' : ''\}\}"[\s\S]*style="\{\{sortDraggingWorkId === item\.id \? sortDragStyle : ''\}\}"[\s\S]*bindlongpress="handleSortDragStart"[\s\S]*bindtouchmove="handleSortDragMove"[\s\S]*bindtouchend="handleSortDragEnd"[\s\S]*bindtouchcancel="handleSortDragCancel"/)
  assert.match(worksWxml, /class="sort-drag-handle"/)
  assert.doesNotMatch(worksWxml, /class="sort-move-button"/)
  assert.doesNotMatch(worksWxml, />上移<\/button>/)
  assert.doesNotMatch(worksWxml, />下移<\/button>/)
  assert.match(worksWxml, /catchtap="handleSaveSort"/)
  assert.doesNotMatch(worksWxml, /class="empty-state"[\s\S]*bindtap="handleAddTap"[\s\S]*<\/view>\s*<view wx:else class="work-list"/)
  assert.doesNotMatch(worksWxml, /class="summary-strip"/)
  assert.doesNotMatch(worksWxml, /class="works-toolbar"/)
  assert.match(worksWxss, /\.filter-shell\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.works-content\s*\{[\s\S]*height:\s*100%;[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*padding:\s*28rpx 28rpx calc\(144rpx \+ env\(safe-area-inset-bottom\)\);/)
  assert.match(worksWxss, /\.library-panel\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*min-height:\s*0;[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(worksWxss, /\.work-list-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;[\s\S]*min-height:\s*0;[\s\S]*margin-top:\s*18rpx;/)
  assert.match(worksWxss, /\.sort-work-row\.dragging\s*\{[\s\S]*border-color:\s*#3d6fad;/)
  assert.match(worksWxss, /\.sort-work-row\s*\{[\s\S]*transition:\s*transform 160ms cubic-bezier\(0\.2, 0, 0, 1\)/)
  assert.match(worksWxss, /\.sort-work-row\.dragging\s*\{[\s\S]*will-change:\s*transform;/)
  assert.match(worksWxss, /\.sort-drag-handle\s*\{[\s\S]*width:\s*56rpx;[\s\S]*height:\s*64rpx;/)
  assert.doesNotMatch(worksWxss, /\.sort-move-button\s*\{/)
  assert.match(worksWxss, /\.tag-add-button\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.tag-delete\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*<text class="tag-delete-mark">×<\/text>[\s\S]*<\/view>/)
  assert.match(worksWxss, /\.tag-delete-mark\s*\{[\s\S]*transform:\s*translateY\(-1rpx\);/)
  assert.match(worksWxml, /class="tag-dialog-grabber"/)
  assert.match(worksWxss, /\.tag-dialog\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*flex-end;[\s\S]*padding:\s*28rpx;/)
  assert.match(worksWxss, /\.tag-dialog-panel\s*\{[\s\S]*position:\s*relative;[\s\S]*width:\s*100%;[\s\S]*border-radius:\s*24rpx 24rpx 18rpx 18rpx;/)
  assert.match(worksWxss, /\.work-edit-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(worksWxss, '.tag-dialog', '.tag-dialog-panel')
  assertSoftLayerAnimation(worksWxss, '.work-edit-mask', '.work-edit-panel')
  assertSoftLayerAnimation(worksWxss, '.sort-mode-mask', '.sort-mode-panel')
  assertSoftLayerAnimation(worksWxss, '.video-preview-mask', '.video-preview-panel')
  assert.match(worksWxss, /\.work-edit-panel\s*\{[\s\S]*height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(worksWxss, /\.work-edit-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;/)
  const imageEditPanelRule = readRule(worksWxss, '.image-edit-mask .work-edit-panel')
  const imageEditScrollRule = readRule(worksWxss, '.image-edit-mask .work-edit-scroll')
  const videoEditPanelRule = readRule(worksWxss, '.video-edit-mask .work-edit-panel')
  const videoEditScrollRule = readRule(worksWxss, '.video-edit-mask .work-edit-scroll')
  assert.match(imageEditPanelRule, /height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(imageEditPanelRule, /max-height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(imageEditPanelRule, /height:\s*auto/)
  assert.match(imageEditScrollRule, /flex:\s*1 1 auto;/)
  assert.match(imageEditScrollRule, /height:\s*0;/)
  assert.match(imageEditScrollRule, /min-height:\s*0;/)
  assert.doesNotMatch(imageEditScrollRule, /height:\s*auto/)
  assert.match(videoEditPanelRule, /height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(videoEditPanelRule, /max-height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(videoEditPanelRule, /height:\s*auto/)
  assert.match(videoEditScrollRule, /flex:\s*1 1 auto;/)
  assert.match(videoEditScrollRule, /height:\s*0;/)
  assert.match(videoEditScrollRule, /min-height:\s*0;/)
  assert.doesNotMatch(videoEditScrollRule, /height:\s*auto/)
  assert.match(worksWxss, /\.field-heading\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(worksWxss, /\.field-limit\s*\{[\s\S]*color:\s*#8b96a3;/)
  assert.match(worksWxss, /\.cover-edit-toolbar\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.cover-use-frame-button\s*\{[\s\S]*min-width:\s*176rpx;/)
  assert.doesNotMatch(worksWxss, /\.frame-export-canvas\s*\{/)
  assert.match(worksWxss, /\.color-grid\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-wrap:\s*wrap;/)
  assert.doesNotMatch(worksWxss, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(worksWxss, /\.color-choice\s*\{[\s\S]*width:\s*31\.3%;[\s\S]*flex:\s*none;/)
  assert.match(worksWxss, /\.tag-scroll\s*\{[\s\S]*height:\s*64rpx;/)
  assert.match(worksWxss, /\.tag-row\s*\{[\s\S]*height:\s*64rpx;[\s\S]*display:\s*inline-flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.tag-pill\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;[\s\S]*display:\s*inline-flex;[\s\S]*flex:\s*0 0 auto;/)
  assert.match(worksWxss, /\.tag-pill\.active\s*\{[\s\S]*box-shadow:\s*0 8rpx 18rpx rgba\(15, 118, 110, 0\.18\);[\s\S]*transform:\s*translateY\(-1rpx\);/)
  assert.match(worksWxss, /\.tag-pill\.active::before\s*\{[\s\S]*content:\s*"";[\s\S]*display:\s*block;[\s\S]*width:\s*10rpx;[\s\S]*height:\s*10rpx;[\s\S]*background:\s*#ffffff;/)
  assert.doesNotMatch(worksWxss, /\.tag-pill\s*\{[\s\S]*min-width:\s*116rpx;/)
  assert.match(worksWxss, /\.list-heading,\s*[\s\S]*\.list-actions,\s*[\s\S]*\.batch-heading\s*\{[\s\S]*width:\s*100%;[\s\S]*justify-content:\s*space-between;/)
  assert.match(worksWxss, /\.section-title,\s*[\s\S]*\.batch-title\s*\{[\s\S]*flex:\s*1 1 auto;/)
  assert.match(worksWxss, /\.list-actions\s*\{[\s\S]*width:\s*auto;[\s\S]*flex:\s*none;[\s\S]*gap:\s*14rpx;/)
  assert.match(worksWxss, /\.work-add-button\s*\{[\s\S]*flex:\s*none;/)
  assert.doesNotMatch(worksWxss, /\.page-add-button\s*\{/)
  assert.match(worksWxss, /\.text-action\s*\{[\s\S]*min-width:\s*128rpx;[\s\S]*max-width:\s*128rpx;/)
  assert.match(worksWxss, /\.batch-copy\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*min-width:\s*0;/)
  assert.match(worksWxss, /\.batch-heading-actions\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;[\s\S]*flex:\s*none;[\s\S]*gap:\s*12rpx;/)
  assert.match(worksWxss, /\.batch-select-all\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*88rpx;[\s\S]*max-width:\s*136rpx;[\s\S]*height:\s*50rpx;/)
  assert.match(addJs, /createChooseMediaOptions/)
  assert.match(addJs, /buildUploadCompleteFailureMessage/)
  assert.match(addJs, /buildUploadProgressSummary/)
  assert.doesNotMatch(addJs, /failedItems\[0\]/)
  assert.match(addWxml, /一次最多勾选 9 个/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*已选作品[\s\S]*\{\{files\.length\}\} \/ 9[\s\S]*class="selected-work-list(?:\s|")/)
  assert.match(addWxml, /class="selected-work-list count-\{\{files\.length > 3 \? 'many' : files\.length\}\}"/)
  assert.match(addWxml, /class="selected-work-row"[\s\S]*\{\{item\.title \|\| item\.fileName\}\}[\s\S]*\{\{item\.metaText\}\}/)
  assert.match(addWxml, /class="selected-work-progress"[\s\S]*class="selected-work-progress-fill"[\s\S]*customCoverProgress[\s\S]*item\.progress/)
  assert.match(addWxml, /class="selected-work-thumb \{\{item\.isVideo \? 'video' : ''\}\}"/)
  assert.match(addWxml, /class="selected-work-swipe-row \{\{revealedFileId === item\.id \? 'revealed' : ''\}\}"/)
  assert.match(addWxml, /bindtouchstart="handleFileTouchStart"[\s\S]*bindtouchmove="handleFileTouchMove"[\s\S]*bindtouchend="handleFileTouchEnd"/)
  assert.match(addWxml, /class="selected-work-remove-pane"[\s\S]*class="selected-work-remove-button"[\s\S]*catchtap="handleRemoveFile"[\s\S]*移除/)
  assert.match(addWxml, /class="selected-work-row"[\s\S]*bindtap="handleOpenFileEditor"[\s\S]*\{\{item\.title \|\| item\.fileName\}\}/)
  assert.match(addWxml, /class="work-edit-mask \{\{editForm\.isVideo \? 'video-edit-mask' : 'image-edit-mask'\}\} \{\{editSheetVisible \? 'visible' : ''\}\}"[\s\S]*class="work-edit-panel"/)
  assert.doesNotMatch(addWxml, /class="work-edit-mask" wx:if="\{\{editSheetVisible\}\}"/)
  assert.match(addWxml, /<image wx:if="\{\{!editForm\.isVideo\}\}" class="work-preview-media" src="\{\{editForm\.tempFilePath\}\}" mode="aspectFit"><\/image>/)
  assert.doesNotMatch(addWxml, /<image wx:if="\{\{!editForm\.isVideo\}\}" class="work-preview-media" src="\{\{editForm\.tempFilePath\}\}" mode="aspectFill"><\/image>/)
  assert.match(addWxml, /placeholder="填写作品标题"[\s\S]*bindinput="handleEditInput"/)
  assert.match(addWxml, /placeholder="填写作品说明"[\s\S]*maxlength="1000"[\s\S]*bindinput="handleEditInput"/)
  assert.doesNotMatch(addWxml, /wx:if="\{\{editForm\.isVideo\}\}"[\s\S]*class="cover-edit-toolbar"/)
  assert.doesNotMatch(addWxml, /id="workCoverVideo"/)
  assert.doesNotMatch(addWxml, /class="cover-slider"/)
  assert.doesNotMatch(addWxml, /class="cover-export-button"[\s\S]*bindtap="handleExportVideoCover"[\s\S]*使用当前帧做封面/)
  assert.doesNotMatch(addWxml, /id="workCoverCanvas"/)
  assert.doesNotMatch(addWxml, /canvas-id="workCoverCanvas"/)
  assert.match(addWxml, /<view class="tag-panel">[\s\S]*统一标签（可选）[\s\S]*class="tag-add-trigger"[\s\S]*catchtap="handleOpenTagPicker"[\s\S]*\+添加[\s\S]*作品说明可保存后补充/)
  assert.match(addWxml, /wx:for="\{\{unifiedTags\}\}"[\s\S]*class="tag-chip"[\s\S]*style="\{\{item\.style\}\}"[\s\S]*\{\{item\.name\}\}/)
  assert.doesNotMatch(addWxml, /class="tag-chip \{\{index === 1 \? 'blue' : 'teal'\}\}"/)
  assert.doesNotMatch(addWxml, /<view wx:if="\{\{files\.length > 0\}\}" class="tag-panel">/)
  assert.match(addWxml, /class="tag-note" wx:if="\{\{files\.length > 0\}\}"/)
  assert.match(addWxml, /class="tag-note muted" wx:else/)
  assert.match(addWxml, /class="primary-button \{\{files\.length === 0 \? 'empty-disabled' : ''\}\}"/)
  assert.match(addWxml, /class="primary-button-label"[\s\S]*\{\{saving \? uploadOverallText : '保存作品'\}\}/)
  assert.match(addWxml, /class="primary-button-progress"[\s\S]*class="primary-button-progress-fill"[\s\S]*width:\s*\{\{uploadOverallProgress\}\}%/)
  assert.match(addWxml, /disabled="\{\{saving\}\}"/)
  assert.doesNotMatch(addWxml, /disabled="\{\{saving \|\| files\.length === 0\}\}"/)
  assert.doesNotMatch(addWxml, /placeholder="统一标签"/)
  assert.doesNotMatch(addWxml, /class="tag-input"/)
  assert.match(addWxml, /class="tag-picker-mask \{\{tagPickerVisible \? 'visible' : ''\}\}"[\s\S]*class="tag-picker-panel"/)
  assert.doesNotMatch(addWxml, /class="tag-picker-mask" wx:if="\{\{tagPickerVisible\}\}"/)
  assert.match(addWxml, /<scroll-view wx:else class="tag-option-list"[^>]*style="height:\s*\{\{tagOptionListHeight\}\}rpx;"/)
  assert.match(addWxml, /wx:for="\{\{tagPickerTags\}\}"[\s\S]*class="tag-option \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*catchtap="handleToggleUnifiedTag"/)
  assert.match(addWxml, /class="tag-picker-confirm"[\s\S]*catchtap="handleConfirmTagPicker"[\s\S]*完成/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*class="tag-panel"[\s\S]*class="error-copy"/)
  assert.doesNotMatch(addWxml, /class="selected-card"/)
  assert.doesNotMatch(addWxml, /class="desc-input"/)
  assert.match(addJs, /WORK_TAGS_API_URL\s*=\s*'\/api\/mine\/works\/tags'/)
  assert.match(addJs, /handleOpenFileEditor/)
  assert.match(addJs, /handleFileTouchStart/)
  assert.doesNotMatch(addJs, /handleExportVideoCover/)
  assert.doesNotMatch(addJs, /createVideoDecoder/)
  assert.doesNotMatch(addJs, /writeRgbaFrameToCanvas/)
  assert.doesNotMatch(addJs, /wx\.canvasPutImageData/)
  assert.match(worksJs, /coverEditMode:\s*''/)
  assert.match(worksJs, /handleChooseVideoCoverUpload/)
  assert.match(worksJs, /uploadVideoCoverOnConfirm/)
  assert.match(worksJs, /coverTaskId/)
  assert.match(addJs, /normalizeWorkTags/)
  assert.match(addJs, /handleOpenTagPicker/)
  assert.match(addJs, /handleToggleUnifiedTag/)
  assert.match(addJs, /handleConfirmTagPicker/)
  assert.match(addWxss, /\.work-add-content\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(addWxss, /\.upload-box\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.empty-state\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;/)
  assert.match(addWxss, /\.primary-button\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.primary-button\.empty-disabled\s*\{[\s\S]*color:\s*#5f6b78;[\s\S]*background:\s*#e6ebf0;[\s\S]*box-shadow:\s*none;/)
  assert.match(addWxss, /\.tag-note\s*\{[\s\S]*margin-top:\s*16rpx;[\s\S]*padding:\s*18rpx 20rpx;/)
  assert.match(addWxss, /\.tag-note\.muted\s*\{[\s\S]*color:\s*#7b8794;/)
  assert.match(addWxss, /\.tag-add-trigger\s*\{[\s\S]*width:\s*auto;[\s\S]*height:\s*50rpx;[\s\S]*flex:\s*0 0 auto;[\s\S]*align-self:\s*flex-start;/)
  assert.match(addWxss, /\.cover-edit-toolbar\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(addWxss, /\.cover-use-frame-button\s*\{[\s\S]*min-width:\s*176rpx;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*border:\s*1rpx solid #d7dee5;[\s\S]*border-radius:\s*16rpx;/)
  assert.match(addWxss, /\.selected-work-list\s*\{[\s\S]*height:\s*528rpx;[\s\S]*max-height:\s*528rpx;[\s\S]*overflow:\s*hidden;/)
  assert.match(addWxss, /\.selected-work-list\.count-1\s*\{[\s\S]*height:\s*160rpx;/)
  assert.match(addWxss, /\.selected-work-list\.count-2\s*\{[\s\S]*height:\s*336rpx;/)
  assert.match(addWxss, /\.selected-work-list\.count-3\s*\{[\s\S]*height:\s*512rpx;/)
  assert.match(addWxss, /\.selected-work-list-content\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(addWxss, /\.selected-work-row\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.doesNotMatch(addWxss, /\.selected-work-row\s*\{[\s\S]*grid-template-columns:/)
  assert.match(addWxss, /\.selected-work-copy\s*\{[\s\S]*flex:\s*1 1 0;[\s\S]*min-width:\s*0;/)
  assert.match(addWxss, /\.selected-work-progress\s*\{[\s\S]*width:\s*100%;/)
  assert.match(addWxss, /\.selected-work-progress-fill\s*\{[\s\S]*height:\s*100%;/)
  assert.match(addWxss, /\.selected-work-swipe-row\.revealed \.selected-work-row\s*\{[\s\S]*transform:\s*translateX\(-140rpx\);/)
  assert.match(addWxss, /\.selected-work-remove-pane\s*\{[\s\S]*position:\s*absolute;[\s\S]*right:\s*0;[\s\S]*width:\s*128rpx;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.doesNotMatch(addWxss, /\.tag-panel\s*\{[\s\S]*display:\s*grid;/)
  assert.match(addWxss, /\.tag-row\s*\{[\s\S]*margin-top:\s*12rpx;[\s\S]*display:\s*flex;/)
  assert.match(addWxss, /\.tag-picker-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(addWxss, '.tag-picker-mask', '.tag-picker-panel')
  const addTagOptionListRule = readRule(addWxss, '.tag-option-list')
  assert.match(addTagOptionListRule, /max-height:\s*520rpx;/)
  assert.match(addTagOptionListRule, /flex:\s*none;/)
  assert.doesNotMatch(addTagOptionListRule, /(^|\n)\s*height:\s*320rpx;/)
  assert.match(addWxss, /\.tag-option\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*space-between;/)
  assert.match(addWxss, /\.work-edit-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assertSoftLayerAnimation(addWxss, '.work-edit-mask', '.work-edit-panel')
  assert.match(addWxss, /\.work-edit-panel\s*\{[\s\S]*height:\s*calc\(84vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(addWxss, /\.work-edit-scroll\s*\{[\s\S]*flex:\s*1 1 auto;[\s\S]*height:\s*0;/)
  assert.match(addWxss, /\.image-edit-mask \.work-edit-panel\s*\{[\s\S]*height:\s*auto;[\s\S]*max-height:\s*calc\(78vh - env\(safe-area-inset-bottom\)\);/)
  assert.match(addWxss, /\.image-edit-mask \.work-edit-scroll\s*\{[\s\S]*flex:\s*0 1 auto;[\s\S]*height:\s*auto;[\s\S]*max-height:\s*calc\(78vh - 176rpx - env\(safe-area-inset-bottom\)\);/)
  assert.doesNotMatch(addWxss, /\.work-edit-scroll\s*\{[\s\S]*max-height:\s*64vh;/)
  assert.match(addWxss, /\.primary-button-progress\s*\{[\s\S]*width:\s*240rpx;[\s\S]*height:\s*8rpx;/)
  assert.doesNotMatch(addWxss, /\.frame-export-canvas\s*\{/)
  assert.match(editWxml, /引用/)
  assert.match(editWxml, /保存/)
})
