const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../app.json'), 'utf8'))

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

test('app registers works pages in the mini program', () => {
  assert.ok(appJson.pages.includes('pages/works/works'))
  assert.ok(appJson.pages.includes('pages/work-add/work-add'))
  assert.ok(appJson.pages.includes('pages/work-edit/work-edit'))
})

test('mine and schedule bottom tabs navigate to works page', () => {
  const indexJs = read('pages/index/index.js')
  const scheduleJs = read('pages/schedule/schedule.js')

  assert.match(indexJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
  assert.match(scheduleJs, /WORKS_PAGE_URL\s*=\s*'\/pages\/works\/works'/)
})

test('works pages expose expected upload and edit structure', () => {
  const worksWxml = read('pages/works/works.wxml')
  const worksWxss = read('pages/works/works.wxss')
  const addJs = read('pages/work-add/work-add.js')
  const addWxml = read('pages/work-add/work-add.wxml')
  const addWxss = read('pages/work-add/work-add.wxss')
  const editWxml = read('pages/work-edit/work-edit.wxml')

  assert.match(worksWxml, /搜索作品标题、标签/)
  assert.match(worksWxml, /批量管理/)
  assert.match(worksWxml, /class="works-content" bindtap="handleCloseTagManageMode"/)
  assert.match(worksWxml, /class="filter-panel"/)
  assert.match(worksWxml, /class="filter-shell" catchtap="handleFilterShellTap"/)
  assert.match(worksWxml, /<view[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.doesNotMatch(worksWxml, /<button[\s\S]*wx:for="\{\{list\.filterTags\}\}"[\s\S]*class="tag-pill/)
  assert.match(worksWxml, /bindlongpress="handleTagLongPress"/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*catchtap="handleTagDeleteTap"/)
  assert.match(worksWxml, /class="tag-add-button"[\s\S]*catchtap="handleOpenCreateTagDialog"[\s\S]*\+/)
  assert.doesNotMatch(worksWxml, /<button[\s\S]*class="tag-add-button/)
  assert.match(worksWxml, /class="tag-dialog" wx:if="\{\{tagDialogVisible\}\}"/)
  assert.match(worksWxml, /标签文字/)
  assert.match(worksWxml, /标签颜色/)
  assert.match(worksWxml, /wx:for="\{\{tagColorOptions\}\}"/)
  assert.match(worksWxml, /class="library-panel"/)
  assert.match(worksWxml, /class="reference-pill/)
  assert.match(worksWxml, /class="batch-panel"/)
  assert.match(worksWxml, /class="primary-button full page-add-button"/)
  assert.match(worksWxml, /class="empty-logo-frame"[\s\S]*<image[\s\S]*class="empty-logo"[\s\S]*src="https:\/\/cos\.we-folio\.dingchenyong\.top\/system\/work-logo-100kb\.jpg"[\s\S]*mode="aspectFit"/)
  assert.doesNotMatch(worksWxml, /class="empty-icon"/)
  assert.match(worksWxss, /\.empty-logo-frame\s*\{[\s\S]*overflow:\s*hidden;[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.42\);/)
  assert.doesNotMatch(worksWxss, /\.empty-logo\s*\{[\s\S]*transform:\s*scale\(1\.5\);/)
  assert.match(worksWxml, /class="library-panel"[\s\S]*class="primary-button full page-add-button"[\s\S]*class="batch-panel"/)
  assert.match(worksWxml, /class="batch-panel" wx:if="\{\{!loading && !errorMessage\}\}"/)
  assert.doesNotMatch(worksWxml, /class="empty-state"[\s\S]*bindtap="handleAddTap"[\s\S]*<\/view>\s*<view wx:else class="work-list"/)
  assert.doesNotMatch(worksWxml, /class="summary-strip"/)
  assert.doesNotMatch(worksWxml, /class="works-toolbar"/)
  assert.match(worksWxss, /\.filter-shell\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*center;/)
  assert.match(worksWxss, /\.tag-add-button\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxss, /\.tag-delete\s*\{[\s\S]*border-radius:\s*50%;/)
  assert.match(worksWxml, /class="tag-delete"[\s\S]*<text class="tag-delete-mark">×<\/text>[\s\S]*<\/view>/)
  assert.match(worksWxss, /\.tag-delete-mark\s*\{[\s\S]*transform:\s*translateY\(-1rpx\);/)
  assert.match(worksWxml, /class="tag-dialog-grabber"/)
  assert.match(worksWxss, /\.tag-dialog\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*flex-end;[\s\S]*padding:\s*28rpx;/)
  assert.match(worksWxss, /\.tag-dialog-panel\s*\{[\s\S]*position:\s*relative;[\s\S]*width:\s*100%;[\s\S]*border-radius:\s*24rpx 24rpx 18rpx 18rpx;/)
  assert.match(worksWxss, /\.color-grid\s*\{[\s\S]*display:\s*grid;/)
  assert.match(worksWxss, /\.tag-row\s*\{[\s\S]*display:\s*inline-flex;[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;/)
  assert.match(worksWxss, /\.tag-pill\s*\{[\s\S]*width:\s*auto;[\s\S]*min-width:\s*0;[\s\S]*display:\s*inline-flex;[\s\S]*flex:\s*0 0 auto;/)
  assert.doesNotMatch(worksWxss, /\.tag-pill\s*\{[\s\S]*min-width:\s*116rpx;/)
  assert.match(worksWxss, /\.list-heading,\s*[\s\S]*\.batch-heading\s*\{[\s\S]*width:\s*100%;[\s\S]*justify-content:\s*space-between;/)
  assert.match(worksWxss, /\.section-title,\s*[\s\S]*\.batch-title\s*\{[\s\S]*flex:\s*1 1 auto;/)
  assert.match(worksWxss, /\.text-action\s*\{[\s\S]*margin:\s*0 0 0 auto;/)
  assert.match(worksWxss, /\.page-add-button\s*\{[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;/)
  assert.match(worksWxss, /\.text-action\s*\{[\s\S]*min-width:\s*128rpx;[\s\S]*max-width:\s*128rpx;/)
  assert.match(addJs, /createChooseMediaOptions/)
  assert.match(addJs, /buildUploadCompleteFailureMessage/)
  assert.doesNotMatch(addJs, /failedItems\[0\]/)
  assert.match(addWxml, /一次最多勾选 9 个/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*已选作品[\s\S]*\{\{files\.length\}\} \/ 9[\s\S]*class="selected-work-list"/)
  assert.match(addWxml, /class="selected-work-row"[\s\S]*\{\{item\.fileName\}\}[\s\S]*\{\{item\.metaText\}\}/)
  assert.match(addWxml, /class="selected-work-thumb \{\{item\.isVideo \? 'video' : ''\}\}"/)
  assert.match(addWxml, /<view class="tag-panel">[\s\S]*统一标签（可选）[\s\S]*class="tag-add-trigger"[\s\S]*catchtap="handleOpenTagPicker"[\s\S]*\+添加[\s\S]*作品说明可保存后补充/)
  assert.match(addWxml, /wx:for="\{\{unifiedTags\}\}"[\s\S]*class="tag-chip"[\s\S]*style="\{\{item\.style\}\}"[\s\S]*\{\{item\.name\}\}/)
  assert.doesNotMatch(addWxml, /class="tag-chip \{\{index === 1 \? 'blue' : 'teal'\}\}"/)
  assert.doesNotMatch(addWxml, /<view wx:if="\{\{files\.length > 0\}\}" class="tag-panel">/)
  assert.match(addWxml, /class="tag-note" wx:if="\{\{files\.length > 0\}\}"/)
  assert.match(addWxml, /class="tag-note muted" wx:else/)
  assert.match(addWxml, /class="primary-button \{\{files\.length === 0 \? 'empty-disabled' : ''\}\}"/)
  assert.match(addWxml, /disabled="\{\{saving\}\}"/)
  assert.doesNotMatch(addWxml, /disabled="\{\{saving \|\| files\.length === 0\}\}"/)
  assert.doesNotMatch(addWxml, /placeholder="统一标签"/)
  assert.doesNotMatch(addWxml, /class="tag-input"/)
  assert.match(addWxml, /class="tag-picker-mask" wx:if="\{\{tagPickerVisible\}\}"[\s\S]*class="tag-picker-panel"/)
  assert.match(addWxml, /wx:for="\{\{tagPickerTags\}\}"[\s\S]*class="tag-option \{\{item\.selected \? 'selected' : ''\}\}"[\s\S]*catchtap="handleToggleUnifiedTag"/)
  assert.match(addWxml, /class="tag-picker-confirm"[\s\S]*catchtap="handleConfirmTagPicker"[\s\S]*完成/)
  assert.match(addWxml, /class="upload-box"[\s\S]*class="selected-panel"[\s\S]*class="tag-panel"[\s\S]*class="error-copy"/)
  assert.doesNotMatch(addWxml, /class="selected-card"/)
  assert.doesNotMatch(addWxml, /class="desc-input"/)
  assert.match(addJs, /WORK_TAGS_API_URL\s*=\s*'\/api\/mine\/works\/tags'/)
  assert.match(addJs, /normalizeWorkTags/)
  assert.match(addJs, /handleOpenTagPicker/)
  assert.match(addJs, /handleToggleUnifiedTag/)
  assert.match(addJs, /handleConfirmTagPicker/)
  assert.match(addWxss, /\.work-add-content\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;/)
  assert.match(addWxss, /\.upload-box\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.empty-state\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*box-sizing:\s*border-box;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;/)
  assert.match(addWxss, /\.primary-button\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*align-self:\s*stretch;/)
  assert.match(addWxss, /\.primary-button\.empty-disabled\s*\{[\s\S]*color:\s*#5f6b78;[\s\S]*background:\s*#e6ebf0;[\s\S]*box-shadow:\s*none;/)
  assert.match(addWxss, /\.tag-note\.muted\s*\{[\s\S]*color:\s*#7b8794;/)
  assert.match(addWxss, /\.tag-add-trigger\s*\{[\s\S]*width:\s*auto;[\s\S]*flex:\s*0 0 auto;[\s\S]*align-self:\s*flex-start;/)
  assert.match(addWxss, /\.selected-panel\s*\{[\s\S]*border:\s*1rpx solid #d7dee5;[\s\S]*border-radius:\s*16rpx;/)
  assert.match(addWxss, /\.selected-work-list\s*\{[\s\S]*max-height:\s*528rpx;[\s\S]*overflow:\s*hidden;/)
  assert.match(addWxss, /\.selected-work-row\s*\{[\s\S]*grid-template-columns:\s*112rpx minmax\(0,\s*1fr\) auto;/)
  assert.match(addWxss, /\.tag-panel\s*\{[\s\S]*display:\s*grid;[\s\S]*gap:\s*16rpx;/)
  assert.match(addWxss, /\.tag-picker-mask\s*\{[\s\S]*position:\s*fixed;[\s\S]*align-items:\s*flex-end;/)
  assert.match(addWxss, /\.tag-option\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*space-between;/)
  assert.match(editWxml, /引用/)
  assert.match(editWxml, /保存/)
})
